const VOCAB = [

  // ═══ УРОВЕНЬ 1 — СЛОВА ═══

  // -- Местоимения --
  { en: 'I (male speaker)', trans: 'pom', thai: 'ผม', level: 1 },
  { en: 'I (female speaker)', trans: 'chan', thai: 'ฉัน', level: 1 },
  { en: 'YOU', trans: 'kun', thai: 'คุณ', level: 1 },
  { en: 'WE', trans: 'rao', thai: 'เรา', level: 1 },
  { en: 'SHE', trans: 'ter', thai: 'เธอ', level: 1 },
  { en: 'HE/THEY', trans: 'kao', thai: 'เขา', level: 1 },
  { en: 'IT', trans: 'man', thai: 'มัน', level: 1 },
  { en: 'PLURAL ARTICLE', trans: 'puuak', thai: 'พวก', level: 1 },

  // -- Частицы --
  { en: 'HELLO/GOODBYE', trans: 'sa-watdii', thai: 'สวัสดี', level: 1 },
  { en: 'POLITE ARTICLE (FEMALE SPEAKER)', trans: 'ka', thai: 'ค่ะ', level: 1 },
  { en: 'POLITE ARTICLE (MALE)', trans: 'krap', thai: 'ครับ', level: 1 },
  { en: 'THANK YOU', trans: 'korp-kun', thai: 'ขอบคุณ', level: 1 },
  { en: 'NAME', trans: 'cheuu', thai: 'ชื่อ', level: 1 },
  { en: 'QUESTION WORD', trans: 'mai', thai: 'ไหม', level: 1 },
  { en: 'WHAT ABOUT...?', trans: 'la', thai: 'ล่ะ', level: 1 },
  { en: 'AND', trans: 'gap', thai: 'กับ', level: 1 },
  { en: 'THIS', trans: 'nii', thai: 'นี่', level: 1 },
  { en: 'THAT', trans: 'nan', thai: 'นั่น', level: 1 },
  { en: 'VERY', trans: 'maak', thai: 'มาก', level: 1 },
  { en: '-ING ENDING', trans: 'gam-lang', thai: 'กำลัง', level: 1 },
  { en: 'WILL (future tense)', trans: 'ja', thai: 'จะ', level: 1 },
  { en: 'AT/TO', trans: 'tii', thai: 'ที่', level: 1 },
  { en: 'BY', trans: 'doi', thai: 'โดย', level: 1 },
  { en: 'OR', trans: 'reuu', thai: 'หรือ', level: 1 },
  { en: 'FROM', trans: 'jaak', thai: 'จาก', level: 1 },
  { en: 'IN', trans: 'nai', thai: 'ใน', level: 1 },
  { en: 'ON', trans: 'bon', thai: 'บน', level: 1 },
  { en: 'UNDER', trans: 'dtai', thai: 'ใต้', level: 1 },
  { en: 'OUT OF', trans: 'nork', thai: 'นอก', level: 1 },
  { en: 'PLEASE...', trans: 'noi', thai: 'หน่อย', level: 1 },
  { en: 'POLITE PARTICLE', trans: 'noi', thai: 'หน่อย', level: 1 },
  { en: 'TO BELONG TO', trans: 'korng', thai: 'ของ', level: 1 },
  { en: 'YES (LOCATION)', trans: 'yuu', thai: 'อยู่', level: 1 },
  { en: 'NO (LOCATION)', trans: 'mai-yuu', thai: 'ไม่อยู่', level: 1 },
  { en: 'ONLY', trans: 'taonan', thai: 'เท่านั้น', level: 1 },
  { en: 'EVERY', trans: 'tuk', thai: 'ทุก', level: 1 },
  { en: 'MORE', trans: 'iik', thai: 'อีก', level: 1 },
  { en: 'HALF', trans: 'kreung', thai: 'ครึ่ง', level: 1 },
  { en: 'APPROXIMATELY (ABOUT)', trans: 'bpra-maan', thai: 'ประมาณ', level: 1 },
  { en: 'AFTER', trans: 'lang', thai: 'หลัง', level: 1 },
  { en: 'TOGETHER', trans: 'duai gan', thai: 'ด้วยกัน', level: 1 },
  { en: 'REALLY', trans: 'jing jing', thai: 'จริงจริง', level: 1 },
  { en: 'SLOWLY', trans: 'chaa chaa', thai: 'ช้าช้า', level: 1 },
  { en: 'PLEASE DON\'T...', trans: 'yaa', thai: 'อย่า', level: 1 },
  { en: 'FORBIDDEN', trans: 'haam', thai: 'ห้าม', level: 1 },
  { en: 'SHOULD', trans: 'naa ja', thai: 'น่าจะ', level: 1 },
  { en: 'WOULD LIKE', trans: 'ao', thai: 'เอา', level: 1 },
  { en: 'WOULD LIKE (FREE)', trans: 'kor', thai: 'ขอ', level: 1 },
  { en: 'NOT', trans: 'mai', thai: 'ไม่', level: 1 },
  { en: 'YES / CORRECT', trans: 'chai', thai: 'ใช่', level: 1 },
  { en: 'ALREADY', trans: 'laeo', thai: 'แล้ว', level: 1 },
  { en: 'STILL / YET', trans: 'yang', thai: 'ยัง', level: 1 },
  { en: 'ALSO / TOO', trans: 'duai', thai: 'ด้วย', level: 1 },

  // -- Вопросительные слова --
  { en: 'WHAT', trans: 'arai', thai: 'อะไร', level: 1 },
  { en: 'WHO?', trans: 'krai?', thai: 'ใคร?', level: 1 },
  { en: 'WHERE', trans: 'tii-nai', thai: 'ที่ไหน', level: 1 },
  { en: 'WHEN?', trans: 'meua-rai?', thai: 'เมื่อไร?', level: 1 },
  { en: 'HOW?', trans: 'yaang-rai?', thai: 'อย่างไร?', level: 1 },
  { en: 'WHY?', trans: 'tam-mai?', thai: 'ทำไม?', level: 1 },
  { en: 'WHICH?', trans: 'nai', thai: 'ไหน', level: 1 },
  { en: 'HOW MUCH', trans: 'taorai', thai: 'เท่าไร', level: 1 },

  // -- Числа 1–10 --
  { en: 'ONE', trans: 'neung', thai: 'หนึ่ง', level: 1 },
  { en: 'TWO', trans: 'sorng', thai: 'สอง', level: 1 },
  { en: 'THREE', trans: 'saam', thai: 'สาม', level: 1 },
  { en: 'FOUR', trans: 'sii', thai: 'สี่', level: 1 },
  { en: 'FIVE', trans: 'haa', thai: 'ห้า', level: 1 },
  { en: 'SIX', trans: 'hok', thai: 'หก', level: 1 },
  { en: 'SEVEN', trans: 'jet', thai: 'เจ็ด', level: 1 },
  { en: 'EIGHT', trans: 'bpaet', thai: 'แปด', level: 1 },
  { en: 'NINE', trans: 'gao', thai: 'เก้า', level: 1 },
  { en: 'TEN', trans: 'sip', thai: 'สิบ', level: 1 },
  { en: 'ONE HUNDRED', trans: 'roi', thai: 'ร้อย', level: 1 },
  { en: 'THOUSAND', trans: 'pan', thai: 'พัน', level: 1 },
  { en: 'NUMBER', trans: 'lek', thai: 'เลข', level: 1 },

  // -- Глаголы --
  { en: 'TO BE', trans: 'bpen', thai: 'เป็น', level: 1 },
  { en: 'TO HAVE...', trans: 'mii', thai: 'มี', level: 1 },
  { en: 'TO WANT', trans: 'yaak', thai: 'อยาก', level: 1 },
  { en: 'TO NEED', trans: 'dtorng gaan', thai: 'ต้องการ', level: 1 },
  { en: 'TO LIKE', trans: 'chorp', thai: 'ชอบ', level: 1 },
  { en: 'TO LOVE', trans: 'rak', thai: 'รัก', level: 1 },
  { en: 'GO', trans: 'bpai', thai: 'ไป', level: 1 },
  { en: 'TO COME', trans: 'maa', thai: 'มา', level: 1 },
  { en: 'GO BACK/RETURN', trans: 'glap', thai: 'กลับ', level: 1 },
  { en: 'TO DO', trans: 'tam', thai: 'ทำ', level: 1 },
  { en: 'TO EAT', trans: 'gin', thai: 'กิน', level: 1 },
  { en: 'TO DRINK', trans: 'deuum', thai: 'ดื่ม', level: 1 },
  { en: 'TO STUDY', trans: 'rian', thai: 'เรียน', level: 1 },
  { en: 'TO READ', trans: 'aan', thai: 'อ่าน', level: 1 },
  { en: 'TO WRITE', trans: 'kian', thai: 'เขียน', level: 1 },
  { en: 'TO LOOK', trans: 'duu', thai: 'ดู', level: 1 },
  { en: 'SPEAK', trans: 'puut', thai: 'พูด', level: 1 },
  { en: 'TO UNDERSTAND', trans: 'kao-jai', thai: 'เข้าใจ', level: 1 },
  { en: 'TO KNOW', trans: 'ruu', thai: 'รู้', level: 1 },
  { en: 'TO THINK', trans: 'kit', thai: 'คิด', level: 1 },
  { en: 'TO FIND', trans: 'jer', thai: 'เจอ', level: 1 },
  { en: 'TO PLAY', trans: 'leen', thai: 'เล่น', level: 1 },
  { en: 'TO RUN', trans: 'wing', thai: 'วิ่ง', level: 1 },
  { en: 'TO DANCE', trans: 'ram', thai: 'รำ', level: 1 },
  { en: 'TO WALK', trans: 'dern', thai: 'เดิน', level: 1 },
  { en: 'STOP', trans: 'jort', thai: 'จอด', level: 1 },
  { en: 'TO TURN', trans: 'liao', thai: 'เลี้ยว', level: 1 },
  { en: 'TO TOUCH', trans: 'jap', thai: 'จับ', level: 1 },
  { en: 'TAKE', trans: 'yip', thai: 'หยิบ', level: 1 },
  { en: 'TO PUT', trans: 'waang', thai: 'วาง', level: 1 },
  { en: 'TO WEAR', trans: 'sai', thai: 'ใส่', level: 1 },
  { en: 'TO WASH', trans: 'laang', thai: 'ล้าง', level: 1 },
  { en: 'TO DREAM', trans: 'fan', thai: 'ฝัน', level: 1 },
  { en: 'TO SLEEP', trans: 'norn lap', thai: 'นอนหลับ', level: 1 },
  { en: 'TO FORGET', trans: 'leuum', thai: 'ลืม', level: 1 },
  { en: 'TO COUNT', trans: 'nap', thai: 'นับ', level: 1 },
  { en: 'TO PRACTICE', trans: 'feuk', thai: 'ฝึก', level: 1 },
  { en: 'TO BE FINE', trans: 'sa-baai-dii', thai: 'สบายดี', level: 1 },
  { en: 'TO BE AVAILABLE', trans: 'waang', thai: 'ว่าง', level: 1 },
  { en: 'TO AGREE WITH...', trans: 'hen duai', thai: 'เห็นด้วย', level: 1 },
  { en: 'TO BE ABLE TO (CAN)', trans: 'dai', thai: 'ได้', level: 1 },
  { en: 'HAVING FUN', trans: 'sanuk', thai: 'สนุก', level: 1 },
  { en: 'CELEBRATE', trans: 'cha-lorng', thai: 'ฉลอง', level: 1 },
  { en: 'TO MISS(REGULAR MEETING)', trans: 'kaat', thai: 'ขาด', level: 1 },
  { en: 'FINISH/CLOSE', trans: 'bpit', thai: 'ปิด', level: 1 },
  { en: 'START/OPEN', trans: 'bpert', thai: 'เปิด', level: 1 },
  { en: 'NEXT', trans: 'dtor', thai: 'ต่อ', level: 1 },
  { en: 'SITDOWN', trans: 'nang long', thai: 'นั่งลง', level: 1 },
  { en: 'TO BUY', trans: 'seuu', thai: 'ซื้อ', level: 1 },
  { en: 'TO SELL', trans: 'kaai', thai: 'ขาย', level: 1 },
  { en: 'TO GIVE', trans: 'hai', thai: 'ให้', level: 1 },
  { en: 'TO WAIT', trans: 'ror', thai: 'รอ', level: 1 },
  { en: 'TO HELP', trans: 'chuai', thai: 'ช่วย', level: 1 },
  { en: 'MUST / HAVE TO', trans: 'dtorng', thai: 'ต้อง', level: 1 },
  { en: 'TO TRY', trans: 'lorng', thai: 'ลอง', level: 1 },
  { en: 'TO CALL (phone)', trans: 'toh', thai: 'โทร', level: 1 },
  { en: 'TO PAY', trans: 'jaai', thai: 'จ่าย', level: 1 },
  { en: 'TO ASK', trans: 'taam', thai: 'ถาม', level: 1 },
  { en: 'HOW MANY...', trans: 'gii', thai: 'กี่', level: 1 },
  { en: 'TO PREFER', trans: 'chorp maak gwaa', thai: 'ชอบมากกว่า', level: 1 },
  { en: 'TO SWIM', trans: 'waai-nam', thai: 'ว่ายน้ำ', level: 1 },
  { en: 'TO GET BETTER', trans: 'haai-dii', thai: 'หายดี', level: 1 },
  { en: 'TO CROSS ROAD/STREET', trans: 'kaam ta-non', thai: 'ข้ามถนน', level: 1 },
  { en: 'WORK', trans: 'tam-ngaan', thai: 'ทำงาน', level: 1 },

  // -- Прилагательные --
  { en: 'NICE/GOOD', trans: 'dii', thai: 'ดี', level: 1 },
  { en: 'BIG', trans: 'yai', thai: 'ใหญ่', level: 1 },
  { en: 'SMALL', trans: 'lek', thai: 'เล็ก', level: 1 },
  { en: 'PRETTY', trans: 'suai', thai: 'สวย', level: 1 },
  { en: 'TALL', trans: 'suung', thai: 'สูง', level: 1 },
  { en: 'LOW', trans: 'dtia', thai: 'เตี้ย', level: 1 },
  { en: 'LONG', trans: 'yaao', thai: 'ยาว', level: 1 },
  { en: 'SHORT', trans: 'san', thai: 'สั้น', level: 1 },
  { en: 'SLOW', trans: 'chaa', thai: 'ช้า', level: 1 },
  { en: 'FAST', trans: 'reo', thai: 'เร็ว', level: 1 },
  { en: 'HOT', trans: 'rorn', thai: 'ร้อน', level: 1 },
  { en: 'COLD', trans: 'yen', thai: 'เย็น', level: 1 },
  { en: 'VERY COLD', trans: 'naao', thai: 'หนาว', level: 1 },
  { en: 'SPICY', trans: 'pet', thai: 'เผ็ด', level: 1 },
  { en: 'DELICIOUS', trans: 'aroi', thai: 'อร่อย', level: 1 },
  { en: 'TIRED', trans: 'neuai', thai: 'เหนื่อย', level: 1 },
  { en: 'LATE', trans: 'saai', thai: 'สาย', level: 1 },
  { en: 'POISONOUS', trans: 'mii-pit', thai: 'มีพิษ', level: 1 },
  { en: 'BECAUSE', trans: 'pror-waa', thai: 'เพราะว่า', level: 1 },
  { en: 'TOO (MUCH)', trans: 'gern-bpai', thai: 'เกินไป', level: 1 },
  { en: 'NEAR', trans: 'glai', thai: 'ใกล้', level: 1 },
  { en: 'FAR', trans: 'glai', thai: 'ไกล', level: 1 },
  { en: 'EXPENSIVE', trans: 'paeng', thai: 'แพง', level: 1 },
  { en: 'CHEAP / CORRECT', trans: 'tuuk', thai: 'ถูก', level: 1 },
  { en: 'EASY', trans: 'ngaai', thai: 'ง่าย', level: 1 },
  { en: 'DIFFICULT', trans: 'yaak', thai: 'ยาก', level: 1 },
  { en: 'SWEET', trans: 'waan', thai: 'หวาน', level: 1 },
  { en: 'SOUR', trans: 'bpriao', thai: 'เปรี้ยว', level: 1 },
  { en: 'SALTY', trans: 'kem', thai: 'เค็ม', level: 1 },
  { en: 'BITTER', trans: 'kom', thai: 'ขม', level: 1 },
  { en: 'HUNGRY', trans: 'hio', thai: 'หิว', level: 1 },
  { en: 'FULL (after eating)', trans: 'im', thai: 'อิ่ม', level: 1 },
  { en: 'SAD', trans: 'sia-jai', thai: 'เสียใจ', level: 1 },
  { en: 'ANGRY', trans: 'groht', thai: 'โกรธ', level: 1 },
  { en: 'SCARED', trans: 'dtok-jai', thai: 'ตกใจ', level: 1 },
  { en: 'HAPPY (HIM)', trans: 'suk-san', thai: 'สุขสันต์', level: 1 },
  { en: 'DRUNK', trans: 'mao', thai: 'เมา', level: 1 },
  { en: 'A LITTLE BIT', trans: 'nit noi', thai: 'นิดหน่อย', level: 1 },
  { en: 'EXACTLY', trans: 'dtorng', thai: 'ตรง', level: 1 },
  { en: 'SORRY / EXCUSE ME', trans: 'kor-toht', thai: 'ขอโทษ', level: 1 },

  // -- Семья --
  { en: 'FAMILY', trans: 'krorp-kruua', thai: 'ครอบครัว', level: 1 },
  { en: 'GRANDFATHER', trans: 'dtaa', thai: 'ตา', level: 1 },
  { en: 'GRANDMOTHER', trans: 'yaai', thai: 'ยาย', level: 1 },
  { en: 'MOTHER', trans: 'mae', thai: 'แม่', level: 1 },
  { en: 'FATHER', trans: 'por', thai: 'พ่อ', level: 1 },
  { en: 'CHILD', trans: 'dek', thai: 'เด็ก', level: 1 },
  { en: 'CHILDREN', trans: 'dek dek', thai: 'เด็กเด็ก', level: 1 },
  { en: 'SON OR DAUGHTER', trans: 'luuk', thai: 'ลูก', level: 1 },
  { en: 'FRIENDS', trans: 'peuan', thai: 'เพื่อน', level: 1 },
  { en: 'PERSON', trans: 'kon', thai: 'คน', level: 1 },
  { en: 'TEACHER', trans: 'kruu', thai: 'ครู', level: 1 },
  { en: 'STUDENT', trans: 'nak-rian', thai: 'นักเรียน', level: 1 },
  { en: 'DOCTOR', trans: 'mor', thai: 'หมอ', level: 1 },
  { en: 'NURSE', trans: 'pa-yaa-baan', thai: 'พยาบาล', level: 1 },

  // -- Части тела --
  { en: 'HEAD', trans: 'huua', thai: 'หัว', level: 1 },
  { en: 'FACE', trans: 'naa', thai: 'หน้า', level: 1 },
  { en: 'EYE', trans: 'dtaa', thai: 'ตา', level: 1 },
  { en: 'EAR', trans: 'huu', thai: 'หู', level: 1 },
  { en: 'NECK/THROAT', trans: 'kor', thai: 'คอ', level: 1 },
  { en: 'HANDS', trans: 'meuu', thai: 'มือ', level: 1 },
  { en: 'HAND', trans: 'kaen', thai: 'แขน', level: 1 },
  { en: 'LEG', trans: 'kaa', thai: 'ขา', level: 1 },
  { en: 'FOOT', trans: 'tao', thai: 'เท้า', level: 1 },
  { en: 'MOUTH', trans: 'bpaak', thai: 'ปาก', level: 1 },
  { en: 'NOSE', trans: 'ja-muuk', thai: 'จมูก', level: 1 },
  { en: 'STOMACH', trans: 'torng', thai: 'ท้อง', level: 1 },
  { en: 'BACK (body)', trans: 'lang', thai: 'หลัง', level: 1 },
  { en: 'FINGER', trans: 'nio', thai: 'นิ้ว', level: 1 },
  { en: 'SHOULDER', trans: 'lai', thai: 'ไหล่', level: 1 },
  { en: 'KNEE', trans: 'kao', thai: 'เข่า', level: 1 },
  { en: 'INJURE', trans: 'jep', thai: 'เจ็บ', level: 1 },
  { en: 'BREAK/BROKEN', trans: 'hak', thai: 'หัก', level: 1 },
  { en: 'FEVER', trans: 'kai', thai: 'ไข้', level: 1 },
  { en: 'COUGH', trans: 'ai', thai: 'ไอ', level: 1 },
  { en: 'SYMPTOMS', trans: 'aa-gaan', thai: 'อาการ', level: 1 },

  // -- Еда и напитки --
  { en: 'RICE', trans: 'kaao', thai: 'ข้าว', level: 1 },
  { en: 'VEGETABLES', trans: 'pak', thai: 'ผัก', level: 1 },
  { en: 'FRUITS', trans: 'pon-la-mai', thai: 'ผลไม้', level: 1 },
  { en: 'PINEAPPLE', trans: 'sap-bpa-rot', thai: 'สับปะรด', level: 1 },
  { en: 'ORANGE (FRUIT)', trans: 'som', thai: 'ส้ม', level: 1 },
  { en: 'MANGO', trans: 'ma-muuang', thai: 'มะม่วง', level: 1 },
  { en: 'BANANA', trans: 'gluai', thai: 'กล้วย', level: 1 },
  { en: 'COCONUT', trans: 'ma-praao', thai: 'มะพร้าว', level: 1 },
  { en: 'DESSERT OR SNACK', trans: 'kanom', thai: 'ขนม', level: 1 },
  { en: 'WATER', trans: 'nam', thai: 'น้ำ', level: 1 },
  { en: 'MILK', trans: 'nom', thai: 'นม', level: 1 },
  { en: 'DEEP FRIED', trans: 'tort', thai: 'ทอด', level: 1 },
  { en: 'BOILED', trans: 'dtom', thai: 'ต้ม', level: 1 },
  { en: 'GRILLED', trans: 'yaang', thai: 'ย่าง', level: 1 },
  { en: 'STIR FRIED', trans: 'pat', thai: 'ผัด', level: 1 },
  { en: 'CHICKEN', trans: 'gai', thai: 'ไก่', level: 1 },
  { en: 'EGG', trans: 'kai', thai: 'ไข่', level: 1 },
  { en: 'COFFEE', trans: 'gaa-fae', thai: 'กาแฟ', level: 1 },
  { en: 'TEA', trans: 'chaa', thai: 'ชา', level: 1 },
  { en: 'BEER', trans: 'bia', thai: 'เบียร์', level: 1 },
  { en: 'PORK', trans: 'muu', thai: 'หมู', level: 1 },
  { en: 'BEEF / MEAT', trans: 'neua', thai: 'เนื้อ', level: 1 },
  { en: 'SHRIMP', trans: 'gung', thai: 'กุ้ง', level: 1 },
  { en: 'NOODLES', trans: 'guai-dtiao', thai: 'ก๋วยเตี๋ยว', level: 1 },
  { en: 'SOAP', trans: 'sabuu', thai: 'สบู่', level: 1 },

  // -- Животные --
  { en: 'FISH', trans: 'bplaa', thai: 'ปลา', level: 1 },
  { en: 'TURTLE', trans: 'dtao', thai: 'เต่า', level: 1 },
  { en: 'MONKEY', trans: 'ling', thai: 'ลิง', level: 1 },
  { en: 'GIRAFFE', trans: 'yii-raap', thai: 'ยีราฟ', level: 1 },
  { en: 'TIGER', trans: 'seua', thai: 'เสือ', level: 1 },
  { en: 'ELEPHANT', trans: 'chaang', thai: 'ช้าง', level: 1 },
  { en: 'BUTTERFLY', trans: 'pii-seua', thai: 'ผีเสื้อ', level: 1 },
  { en: 'SNAKE', trans: 'nguu', thai: 'งู', level: 1 },
  { en: 'CROCODILE', trans: 'jo-ra-kee', thai: 'จระเข้', level: 1 },
  { en: 'BUFFALO', trans: 'kwaai', thai: 'ควาย', level: 1 },
  { en: 'DOG', trans: 'maa', thai: 'หมา', level: 1 },
  { en: 'CAT', trans: 'maeo', thai: 'แมว', level: 1 },
  { en: 'MOSQUITO', trans: 'yung', thai: 'ยุง', level: 1 },

  // -- Места --
  { en: 'HOUSE/HOME', trans: 'baan', thai: 'บ้าน', level: 1 },
  { en: 'TEMPLE', trans: 'wat', thai: 'วัด', level: 1 },
  { en: 'MARKET', trans: 'dtalaat', thai: 'ตลาด', level: 1 },
  { en: 'STATION', trans: 'sa-taa-nii', thai: 'สถานี', level: 1 },
  { en: 'BEACH', trans: 'chaai haat', thai: 'ชายหาด', level: 1 },
  { en: 'SCHOOL', trans: 'rohng-rian', thai: 'โรงเรียน', level: 1 },
  { en: 'HOSPITAL', trans: 'rohng-pa-yaa-baan', thai: 'โรงพยาบาล', level: 1 },
  { en: 'AIRPORT', trans: 'sa-naam-bin', thai: 'สนามบิน', level: 1 },
  { en: 'GARDEN (PLACE)', trans: 'suuan', thai: 'สวน', level: 1 },
  { en: 'BANK', trans: 'ta-naa-kaan', thai: 'ธนาคาร', level: 1 },
  { en: 'ROAD/STREET', trans: 'ta-non', thai: 'ถนน', level: 1 },
  { en: 'SUB STREET', trans: 'soi', thai: 'ซอย', level: 1 },
  { en: 'COUNTRY', trans: 'bpra-tet (meuang)', thai: 'ประเทศ', level: 1 },
  { en: 'LANGUAGE', trans: 'paa-saa', thai: 'ภาษา', level: 1 },
  { en: 'ROOM', trans: 'horng', thai: 'ห้อง', level: 1 },

  // -- Вещи --
  { en: 'NOTEBOOK', trans: 'sa-mut', thai: 'สมุด', level: 1 },
  { en: 'PENCIL', trans: 'din-sor', thai: 'ดินสอ', level: 1 },
  { en: 'BOOK', trans: 'nang-seuu', thai: 'หนังสือ', level: 1 },
  { en: 'PAPER', trans: 'gra-daat', thai: 'กระดาษ', level: 1 },
  { en: 'SCISSORS', trans: 'gan-grai', thai: 'กรรไกร', level: 1 },
  { en: 'GLUE', trans: 'gaao', thai: 'กาว', level: 1 },
  { en: 'RULER', trans: 'mai-ban-tat', thai: 'ไม้บรรทัด', level: 1 },
  { en: 'ERASER', trans: 'yaang-lop', thai: 'ยางลบ', level: 1 },
  { en: 'TABLE', trans: 'dtoh', thai: 'โต๊ะ', level: 1 },
  { en: 'CHAIR', trans: 'gao-ii', thai: 'เก้าอี้', level: 1 },
  { en: 'DOOR', trans: 'bpra-dtuu', thai: 'ประตู', level: 1 },
  { en: 'MIRROR', trans: 'gra-jok', thai: 'กระจก', level: 1 },
  { en: 'SHELF', trans: 'chan-waang', thai: 'ชั้นวาง', level: 1 },
  { en: 'CLOCK/WATCH', trans: 'naa-li-gaa', thai: 'นาฬิกา', level: 1 },
  { en: 'UMBRELLA', trans: 'rom', thai: 'ร่ม', level: 1 },
  { en: 'HAT', trans: 'muuak', thai: 'หมวก', level: 1 },
  { en: 'SHOES', trans: 'rorng-tao', thai: 'รองเท้า', level: 1 },
  { en: 'SHIRT', trans: 'seua', thai: 'เสื้อ', level: 1 },
  { en: 'SKIRT', trans: 'gra-bprohng', thai: 'กระโปรง', level: 1 },
  { en: 'SHORTS', trans: 'gaang geeng', thai: 'กางเกง', level: 1 },
  { en: 'TOWEL', trans: 'paa-chet-dtuua', thai: 'ผ้าเช็ดตัว', level: 1 },
  { en: 'TOY', trans: 'korng leen', thai: 'ของเล่น', level: 1 },
  { en: 'ACCESSORIES', trans: 'soi', thai: 'สร้อย', level: 1 },
  { en: 'BOTTLE', trans: 'kuuat', thai: 'ขวด', level: 1 },
  { en: 'PLATE', trans: 'jaan', thai: 'จาน', level: 1 },
  { en: 'TATOO', trans: 'roi-sak', thai: 'รอยสัก', level: 1 },
  { en: 'MEDICATION', trans: 'yaa', thai: 'ยา', level: 1 },
  { en: 'BELL', trans: 'ra-kang', thai: 'ระฆัง', level: 1 },
  { en: 'SMALL CYMBAL', trans: 'ching', thai: 'ฉิ่ง', level: 1 },

  // -- Классификаторы --
  { en: 'PEOPLE (classifier)', trans: 'kon', thai: 'คน', level: 1 },
  { en: 'ANIMALS (CLASSIFIER)', trans: 'dtuua', thai: 'ตัว', level: 1 },
  { en: 'FRUITS (classifier)', trans: 'luuk', thai: 'ลูก', level: 1 },
  { en: 'BOOKS (classifier)', trans: 'leem', thai: 'เล่ม', level: 1 },
  { en: 'SMALL OBJECTS (classifier)', trans: 'an', thai: 'อัน', level: 1 },
  { en: 'CLASSIFIER FOR VEHICLES', trans: 'kan', thai: 'คัน', level: 1 },
  { en: 'CLASSIFIER FOR STREETS', trans: 'seen', thai: 'เส้น', level: 1 },
  { en: 'CLASSIFIER FOR PLACE, LOCATION', trans: 'haeng', thai: 'แห่ง', level: 1 },

  // -- Время (слова) --
  { en: 'DAY/DAYS', trans: 'wan', thai: 'วัน', level: 1 },
  { en: 'MONTH', trans: 'deuan', thai: 'เดือน', level: 1 },
  { en: 'YEAR', trans: 'bpii', thai: 'ปี', level: 1 },
  { en: 'WEEK', trans: 'aa-tit', thai: 'อาทิตย์', level: 1 },
  { en: 'HOUR', trans: 'chuua-mohng', thai: 'ชั่วโมง', level: 1 },
  { en: 'MINUTE', trans: 'naa-tii', thai: 'นาที', level: 1 },
  { en: 'TIME', trans: 'wee-laa', thai: 'เวลา', level: 1 },
  { en: 'TODAY', trans: 'wan nii', thai: 'วันนี้', level: 1 },
  { en: 'YESTERDAY', trans: 'meua waan', thai: 'เมื่อวาน', level: 1 },
  { en: 'TOMORROW', trans: 'prung nii', thai: 'พรุ่งนี้', level: 1 },
  { en: 'NOW', trans: 'dtorn nii', thai: 'ตอนนี้', level: 1 },
  { en: 'A MOMENT AGO', trans: 'meua gii', thai: 'เมื่อกี้', level: 1 },
  { en: 'NOON', trans: 'tiang', thai: 'เที่ยง', level: 1 },
  { en: 'NIGHT', trans: 'kam', thai: 'ค่ำ', level: 1 },
  { en: 'SEASON', trans: 'reuduu', thai: 'ฤดู', level: 1 },
  { en: 'BIRTHDAY', trans: 'wan-gert', thai: 'วันเกิด', level: 1 },
  { en: 'FROM (TIME)', trans: 'dtang-dtae', thai: 'ตั้งแต่', level: 1 },
  { en: 'TO (TIME)', trans: 'teung', thai: 'ถึง', level: 1 },
  { en: 'DAYOFF', trans: 'wan-yut', thai: 'วันหยุด', level: 1 },

  // -- Деньги --
  { en: 'MONEY', trans: 'ngern', thai: 'เงิน', level: 1 },
  { en: 'BAHT', trans: 'baat', thai: 'บาท', level: 1 },
  { en: 'PRICE', trans: 'raa-kaa', thai: 'ราคา', level: 1 },

  // ═══ УРОВЕНЬ 2 — СЛОВОСОЧЕТАНИЯ ═══

  // -- Цвета --
  { en: 'RED', trans: 'sii daeng', thai: 'สีแดง', level: 2 },
  { en: 'PURPLE', trans: 'sii muuang', thai: 'สีม่วง', level: 2 },
  { en: 'DARK BLUE', trans: 'sii nam ngern', thai: 'สีน้ำเงิน', level: 2 },
  { en: 'GREEN', trans: 'sii kiao', thai: 'สีเขียว', level: 2 },
  { en: 'LIGHT BLUE', trans: 'sii faa', thai: 'สีฟ้า', level: 2 },
  { en: 'PINK', trans: 'sii chompuu', thai: 'สีชมพู', level: 2 },
  { en: 'ORANGE', trans: 'sii som', thai: 'สีส้ม', level: 2 },
  { en: 'YELLOW', trans: 'sii leuang', thai: 'สีเหลือง', level: 2 },
  { en: 'BROWN', trans: 'sii nam-dtaan', thai: 'สีน้ำตาล', level: 2 },
  { en: 'WHITE', trans: 'sii kaao', thai: 'สีขาว', level: 2 },
  { en: 'GREY', trans: 'sii tao', thai: 'สีเทา', level: 2 },
  { en: 'BLACK', trans: 'sii dam', thai: 'สีดำ', level: 2 },

  // -- Числа 11–100 --
  { en: 'ELEVEN', trans: 'sip et', thai: 'สิบเอ็ด', level: 2 },
  { en: 'TWELVE', trans: 'sip sorng', thai: 'สิบสอง', level: 2 },
  { en: 'THIRTEEN', trans: 'sip saam', thai: 'สิบสาม', level: 2 },
  { en: 'FOURTEEN', trans: 'sip sii', thai: 'สิบสี่', level: 2 },
  { en: 'FIFTEEN', trans: 'sip haa', thai: 'สิบห้า', level: 2 },
  { en: 'SIXTEEN', trans: 'sip hok', thai: 'สิบหก', level: 2 },
  { en: 'SEVENTEEN', trans: 'sip jet', thai: 'สิบเจ็ด', level: 2 },
  { en: 'EIGHTEEN', trans: 'sip bpaet', thai: 'สิบแปด', level: 2 },
  { en: 'NINETEEN', trans: 'sip gao', thai: 'สิบเก้า', level: 2 },
  { en: 'TWENTY', trans: 'yii sip', thai: 'ยี่สิบ', level: 2 },
  { en: 'TWENTY ONE', trans: 'yii sip et', thai: 'ยี่สิบเอ็ด', level: 2 },
  { en: 'TWENTY TWO', trans: 'yii sip sorng', thai: 'ยี่สิบสอง', level: 2 },
  { en: 'TWENTY THREE', trans: 'yii sip saam', thai: 'ยี่สิบสาม', level: 2 },
  { en: 'TWENTY FOUR', trans: 'yii sip sii', thai: 'ยี่สิบสี่', level: 2 },
  { en: 'TWENTY FIVE', trans: 'yii sip haa', thai: 'ยี่สิบห้า', level: 2 },
  { en: 'TWENTY SIX', trans: 'yii sip hok', thai: 'ยี่สิบหก', level: 2 },
  { en: 'TWENTY SEVEN', trans: 'yii sip jet', thai: 'ยี่สิบเจ็ด', level: 2 },
  { en: 'TWENTY EIGHT', trans: 'yii sip bpaet', thai: 'ยี่สิบแปด', level: 2 },
  { en: 'TWENTY NINE', trans: 'yii sip gao', thai: 'ยี่สิบเก้า', level: 2 },
  { en: 'THIRTY', trans: 'saam sip', thai: 'สามสิบ', level: 2 },
  { en: 'FORTY', trans: 'sii sip', thai: 'สี่สิบ', level: 2 },
  { en: 'FIFTY', trans: 'haa sip', thai: 'ห้าสิบ', level: 2 },
  { en: 'SIXTY', trans: 'hok sip', thai: 'หกสิบ', level: 2 },
  { en: 'SEVENTY', trans: 'jet sip', thai: 'เจ็ดสิบ', level: 2 },
  { en: 'SEVENTY ONE', trans: 'jet sip et', thai: 'เจ็ดสิบเอ็ด', level: 2 },
  { en: 'EIGHTY', trans: 'bpaet sip', thai: 'แปดสิบ', level: 2 },
  { en: 'EIGHTY ONE', trans: 'bpaet sip et', thai: 'แปดสิบเอ็ด', level: 2 },
  { en: 'NINETY', trans: 'gao sip', thai: 'เก้าสิบ', level: 2 },
  { en: 'NINETY ONE', trans: 'gao sip et', thai: 'เก้าสิบเอ็ด', level: 2 },

  // -- Дни недели --
  { en: 'MONDAY', trans: 'wan jan', thai: 'วันจันทร์', level: 2 },
  { en: 'TUESDAY', trans: 'wan ang-kaan', thai: 'วันอังคาร', level: 2 },
  { en: 'WEDNESDAY', trans: 'wan put', thai: 'วันพุธ', level: 2 },
  { en: 'THURSDAY', trans: 'wan pareuhat', thai: 'วันพฤหัส', level: 2 },
  { en: 'FRIDAY', trans: 'wan suk', thai: 'วันศุกร์', level: 2 },
  { en: 'SATURDAY', trans: 'wan sao', thai: 'วันเสาร์', level: 2 },
  { en: 'SUNDAY', trans: 'wan aa-tit', thai: 'วันอาทิตย์', level: 2 },
  { en: 'WEEKEND', trans: 'sao-aa-tit', thai: 'เสาร์อาทิตย์', level: 2 },

  // -- Месяцы --
  { en: 'JANUARY', trans: 'ma-ga-raa-kom', thai: 'มกราคม', level: 2 },
  { en: 'FEBRUARY', trans: 'gum-paa-pan', thai: 'กุมภาพันธ์', level: 2 },
  { en: 'MARCH', trans: 'mii-naa-kom', thai: 'มีนาคม', level: 2 },
  { en: 'APRIL', trans: 'mee-saa-yon', thai: 'เมษายน', level: 2 },
  { en: 'MAY', trans: 'preut-sa-paa-kom', thai: 'พฤษภาคม', level: 2 },
  { en: 'JUNE', trans: 'mi-tu-naa-yon', thai: 'มิถุนายน', level: 2 },
  { en: 'JULY', trans: 'ga-ra-ga-daa-kom', thai: 'กรกฎาคม', level: 2 },
  { en: 'AUGUST', trans: 'sing-haa-kom', thai: 'สิงหาคม', level: 2 },
  { en: 'SEPTEMBER', trans: 'gan-yaa-yon', thai: 'กันยายน', level: 2 },
  { en: 'OCTOBER', trans: 'dtu-laa-kom', thai: 'ตุลาคม', level: 2 },
  { en: 'NOVEMBER', trans: 'preut-sa-ji-gaa-yon', thai: 'พฤศจิกายน', level: 2 },
  { en: 'DECEMBER', trans: 'tan-waa-kom', thai: 'ธันวาคม', level: 2 },

  // -- Сезоны и погода --
  { en: 'WINTER', trans: 'reuduu naao', thai: 'ฤดูหนาว', level: 2 },
  { en: 'SPRING', trans: 'reuduu bai-mai-pli', thai: 'ฤดูใบไม้ผลิ', level: 2 },
  { en: 'SUMMER', trans: 'reuduu rorn', thai: 'ฤดูร้อน', level: 2 },
  { en: 'AUTUMN', trans: 'reuduu bai-mai-ruuang', thai: 'ฤดูใบไม้ร่วง', level: 2 },
  { en: 'WEATHER CONDITION', trans: 'sa-paap aa-gaat', thai: 'สภาพอากาศ', level: 2 },

  // -- Время (фразы) --
  { en: 'MORNING', trans: 'dtorn chao', thai: 'ตอนเช้า', level: 2 },
  { en: 'EVENING', trans: 'dtorn yen', thai: 'ตอนเย็น', level: 2 },
  { en: 'MIDNIGHT', trans: 'tiang keuun', thai: 'เที่ยงคืน', level: 2 },
  { en: '1AM', trans: 'dtii neung', thai: 'ตีหนึ่ง', level: 2 },
  { en: '2AM', trans: 'dtii sorng', thai: 'ตีสอง', level: 2 },
  { en: '3AM', trans: 'dtii saam', thai: 'ตีสาม', level: 2 },
  { en: '4AM', trans: 'dtii sii', thai: 'ตีสี่', level: 2 },
  { en: '5AM', trans: 'dtii haa', thai: 'ตีห้า', level: 2 },
  { en: '6AM', trans: 'hok mohng chao', thai: 'หกโมงเช้า', level: 2 },
  { en: '7AM', trans: 'jet mohng chao', thai: 'เจ็ดโมงเช้า', level: 2 },
  { en: '8AM', trans: 'bpaet mohng chao', thai: 'แปดโมงเช้า', level: 2 },
  { en: '9AM', trans: 'gao mohng chao', thai: 'เก้าโมงเช้า', level: 2 },
  { en: '10AM', trans: 'sip mohng chao', thai: 'สิบโมงเช้า', level: 2 },
  { en: '11AM', trans: 'sip et mohng chao', thai: 'สิบเอ็ดโมงเช้า', level: 2 },
  { en: '1PM', trans: 'baai neung', thai: 'บ่ายหนึ่ง', level: 2 },
  { en: '2PM', trans: 'baai sorng', thai: 'บ่ายสอง', level: 2 },
  { en: '3PM', trans: 'baai saam', thai: 'บ่ายสาม', level: 2 },
  { en: '4PM', trans: 'baai sii', thai: 'บ่ายสี่', level: 2 },
  { en: '5PM', trans: 'haa mohng yen', thai: 'ห้าโมงเย็น', level: 2 },
  { en: '6PM', trans: 'hok mohng yen', thai: 'หกโมงเย็น', level: 2 },
  { en: '7PM', trans: 'neung tum', thai: 'หนึ่งทุ่ม', level: 2 },
  { en: '8PM', trans: 'sorng tum', thai: 'สองทุ่ม', level: 2 },
  { en: '9PM', trans: 'saam tum', thai: 'สามทุ่ม', level: 2 },
  { en: '10PM', trans: 'sii tum', thai: 'สี่ทุ่ม', level: 2 },
  { en: '11PM', trans: 'haa tum', thai: 'ห้าทุ่ม', level: 2 },
  { en: 'NEW YEAR', trans: 'bpii mai', thai: 'ปีใหม่', level: 2 },
  { en: 'PAST MONTH', trans: 'deuan tii-laeo', thai: 'เดือนที่แล้ว', level: 2 },
  { en: 'THIS MONTH', trans: 'deuan nii', thai: 'เดือนนี้', level: 2 },
  { en: 'NEXT MONTH', trans: 'deuan naa', thai: 'เดือนหน้า', level: 2 },
  { en: '15:00 (24h)', trans: 'sip haa naaligaa', thai: 'สิบห้านาฬิกา', level: 2 },
  { en: '1ST', trans: 'wan tii neung', thai: 'วันที่หนึ่ง', level: 2 },

  // -- Семья (составные) --
  { en: 'YOUNGER SISTER', trans: 'norng saao', thai: 'น้องสาว', level: 2 },
  { en: 'OLDER BROTHER', trans: 'pii chaai', thai: 'พี่ชาย', level: 2 },
  { en: 'OLDER SISTER', trans: 'pii saao', thai: 'พี่สาว', level: 2 },
  { en: 'YOUNGER BROTHER', trans: 'norng chaai', thai: 'น้องชาย', level: 2 },
  { en: 'BABY (MALE)', trans: 'luuk chaai', thai: 'ลูกชาย', level: 2 },
  { en: 'BABY (FEMALE)', trans: 'luuk saao', thai: 'ลูกสาว', level: 2 },

  // -- Комнаты --
  { en: 'BATHROOM', trans: 'horng nam', thai: 'ห้องน้ำ', level: 2 },
  { en: 'BEDROOM', trans: 'horng norn', thai: 'ห้องนอน', level: 2 },
  { en: 'KITCHEN', trans: 'horng kruua', thai: 'ห้องครัว', level: 2 },
  { en: 'LIVING ROOM', trans: 'horng nang leen', thai: 'ห้องนั่งเล่น', level: 2 },
  { en: 'CLASSROOM', trans: 'horng rian', thai: 'ห้องเรียน', level: 2 },
  { en: 'GLASS-DOOR CABINET', trans: 'dtuu gra-jok', thai: 'ตู้กระจก', level: 2 },

  // -- Ежедневные дела --
  { en: 'TO TAKE A BATH/SHOWER', trans: 'aap nam', thai: 'อาบน้ำ', level: 2 },
  { en: 'TO WASH YOUR HAIR', trans: 'sa pom', thai: 'สระผม', level: 2 },
  { en: 'TO WASH YOUR HANDS', trans: 'laang meuu', thai: 'ล้างมือ', level: 2 },
  { en: 'TO BRUSH YOUR TEETH', trans: 'bpraeng fan', thai: 'แปรงฟัน', level: 2 },
  { en: 'TO GET DRESSED', trans: 'dtaeng dtuua', thai: 'แต่งตัว', level: 2 },
  { en: 'COOK FOOD', trans: 'tam aahaan', thai: 'ทำอาหาร', level: 2 },
  { en: 'HOMEWORK', trans: 'ngaan baan', thai: 'งานบ้าน', level: 2 },
  { en: 'TAKE A PHOTO', trans: 'taai-ruup', thai: 'ถ่ายรูป', level: 2 },
  { en: 'PLAY MUSIC', trans: 'don-dtrii', thai: 'ดนตรี', level: 2 },
  { en: 'THAI MASSAGE', trans: 'nuuat tai', thai: 'นวดไทย', level: 2 },
  { en: 'LUNCH', trans: 'aahaan tiang', thai: 'อาหารเที่ยง', level: 2 },
  { en: 'BREAKFAST', trans: 'aahaan chao', thai: 'อาหารเช้า', level: 2 },
  { en: 'DINNER', trans: 'kaao yen', thai: 'ข้าวเย็น', level: 2 },
  { en: 'FRIED RICE', trans: 'kaao pat', thai: 'ข้าวผัด', level: 2 },
  { en: 'ORANGE JUICE', trans: 'nam som', thai: 'น้ำส้ม', level: 2 },
  { en: 'VISIT DOCTOR', trans: 'haa mor', thai: 'หาหมอ', level: 2 },
  { en: 'TO TAKE MEDICATION', trans: 'gin yaa', thai: 'กินยา', level: 2 },
  { en: 'TO BE ABSENT (FOR THE SCHOOL)', trans: 'kaat rian', thai: 'ขาดเรียน', level: 2 },
  { en: 'TO BE ABSENT (FOR THE WORK)', trans: 'kaat ngaan', thai: 'ขาดงาน', level: 2 },

  // -- Транспорт --
  { en: 'CAR', trans: 'rot yon', thai: 'รถยนต์', level: 2 },
  { en: 'ELECTRIC TRAIN', trans: 'rot fai-faa', thai: 'รถไฟฟ้า', level: 2 },
  { en: 'BOAT', trans: 'reua', thai: 'เรือ', level: 2 },
  { en: 'AIRPLANE', trans: 'kreuang bin', thai: 'เครื่องบิน', level: 2 },
  { en: 'BUS', trans: 'rot mee', thai: 'รถเมล์', level: 2 },
  { en: 'BICYCLE', trans: 'jak-gra-yaan', thai: 'จักรยาน', level: 2 },

  // -- Навигация --
  { en: 'HERE', trans: 'tii nii', thai: 'ที่นี่', level: 2 },
  { en: 'LEFT SIDE', trans: 'taang-saai', thai: 'ทางซ้าย', level: 2 },
  { en: 'RIGHT SIDE', trans: 'taang-kwaa', thai: 'ทางขวา', level: 2 },
  { en: 'STRAIGHT', trans: 'dtorng bpai', thai: 'ตรงไป', level: 2 },
  { en: 'ROUNDABOUT', trans: 'wong-wian', thai: 'วงเวียน', level: 2 },
  { en: '4 INTERSECTION', trans: 'sii yaek', thai: 'สี่แยก', level: 2 },
  { en: 'TRAFFIC LIGHT', trans: 'sanyaan-fai', thai: 'สัญญาณไฟ', level: 2 },
  { en: 'ENTRANCE', trans: 'taang kao', thai: 'ทางเข้า', level: 2 },
  { en: 'GO WALKING', trans: 'dern bpai', thai: 'เดินไป', level: 2 },
  { en: 'TO TURN LEFT', trans: 'liao saai', thai: 'เลี้ยวซ้าย', level: 2 },
  { en: 'TO TURN RIGHT', trans: 'liao kwaa', thai: 'เลี้ยวขวา', level: 2 },
  { en: 'TO REVERSE', trans: 'toi lang', thai: 'ถอยหลัง', level: 2 },
  { en: 'U TURN', trans: 'glap rot', thai: 'กลับรถ', level: 2 },
  { en: 'BUS STOP', trans: 'bpaai rot mee', thai: 'ป้ายรถเมล์', level: 2 },

  // -- Покупки --
  { en: 'CASH', trans: 'ngern-sot', thai: 'เงินสด', level: 2 },
  { en: 'CHANGE (money)', trans: 'ngern-torn', thai: 'เงินทอน', level: 2 },
  { en: 'RECEIPT', trans: 'bai-set', thai: 'ใบเสร็จ', level: 2 },

  // -- Одежда --
  { en: 'CLOTHES', trans: 'chut / seua-paa', thai: 'ชุด / เสื้อผ้า', level: 2 },
  { en: 'SUNGLASSES', trans: 'waen-gan-daet', thai: 'แว่นกันแดด', level: 2 },
  { en: 'SUNCREAM', trans: 'kriim-gan-daet', thai: 'ครีมกันแดด', level: 2 },
  { en: 'RAINCOAT', trans: 'seua-gan-fon', thai: 'เสื้อกันฝน', level: 2 },
  { en: 'SWEATER', trans: 'seua-gan-naao', thai: 'เสื้อกันหนาว', level: 2 },
  { en: 'GLOVES', trans: 'tung-meuu', thai: 'ถุงมือ', level: 2 },
  { en: 'COAT', trans: 'seua koht', thai: 'เสื้อโค้ต', level: 2 },

  // -- Медицина (фразы) --
  { en: 'HEADACHE', trans: 'bpuuat huua', thai: 'ปวดหัว', level: 2 },
  { en: 'PHARMACY', trans: 'raan yaa', thai: 'ร้านยา', level: 2 },
  { en: 'RESTAURANT', trans: 'raan aahaan', thai: 'ร้านอาหาร', level: 2 },
  { en: 'CINEMA', trans: 'rohng-nang', thai: 'โรงหนัง', level: 2 },
  { en: 'HOTEL', trans: 'rohng-raem', thai: 'โรงแรม', level: 2 },
  { en: 'ICE CREAM SHOP', trans: 'raan ai sa griim', thai: 'ร้านไอศกรีม', level: 2 },
  { en: 'AQUARIUM', trans: 'pi-pit-ta-pan sat-naam', thai: 'พิพิธภัณฑ์สัตว์น้ำ', level: 2 },
  { en: 'WIFI PASSWORD', trans: 'rahat wai fai', thai: 'รหัสไวไฟ', level: 2 },
  { en: 'NEXT TO/BESIDE', trans: 'kaang kaang', thai: 'ข้างข้าง', level: 2 },
  { en: 'BETWEEN', trans: 'ra-waang', thai: 'ระหว่าง', level: 2 },
  { en: 'YOU ARE WELCOME', trans: 'mai bpen rai', thai: 'ไม่เป็นไร', level: 2 },
  { en: 'NO / INCORRECT', trans: 'mai chai', thai: 'ไม่ใช่', level: 2 },
  { en: 'TOM YUM', trans: 'dtom-yam', thai: 'ต้มยำ', level: 2 },
  { en: 'PAPAYA SALAD', trans: 'som-dtam', thai: 'ส้มตำ', level: 2 },
  { en: 'MAYBE', trans: 'aat-ja', thai: 'อาจจะ', level: 2 },
  { en: 'SURE / DEFINITELY', trans: 'nae-norn', thai: 'แน่นอน', level: 2 },
  { en: 'MY BIRTHDAY', trans: 'wan-gert korng pom', thai: 'วันเกิดของผม', level: 2 },
  { en: 'TO COME BACK', trans: 'glap maa', thai: 'กลับมา', level: 2 },
  { en: 'DON\'T UNDERSTAND', trans: 'mai kao-jai', thai: 'ไม่เข้าใจ', level: 2 },
  { en: 'EVERYONE', trans: 'tuk kon', thai: 'ทุกคน', level: 2 },
  { en: 'FORBIDDEN TO TOUCH', trans: 'haam jap', thai: 'ห้ามจับ', level: 2 },
  { en: 'FORBIDDEN TO ENTER', trans: 'haam kao', thai: 'ห้ามเข้า', level: 2 },
  { en: 'FORBIDDEN FOR PARKING', trans: 'haam jort', thai: 'ห้ามจอด', level: 2 },
  { en: 'FORBIDDEN TO SMOKE', trans: 'haam suup burii', thai: 'ห้ามสูบบุหรี่', level: 2 },
  { en: 'HELP EMERGENCY', trans: 'chuai duai', thai: 'ช่วยด้วย', level: 2 },
  { en: 'STOP HERE', trans: 'jort tii nii', thai: 'จอดที่นี่', level: 2 },
  { en: 'STOP BEFORE...', trans: 'jort gorn', thai: 'จอดก่อน', level: 2 },
  { en: 'COCONUT TREE', trans: 'dton ma-praao', thai: 'ต้นมะพร้าว', level: 2 },
  { en: 'SHARK', trans: 'bplaa cha-laam', thai: 'ปลาฉลาม', level: 2 },

  // ═══ УРОВЕНЬ 3 — ПРЕДЛОЖЕНИЯ ═══
  // (short to long)

  { en: 'I AM LATE', trans: 'pom saai', thai: 'ผมสาย', level: 3 },
  { en: 'I AM PLAYING', trans: 'pom gamlang leen', thai: 'ผมกำลังเล่น', level: 3 },
  { en: 'SHE SLEEPS', trans: 'ter norn lap', thai: 'เธอนอนหลับ', level: 3 },
  { en: 'I HAVE A CAT', trans: 'pom mii maeo', thai: 'ผมมีแมว', level: 3 },
  { en: 'I DONT KNOW', trans: 'pom mai ruu', thai: 'ผมไม่รู้', level: 3 },
  { en: 'I\'M TIRED', trans: 'pom neuai', thai: 'ผมเหนื่อย', level: 3 },
  { en: 'I AM HUNGRY', trans: 'pom hio laeo', thai: 'ผมหิวแล้ว', level: 3 },
  { en: 'SHE IS SAD', trans: 'kao sia-jai', thai: 'เขาเสียใจ', level: 3 },
  { en: 'IT\'S VERY SPICY', trans: 'pet maak', thai: 'เผ็ดมาก', level: 3 },
  { en: 'TODAY IS FRIDAY', trans: 'wan nii wan suk', thai: 'วันนี้วันศุกร์', level: 3 },
  { en: 'TOMORROW IS SATURDAY', trans: 'prung nii wan sao', thai: 'พรุ่งนี้วันเสาร์', level: 3 },
  { en: 'HE HAS HEADACHE', trans: 'kao bpuuat huua', thai: 'เขาปวดหัว', level: 3 },
  { en: 'I AM THAI', trans: 'pom bpen kon tai', thai: 'ผมเป็นคนไทย', level: 3 },
  { en: 'BECAUSE I DON\'T FEEL WELL', trans: 'pror-waa mai sa-baai', thai: 'เพราะว่าไม่สบาย', level: 3 },
  { en: 'EVERYONE HAS A COUGH', trans: 'tuk kon ai', thai: 'ทุกคนไอ', level: 3 },
  { en: 'THEY DRINK MILK', trans: 'puuak kao deuum nom', thai: 'พวกเขาดื่มนม', level: 3 },
  { en: 'HE/THEY DRINK(S) MILK', trans: 'kao deuum nom', thai: 'เขาดื่มนม', level: 3 },
  { en: 'WE LIKE DESSERT', trans: 'rao chorp kanom', thai: 'เราชอบขนม', level: 3 },
  { en: 'SHE WASHES HER HAIR', trans: 'ter sa pom', thai: 'เธอสระผม', level: 3 },
  { en: 'I\'M FROM THAILAND', trans: 'pom maa jaak bpra-tet Tai', thai: 'ผมมาจากประเทศไทย', level: 3 },
  { en: 'THIS IS MY SHIRT', trans: 'nii seua korng pom', thai: 'นี่เสื้อของผม', level: 3 },
  { en: 'THIS IS MY MOTHER', trans: 'nii keuu kun mae', thai: 'นี่คือคุณแม่', level: 3 },
  { en: 'ARE YOU HAVING FUN?', trans: 'sanuk mai?', thai: 'สนุกไหม?', level: 3 },
  { en: 'WHAT IS THIS?', trans: 'nii keuu arai?', thai: 'นี่คืออะไร?', level: 3 },
  { en: 'WHAT IS THAT?', trans: 'nan keuu arai?', thai: 'นั่นคืออะไร?', level: 3 },
  { en: 'WHO IS THIS?', trans: 'nii keuu krai?', thai: 'นี่คือใคร?', level: 3 },
  { en: 'WHO IS THAT?', trans: 'nan keuu krai?', thai: 'นั่นคือใคร?', level: 3 },
  { en: 'WHAT ARE YOU DOING?', trans: 'kun tam arai?', thai: 'คุณทำอะไร?', level: 3 },
  { en: 'WHERE ARE YOU GOING?', trans: 'kun bpai tii nai?', thai: 'คุณไปที่ไหน?', level: 3 },
  { en: 'COME HERE', trans: 'maa nii', thai: 'มานี่', level: 3 },
  { en: 'LOOK AT THE CROCODILE', trans: 'duu jo-ra-kee', thai: 'ดูจระเข้', level: 3 },
  { en: 'IT IS TOO HOT', trans: 'man rorn gern bpai', thai: 'มันร้อนเกินไป', level: 3 },
  { en: 'IT IS TOO COLD', trans: 'man naao gern bpai', thai: 'มันหนาวเกินไป', level: 3 },
  { en: 'THERE IS A CAT IN THE HOUSE', trans: 'mii maeo nai baan', thai: 'มีแมวในบ้าน', level: 3 },
  { en: 'THERE IS SUNNY', trans: 'mii daet-ork', thai: 'มีแดดออก', level: 3 },
  { en: 'THERE IS WINDY', trans: 'mii lom-raeng', thai: 'มีลมแรง', level: 3 },
  { en: 'THERE IS RAINBOW', trans: 'mii saai-rung', thai: 'มีสายรุ้ง', level: 3 },
  { en: 'THERE IS STORMY', trans: 'mii paa-yu', thai: 'มีพายุ', level: 3 },
  { en: 'THERE IS RAINING', trans: 'mii fon-dtok', thai: 'มีฝนตก', level: 3 },
  { en: 'THERE IS MONSOON', trans: 'mii mor-ra-sum', thai: 'มีมรสุม', level: 3 },
  { en: 'THERE IS SNOWING', trans: 'mii hima-dtok', thai: 'มีหิมะตก', level: 3 },
  { en: 'THERE IS VERY CLOUDY', trans: 'mii mek maak', thai: 'มีเมฆมาก', level: 3 },
  { en: 'PLEASE HELP WASH THE PLATES', trans: 'chuai laang jaan', thai: 'ช่วยล้างจาน', level: 3 },
  { en: 'I SPEAK CHINESE', trans: 'pom puut paa-saa jiin', thai: 'ผมพูดภาษาจีน', level: 3 },
  { en: 'I\'M FRENCH', trans: 'pom bpen kon farangset', thai: 'ผมเป็นคนฝรั่งเศส', level: 3 },
  { en: 'SPEAK SLOWLY PLEASE', trans: 'puut chaa chaa noi', thai: 'พูดช้าช้าหน่อย', level: 3 },
  { en: 'EVERY DAY I DRINK COFFEE', trans: 'tuk wan pom deuum gaa-fae', thai: 'ทุกวันผมดื่มกาแฟ', level: 3 },
  { en: 'THERE IS ONE BOOK', trans: 'mii nang-seuu neung leem', thai: 'มีหนังสือหนึ่งเล่ม', level: 3 },
  { en: 'PLEASE DON\'T GO THERE', trans: 'yaa bpai tii nan', thai: 'อย่าไปที่นั่น', level: 3 },
  { en: 'COME SEE THE GIRAFFE', trans: 'maa duu yii-raap', thai: 'มาดูยีราฟ', level: 3 },
  { en: 'WHOOSE IS THIS SHIRT?', trans: 'nii seua korng krai?', thai: 'นี่เสื้อของใคร?', level: 3 },
  { en: 'WHAT DAY?', trans: 'wan arai?', thai: 'วันอะไร?', level: 3 },
  { en: 'WHICH DAY?', trans: 'wan nai?', thai: 'วันไหน?', level: 3 },
  { en: 'I PLAY FOOTBALL EVERY MONDAY', trans: 'pom leen fut-bon tuk wan jan', thai: 'ผมเล่นฟุตบอลทุกวันจันทร์', level: 3 },
  { en: 'SHE DOES HER HOMEWORK IN THE LIVING ROOM', trans: 'ter tam ngaan baan nai horng nang leen', thai: 'เธอทำงานบ้านในห้องนั่งเล่น', level: 3 },
  { en: 'THE GIRAFFE IS TALL', trans: 'yii-raap dtuua suung', thai: 'ยีราฟตัวสูง', level: 3 },
  { en: 'THE BUTTERFLY IS SMALL', trans: 'pii-seua dtuua lek', thai: 'ผีเสื้อตัวเล็ก', level: 3 },
  { en: 'THE ELEPHANT IS BIG', trans: 'chaang dtuua yai', thai: 'ช้างตัวใหญ่', level: 3 },
  { en: 'WHY ARE YOU SAD?', trans: 'kun sia-jai tam-mai?', thai: 'คุณเสียใจทำไม?', level: 3 },
  { en: 'WHY DO YOU CRY?', trans: 'kun rorng-hai tam-mai?', thai: 'คุณร้องไห้ทำไม?', level: 3 },
  { en: 'HOW IS THE WEATHER?', trans: 'aa-gaat bpen yaang-rai?', thai: 'อากาศเป็นอย่างไร?', level: 3 },
  { en: 'WHAT NATIONALITY YOU?', trans: 'kun bpen kohn arai?', thai: 'คุณเป็นคนอะไร?', level: 3 },
  { en: 'CAN YOU HELP ME?', trans: 'chuai pom dai-mai?', thai: 'ช่วยผมได้ไหม?', level: 3 },
  { en: 'I KNOW THAT HE IS HERE', trans: 'pom ruu waa kao yuu tii nan', thai: 'ผมรู้ว่าเขาอยู่ที่นั่น', level: 3 },
  { en: 'ARE YOU FEELING BETTER YES/OR NOT?', trans: 'kun haai-dii reuu-yang?', thai: 'คุณหายดีหรือยัง?', level: 3 },
  { en: 'FROM ONE O\'CLOCK', trans: 'dtang-dtae baai mohng', thai: 'ตั้งแต่บ่ายโมง', level: 3 },
  { en: 'FROM MONDAY TO FRIDAY', trans: 'dtang-dtae wan jan teung wan suk', thai: 'ตั้งแต่วันจันทร์ถึงวันศุกร์', level: 3 },
  { en: 'I BRUSH MY TEETH IN THE MORNING', trans: 'pom bpraeng fan nai dtorn chao', thai: 'ผมแปรงฟันในตอนเช้า', level: 3 },
  { en: 'I EAT SNACK IN THE AFTERNOON', trans: 'pom gin kanom nai dtorn baai', thai: 'ผมกินขนมในตอนบ่าย', level: 3 },
  { en: 'I TAKE SHOWER IN THE EVENING', trans: 'pom aap nam nai dtorn yen', thai: 'ผมอาบน้ำในตอนเย็น', level: 3 },
  { en: 'I WASH MY HANDS IN THE BATHROOM', trans: 'pom laang meuu nai horng nam', thai: 'ผมล้างมือในห้องน้ำ', level: 3 },
  { en: 'THEY SLEEP IN THE BEDROOM', trans: 'puuak kao norn lap nai horng norn', thai: 'พวกเขานอนหลับในห้องนอน', level: 3 },
  { en: 'I GO TO THE TEMPLE BY BOAT', trans: 'pom bpai tii wat doi reua', thai: 'ผมไปที่วัดโดยเรือ', level: 3 },
  { en: 'WE ARE AT TEMPLE', trans: 'rao yuu tii wat', thai: 'เราอยู่ที่วัด', level: 3 },
  { en: 'WE WALK BACK HOME', trans: 'rao dern glap baan', thai: 'เราเดินกลับบ้าน', level: 3 },
  { en: 'SHE WEARS PYJAMAS', trans: 'kao sai chut-norn', thai: 'เขาใส่ชุดนอน', level: 3 },
  { en: 'ONE COCONUT', trans: 'ma-praao neung luuk', thai: 'มะพร้าวหนึ่งลูก', level: 3 },
  { en: 'FOUR COCONUTS', trans: 'ma-praao sii luuk', thai: 'มะพร้าวสี่ลูก', level: 3 },
  { en: 'EIGHT COCONUTS', trans: 'ma-praao bpaet luuk', thai: 'มะพร้าวแปดลูก', level: 3 },
  { en: 'SEVEN MONKEYS', trans: 'ling jet dtuua', thai: 'ลิงเจ็ดตัว', level: 3 },
  { en: 'TEN MONKEYS', trans: 'ling sip dtuua', thai: 'ลิงสิบตัว', level: 3 },
  { en: 'A MONKEY ON A COCONUT TREE', trans: 'ling bon dton ma-praao', thai: 'ลิงบนต้นมะพร้าว', level: 3 },
  { en: 'BROWN FISH', trans: 'bplaa sii nam-dtaan', thai: 'ปลาสีน้ำตาล', level: 3 },
  { en: 'GREEN TURTLE', trans: 'dtao sii kiao', thai: 'เต่าสีเขียว', level: 3 },
  { en: 'THE GREEN TURTLE', trans: 'dtao sii kiao', thai: 'เต่าสีเขียว', level: 3 },
  { en: 'THE GREY SHARK', trans: 'bplaa cha-laam sii tao', thai: 'ปลาฉลามสีเทา', level: 3 },
  { en: 'THE ORANGE AND WHITE FISH', trans: 'bplaa sii som gap sii kaao', thai: 'ปลาสีส้มกับสีขาว', level: 3 },
  { en: 'I LIKE TURTLES', trans: 'pom chorp dtao', thai: 'ผมชอบเต่า', level: 3 },
  { en: 'I LIKE RED', trans: 'pom chorp sii daeng', thai: 'ผมชอบสีแดง', level: 3 },
  { en: 'I LIKE PINK', trans: 'pom chorp sii chompuu', thai: 'ผมชอบสีชมพู', level: 3 },
  { en: 'I PREFER RED', trans: 'pom chorp sii daeng maak gwaa', thai: 'ผมชอบสีแดงมากกว่า', level: 3 },
  { en: 'I LIKE BLACK AND YELLOW', trans: 'pom chorp sii dam gap sii leuang', thai: 'ผมชอบสีดำกับสีเหลือง', level: 3 },
  { en: 'I HAVE TEN FRIENDS', trans: 'pom mii peuan sip kon', thai: 'ผมมีเพื่อนสิบคน', level: 3 },
  { en: 'I HAVE ONE BOOK', trans: 'pom mii nang-seuu neung leem', thai: 'ผมมีหนังสือหนึ่งเล่ม', level: 3 },
  { en: 'WE HAVE FIVE COCONUTS', trans: 'rao mii ma-praao haa luuk', thai: 'เรามีมะพร้าวห้าลูก', level: 3 },
  { en: 'WE HAVE SEVEN COCONUTS', trans: 'rao mii ma-praao jet luuk', thai: 'เรามีมะพร้าวเจ็ดลูก', level: 3 },
  { en: 'WE HAVE NINE COCONUTS', trans: 'rao mii ma-praao gao luuk', thai: 'เรามีมะพร้าวเก้าลูก', level: 3 },
  { en: 'HE CRIES BECAUSE BROKE ARM', trans: 'kao rorng-hai pror-waa kaen hak', thai: 'เขาร้องไห้เพราะว่าแขนหัก', level: 3 },
  { en: 'HE NEEDS A TOWEL AND SOAP', trans: 'kao dtorng gaan paa-chet-dtuua gap sa-buu', thai: 'เขาต้องการผ้าเช็ดตัวกับสบู่', level: 3 },
  { en: 'WOULD YOU LIKE SOME ORANGE JUICE?', trans: 'ao nam som mai?', thai: 'เอาน้ำส้มไหม?', level: 3 },
  { en: 'HOW MANY FRIENDS DO YOU HAVE?', trans: 'kun mii peuan gii kon?', thai: 'คุณมีเพื่อนกี่คน?', level: 3 },
  { en: 'HOW MANY MONKEYS DO YOU HAVE?', trans: 'kun mii ling gii dtuua?', thai: 'คุณมีลิงกี่ตัว?', level: 3 },
  { en: 'HOW MANY MONKEYS DO WE HAVE?', trans: 'rao mii ling gii dtuua?', thai: 'เรามีลิงกี่ตัว?', level: 3 },
  { en: 'HOW MANY COCONUTS DO WE HAVE?', trans: 'rao mii ma-praao gii luuk?', thai: 'เรามีมะพร้าวกี่ลูก?', level: 3 },
  { en: 'HOW MUCH APPLE COST?', trans: 'apple raa-kaa taorai?', thai: 'แอปเปิ้ลราคาเท่าไร?', level: 3 },
  { en: 'WHICH DAY DO YOU PLAY MUSIC?', trans: 'kun leen don-dtrii wan nai?', thai: 'คุณเล่นดนตรีวันไหน?', level: 3 },
  { en: 'WHEN OLEG BIRTHDAY?', trans: 'wan-gert Oleg meua-rai?', thai: 'วันเกิดโอเลกเมื่อไร?', level: 3 },
  { en: 'ARE YOU AVAILABLE ON SATURDAY?', trans: 'kun waang wan sao mai?', thai: 'คุณว่างวันเสาร์ไหม?', level: 3 },
  { en: 'CAN YOU GIVE ME YOUR PHONE NUMBER?', trans: 'kor ber dai-mai?', thai: 'ขอเบอร์ได้ไหม?', level: 3 },
  { en: 'WHERE ARE WE GOING?', trans: 'rao ja bpai tii nai?', thai: 'เราจะไปที่ไหน?', level: 3 },
  { en: 'AT NIGHT, I CAN WATCH TV', trans: 'dtorn kam pom duu tii-wii dai', thai: 'ตอนค่ำผมดูทีวีได้', level: 3 },
  { en: 'IN THE AFTERNOON, I READ BOOK', trans: 'dtorn baai pom aan nang-seuu', thai: 'ตอนบ่ายผมอ่านหนังสือ', level: 3 },
  { en: 'WE GO TO SCHOOL AT 8AM', trans: 'rao bpai tii rohng-rian bpaet mohng chao', thai: 'เราไปที่โรงเรียนแปดโมงเช้า', level: 3 },
  { en: 'CAN YOU BRING ME TO AIRPORT?', trans: 'kun bpai-song pom tii sa-naam-bin dai-mai?', thai: 'คุณไปส่งผมที่สนามบินได้ไหม?', level: 3 },
  { en: 'CAN YOU PICKUP ME FROM AIRPORT?', trans: 'kun maa-rap pom tii sa-naam-bin dai-mai?', thai: 'คุณมารับผมที่สนามบินได้ไหม?', level: 3 },
  { en: 'YOU COME MEET ME AT HOME, IN THE MORNING', trans: 'kun maa-jer pom tii baan, nai dtorn chao', thai: 'คุณมาเจอผมที่บ้าน ในตอนเช้า', level: 3 },
  { en: 'WE WILL GO TO THE AQUARIUM', trans: 'rao ja bpai tii pi-pit-ta-pan sat-naam', thai: 'เราจะไปที่พิพิธภัณฑ์สัตว์น้ำ', level: 3 },
  { en: 'I WANT TO GO TO BKK, DO YOU WANT TO GO TOGETHER?', trans: 'pom yaak bpai grung-tep, kun yaak bpai duai gan mai?', thai: 'ผมอยากไปกรุงเทพ คุณอยากไปด้วยกันไหม?', level: 3 },

  { en: 'OLEH BILETSKII', trans: 'oh-lee bi-leet-sa-gii', thai: 'โอเลห์ บิเลตสกี', special: true, level: 3 },
];
