const VOCAB = [

  // ═══ УРОВЕНЬ 1 — СЛОВА ═══

  // -- Местоимения --
  { en: 'SHE', trans: 'ter', thai: 'เธอ', level: 1 , lesson: 1 },
  { en: 'HE/THEY', trans: 'kao', thai: 'เขา', level: 1 , lesson: 1 },
  { en: 'PLURAL ARTICLE', trans: 'puuak', thai: 'พวก', level: 1 , lesson: 1 },

  // -- Частицы --
  { en: 'OUT OF', trans: 'nork', thai: 'นอก', level: 1 , lesson: 3 },
  { en: 'PLEASE...', trans: 'noi', thai: 'หน่อย', level: 1 , lesson: 1 },
  { en: 'POLITE PARTICLE', trans: 'noi', thai: 'หน่อย', level: 1 , lesson: 1 },
  { en: 'NO (LOCATION)', trans: 'mai-yuu', thai: 'ไม่อยู่', level: 1 , lesson: 1 },
  { en: 'ONLY', trans: 'taonan', thai: 'เท่านั้น', level: 1 , lesson: 1 },
  { en: 'TOGETHER', trans: 'duai gan', thai: 'ด้วยกัน', level: 1 , lesson: 1 },
  { en: 'PLEASE DON\'T...', trans: 'yaa', thai: 'อย่า', level: 1 , lesson: 1 },
  { en: 'FORBIDDEN', trans: 'haam', thai: 'ห้าม', level: 1 , lesson: 1 },
  { en: 'SHOULD', trans: 'naa ja', thai: 'น่าจะ', level: 1 , lesson: 1 },
  { en: 'ALSO / TOO', trans: 'duai', thai: 'ด้วย', level: 1 , lesson: 1 },

  // -- Вопросительные слова --
  { en: 'HOW?', trans: 'yaang-rai?', thai: 'อย่างไร?', level: 1 , lesson: 3 },
  { en: 'WHY?', trans: 'tam-mai?', thai: 'ทำไม?', level: 1 , lesson: 3 },
  { en: 'WHICH?', trans: 'nai', thai: 'ไหน', level: 1 , lesson: 3 },

  // -- Числа 1–10 --
  { en: 'ONE', trans: 'neung', thai: 'หนึ่ง', level: 1 , lesson: 2 },
  { en: 'TWO', trans: 'sorng', thai: 'สอง', level: 1 , lesson: 2 },
  { en: 'THREE', trans: 'saam', thai: 'สาม', level: 1 , lesson: 2 },
  { en: 'FOUR', trans: 'sii', thai: 'สี่', level: 1 , lesson: 2 },
  { en: 'FIVE', trans: 'haa', thai: 'ห้า', level: 1 , lesson: 2 },
  { en: 'SIX', trans: 'hok', thai: 'หก', level: 1 , lesson: 2 },
  { en: 'SEVEN', trans: 'jet', thai: 'เจ็ด', level: 1 , lesson: 2 },
  { en: 'EIGHT', trans: 'bpaet', thai: 'แปด', level: 1 , lesson: 2 },
  { en: 'NINE', trans: 'gao', thai: 'เก้า', level: 1 , lesson: 2 },
  { en: 'TEN', trans: 'sip', thai: 'สิบ', level: 1 , lesson: 2 },
  { en: 'ONE HUNDRED', trans: 'roi', thai: 'ร้อย', level: 1 , lesson: 2 },
  { en: 'THOUSAND', trans: 'pan', thai: 'พัน', level: 1 , lesson: 2 },
  { en: 'NUMBER', trans: 'leek', thai: 'เลข', level: 1 , lesson: 2 },

  // -- Глаголы --
  { en: 'TO NEED', trans: 'dtorng gaan', thai: 'ต้องการ', level: 1 , lesson: 3 },
  { en: 'STOP', trans: 'jort', thai: 'จอด', level: 1 , lesson: 3 },
  { en: 'TO TURN', trans: 'liao', thai: 'เลี้ยว', level: 1 , lesson: 3 },
  { en: 'TO TOUCH', trans: 'jap', thai: 'จับ', level: 1 , lesson: 3 },
  { en: 'TAKE', trans: 'yip', thai: 'หยิบ', level: 1 , lesson: 3 },
  { en: 'TO PUT', trans: 'waang', thai: 'วาง', level: 1 , lesson: 3 },
  { en: 'TO DREAM', trans: 'fan', thai: 'ฝัน', level: 1 , lesson: 3 },
  { en: 'TO FORGET', trans: 'leuum', thai: 'ลืม', level: 1 , lesson: 3 },
  { en: 'TO COUNT', trans: 'nap', thai: 'นับ', level: 1 , lesson: 3 },
  { en: 'TO PRACTICE', trans: 'feuk', thai: 'ฝึก', level: 1 , lesson: 3 },
  { en: 'TO AGREE WITH...', trans: 'hen duai', thai: 'เห็นด้วย', level: 1 , lesson: 3 },
  { en: 'HAVING FUN', trans: 'sanuk', thai: 'สนุก', level: 1 , lesson: 3 },
  { en: 'CELEBRATE', trans: 'cha-lorng', thai: 'ฉลอง', level: 1 , lesson: 3 },
  { en: 'TO MISS(REGULAR MEETING)', trans: 'kaat', thai: 'ขาด', level: 1 , lesson: 3 },
  { en: 'FINISH/CLOSE', trans: 'bpit', thai: 'ปิด', level: 1 , lesson: 3 },
  { en: 'START/OPEN', trans: 'bpert', thai: 'เปิด', level: 1 , lesson: 3 },
  { en: 'NEXT', trans: 'dtor', thai: 'ต่อ', level: 1 , lesson: 3 },
  { en: 'SITDOWN', trans: 'nang long', thai: 'นั่งลง', level: 1 , lesson: 3 },
  { en: 'TO GIVE', trans: 'hai', thai: 'ให้', level: 1 , lesson: 3 },
  { en: 'TO WAIT', trans: 'ror', thai: 'รอ', level: 1 , lesson: 3 },
  { en: 'TO HELP', trans: 'chuai', thai: 'ช่วย', level: 1 , lesson: 3 },
  { en: 'TO TRY', trans: 'lorng', thai: 'ลอง', level: 1 , lesson: 3 },
  { en: 'TO CALL (phone)', trans: 'toh', thai: 'โทร', level: 1 , lesson: 3 },
  { en: 'TO PAY', trans: 'jaai', thai: 'จ่าย', level: 1 , lesson: 3 },
  { en: 'TO ASK', trans: 'taam', thai: 'ถาม', level: 1 , lesson: 3 },
  { en: 'HOW MANY...', trans: 'gii', thai: 'กี่', level: 1 , lesson: 3 },
  { en: 'TO PREFER', trans: 'chorp maak gwaa', thai: 'ชอบมากกว่า', level: 1 , lesson: 3 },
  { en: 'TO GET BETTER', trans: 'haai-dii', thai: 'หายดี', level: 1 , lesson: 3 },
  { en: 'TO CROSS ROAD/STREET', trans: 'kaam ta-non', thai: 'ข้ามถนน', level: 1 , lesson: 3 },

  { en: 'POISONOUS', trans: 'mii-pit', thai: 'มีพิษ', level: 1 , lesson: 10 },
  { en: 'TOO (MUCH)', trans: 'gern-bpai', thai: 'เกินไป', level: 1 , lesson: 10 },
  { en: 'BITTER', trans: 'kom', thai: 'ขม', level: 1 , lesson: 7 },
  { en: 'HUNGRY', trans: 'hio', thai: 'หิว', level: 1 , lesson: 5 },
  { en: 'FULL (after eating)', trans: 'im', thai: 'อิ่ม', level: 1 , lesson: 5 },
  { en: 'SAD', trans: 'sia-jai', thai: 'เสียใจ', level: 1 , lesson: 10 },
  { en: 'ANGRY', trans: 'groht', thai: 'โกรธ', level: 1 , lesson: 10 },
  { en: 'SCARED', trans: 'dtok-jai', thai: 'ตกใจ', level: 1 , lesson: 10 },
  { en: 'HAPPY (HIM)', trans: 'suk-san', thai: 'สุขสันต์', level: 1 , lesson: 10 },
  { en: 'DRUNK', trans: 'mao', thai: 'เมา', level: 1 , lesson: 10 },
  // -- Семья --
  { en: 'CHILDREN', trans: 'dek dek', thai: 'เด็กเด็ก', level: 1 , lesson: 9 },

  // -- Части тела --

  { en: 'BREAK/BROKEN', trans: 'hak', thai: 'หัก', level: 1 , lesson: 8 },
  { en: 'FEVER', trans: 'kai', thai: 'ไข้', level: 1 , lesson: 8 },
  { en: 'COUGH', trans: 'ai', thai: 'ไอ', level: 1 , lesson: 8 },
  { en: 'SYMPTOMS', trans: 'aa-gaan', thai: 'อาการ', level: 1 , lesson: 8 },

  // -- Еда и напитки --
  { en: 'VEGETABLES', trans: 'pak', thai: 'ผัก', level: 1 , lesson: 5 },
  { en: 'DEEP FRIED', trans: 'tort', thai: 'ทอด', level: 1 , lesson: 5 },
  { en: 'BOILED', trans: 'dtom', thai: 'ต้ม', level: 1 , lesson: 5 },
  { en: 'GRILLED', trans: 'yaang', thai: 'ย่าง', level: 1 , lesson: 5 },
  { en: 'STIR FRIED', trans: 'pat', thai: 'ผัด', level: 1 , lesson: 5 },

  // -- Животные --
  { en: 'FISH', trans: 'bplaa', thai: 'ปลา', level: 1 , lesson: 7 },
  { en: 'GIRAFFE', trans: 'yii-raap', thai: 'ยีราฟ', level: 1 , lesson: 9 },

  // -- Места --
  { en: 'STATION', trans: 'sa-taa-nii', thai: 'สถานี', level: 1 , lesson: 4 },
  { en: 'BEACH', trans: 'chaai haat', thai: 'ชายหาด', level: 1 , lesson: 4 },
  { en: 'SUB STREET', trans: 'soi', thai: 'ซอย', level: 1 , lesson: 4 },

  // -- Вещи --
  { en: 'SCISSORS', trans: 'gan-grai', thai: 'กรรไกร', level: 1 , lesson: 8 },
  { en: 'GLUE', trans: 'gaao', thai: 'กาว', level: 1 , lesson: 8 },
  { en: 'RULER', trans: 'mai-ban-tat', thai: 'ไม้บรรทัด', level: 1 , lesson: 8 },
  { en: 'ERASER', trans: 'yaang-lop', thai: 'ยางลบ', level: 1 , lesson: 8 },
  { en: 'DOOR', trans: 'bpra-dtuu', thai: 'ประตู', level: 1 , lesson: 10 },
  { en: 'MIRROR', trans: 'gra-jok', thai: 'กระจก', level: 1 , lesson: 10 },
  { en: 'SHELF', trans: 'chan-waang', thai: 'ชั้นวาง', level: 1 , lesson: 10 },
  { en: 'TOWEL', trans: 'paa-chet-dtuua', thai: 'ผ้าเช็ดตัว', level: 1 , lesson: 8 },
  { en: 'TOY', trans: 'korng leen', thai: 'ของเล่น', level: 1 , lesson: 10 },
  { en: 'TATOO', trans: 'roi-sak', thai: 'รอยสัก', level: 1 , lesson: 8 },
  { en: 'MEDICATION', trans: 'yaa', thai: 'ยา', level: 1 , lesson: 8 },
  { en: 'BELL', trans: 'ra-kang', thai: 'ระฆัง', level: 1 , lesson: 10 },
  { en: 'SMALL CYMBAL', trans: 'ching', thai: 'ฉิ่ง', level: 1 , lesson: 10 },

  // -- Классификаторы --
  { en: 'BOOKS (classifier)', trans: 'leem', thai: 'เล่ม', level: 1 , lesson: 10 },
  { en: 'SMALL OBJECTS (classifier)', trans: 'an', thai: 'อัน', level: 1 , lesson: 10 },
  { en: 'CLASSIFIER FOR VEHICLES', trans: 'kan', thai: 'คัน', level: 1 , lesson: 10 },
  { en: 'CLASSIFIER FOR STREETS', trans: 'seen', thai: 'เส้น', level: 1 , lesson: 10 },
  { en: 'CLASSIFIER FOR PLACE, LOCATION', trans: 'haeng', thai: 'แห่ง', level: 1 , lesson: 10 },

  // -- Время (слова) --
  { en: 'YESTERDAY', trans: 'meua waan', thai: 'เมื่อวาน', level: 1 , lesson: 2 },
  { en: 'SEASON', trans: 'reuduu', thai: 'ฤดู', level: 1 , lesson: 2 },
  { en: 'BIRTHDAY', trans: 'wan-gert', thai: 'วันเกิด', level: 1 , lesson: 2 },

  // -- Деньги --

  // ═══ УРОВЕНЬ 2 — СЛОВОСОЧЕТАНИЯ ═══

  // -- Числа 11–100 --
  { en: 'ELEVEN', trans: 'sip et', thai: 'สิบเอ็ด', level: 2 , lesson: 2 },
  { en: 'TWELVE', trans: 'sip sorng', thai: 'สิบสอง', level: 2 , lesson: 2 },
  { en: 'THIRTEEN', trans: 'sip saam', thai: 'สิบสาม', level: 2 , lesson: 2 },
  { en: 'FOURTEEN', trans: 'sip sii', thai: 'สิบสี่', level: 2 , lesson: 2 },
  { en: 'FIFTEEN', trans: 'sip haa', thai: 'สิบห้า', level: 2 , lesson: 2 },
  { en: 'SIXTEEN', trans: 'sip hok', thai: 'สิบหก', level: 2 , lesson: 2 },
  { en: 'SEVENTEEN', trans: 'sip jet', thai: 'สิบเจ็ด', level: 2 , lesson: 2 },
  { en: 'EIGHTEEN', trans: 'sip bpaet', thai: 'สิบแปด', level: 2 , lesson: 2 },
  { en: 'NINETEEN', trans: 'sip gao', thai: 'สิบเก้า', level: 2 , lesson: 2 },
  { en: 'TWENTY', trans: 'yii sip', thai: 'ยี่สิบ', level: 2 , lesson: 2 },
  { en: 'TWENTY ONE', trans: 'yii sip et', thai: 'ยี่สิบเอ็ด', level: 2 , lesson: 2 },
  { en: 'TWENTY TWO', trans: 'yii sip sorng', thai: 'ยี่สิบสอง', level: 2 , lesson: 2 },
  { en: 'TWENTY THREE', trans: 'yii sip saam', thai: 'ยี่สิบสาม', level: 2 , lesson: 2 },
  { en: 'TWENTY FOUR', trans: 'yii sip sii', thai: 'ยี่สิบสี่', level: 2 , lesson: 2 },
  { en: 'TWENTY FIVE', trans: 'yii sip haa', thai: 'ยี่สิบห้า', level: 2 , lesson: 2 },
  { en: 'TWENTY SIX', trans: 'yii sip hok', thai: 'ยี่สิบหก', level: 2 , lesson: 2 },
  { en: 'TWENTY SEVEN', trans: 'yii sip jet', thai: 'ยี่สิบเจ็ด', level: 2 , lesson: 2 },
  { en: 'TWENTY EIGHT', trans: 'yii sip bpaet', thai: 'ยี่สิบแปด', level: 2 , lesson: 2 },
  { en: 'TWENTY NINE', trans: 'yii sip gao', thai: 'ยี่สิบเก้า', level: 2 , lesson: 2 },
  { en: 'THIRTY', trans: 'saam sip', thai: 'สามสิบ', level: 2 , lesson: 2 },
  { en: 'FORTY', trans: 'sii sip', thai: 'สี่สิบ', level: 2 , lesson: 2 },
  { en: 'FIFTY', trans: 'haa sip', thai: 'ห้าสิบ', level: 2 , lesson: 2 },
  { en: 'SIXTY', trans: 'hok sip', thai: 'หกสิบ', level: 2 , lesson: 2 },
  { en: 'SEVENTY', trans: 'jet sip', thai: 'เจ็ดสิบ', level: 2 , lesson: 2 },
  { en: 'SEVENTY ONE', trans: 'jet sip et', thai: 'เจ็ดสิบเอ็ด', level: 2 , lesson: 2 },
  { en: 'EIGHTY', trans: 'bpaet sip', thai: 'แปดสิบ', level: 2 , lesson: 2 },
  { en: 'EIGHTY ONE', trans: 'bpaet sip et', thai: 'แปดสิบเอ็ด', level: 2 , lesson: 2 },
  { en: 'NINETY', trans: 'gao sip', thai: 'เก้าสิบ', level: 2 , lesson: 2 },
  { en: 'NINETY ONE', trans: 'gao sip et', thai: 'เก้าสิบเอ็ด', level: 2 , lesson: 2 },

  // -- Месяцы --
  { en: 'JANUARY', trans: 'ma-ga-raa-kom', thai: 'มกราคม', level: 2 , lesson: 2 },
  { en: 'FEBRUARY', trans: 'gum-paa-pan', thai: 'กุมภาพันธ์', level: 2 , lesson: 2 },
  { en: 'MARCH', trans: 'mii-naa-kom', thai: 'มีนาคม', level: 2 , lesson: 2 },
  { en: 'APRIL', trans: 'mee-saa-yon', thai: 'เมษายน', level: 2 , lesson: 2 },
  { en: 'MAY', trans: 'preut-sa-paa-kom', thai: 'พฤษภาคม', level: 2 , lesson: 2 },
  { en: 'JUNE', trans: 'mi-tu-naa-yon', thai: 'มิถุนายน', level: 2 , lesson: 2 },
  { en: 'JULY', trans: 'ga-ra-ga-daa-kom', thai: 'กรกฎาคม', level: 2 , lesson: 2 },
  { en: 'AUGUST', trans: 'sing-haa-kom', thai: 'สิงหาคม', level: 2 , lesson: 2 },
  { en: 'SEPTEMBER', trans: 'gan-yaa-yon', thai: 'กันยายน', level: 2 , lesson: 2 },
  { en: 'OCTOBER', trans: 'dtu-laa-kom', thai: 'ตุลาคม', level: 2 , lesson: 2 },
  { en: 'NOVEMBER', trans: 'preut-sa-ji-gaa-yon', thai: 'พฤศจิกายน', level: 2 , lesson: 2 },
  { en: 'DECEMBER', trans: 'tan-waa-kom', thai: 'ธันวาคม', level: 2 , lesson: 2 },

  // -- Сезоны и погода --
  { en: 'WINTER', trans: 'reuduu naao', thai: 'ฤดูหนาว', level: 2 , lesson: 2 },
  { en: 'SPRING', trans: 'reuduu bai-mai-pli', thai: 'ฤดูใบไม้ผลิ', level: 2 , lesson: 2 },
  { en: 'SUMMER', trans: 'reuduu rorn', thai: 'ฤดูร้อน', level: 2 , lesson: 2 },
  { en: 'AUTUMN', trans: 'reuduu bai-mai-ruuang', thai: 'ฤดูใบไม้ร่วง', level: 2 , lesson: 2 },
  { en: 'WEATHER CONDITION', trans: 'sa-paap aa-gaat', thai: 'สภาพอากาศ', level: 2 , lesson: 2 },

  { en: 'NEW YEAR', trans: 'bpii mai', thai: 'ปีใหม่', level: 2 , lesson: 2 },
  { en: '1ST', trans: 'wan tii neung', thai: 'วันที่หนึ่ง', level: 2 , lesson: 2 },


  // -- Комнаты --
  { en: 'KITCHEN', trans: 'horng kruua', thai: 'ห้องครัว', level: 2 , lesson: 4 },
  { en: 'LIVING ROOM', trans: 'horng nang leen', thai: 'ห้องนั่งเล่น', level: 2 , lesson: 4 },
  { en: 'CLASSROOM', trans: 'horng rian', thai: 'ห้องเรียน', level: 2 , lesson: 4 },
  { en: 'GLASS-DOOR CABINET', trans: 'dtuu gra-jok', thai: 'ตู้กระจก', level: 2 , lesson: 4 },

  // -- Ежедневные дела --
  { en: 'TO WASH YOUR HANDS', trans: 'laang meuu', thai: 'ล้างมือ', level: 2 , lesson: 5 },
  { en: 'COOK FOOD', trans: 'tam aahaan', thai: 'ทำอาหาร', level: 2 , lesson: 5 },
  { en: 'HOMEWORK', trans: 'ngaan baan', thai: 'งานบ้าน', level: 2 , lesson: 5 },
  { en: 'TAKE A PHOTO', trans: 'taai-ruup', thai: 'ถ่ายรูป', level: 2 , lesson: 5 },
  { en: 'PLAY MUSIC', trans: 'don-dtrii', thai: 'ดนตรี', level: 2 , lesson: 5 },
  { en: 'THAI MASSAGE', trans: 'nuuat tai', thai: 'นวดไทย', level: 2 , lesson: 5 },
  { en: 'VISIT DOCTOR', trans: 'haa mor', thai: 'หาหมอ', level: 2 , lesson: 5 },
  { en: 'TO TAKE MEDICATION', trans: 'gin yaa', thai: 'กินยา', level: 2 , lesson: 5 },
  { en: 'TO BE ABSENT (FOR THE SCHOOL)', trans: 'kaat rian', thai: 'ขาดเรียน', level: 2 , lesson: 5 },
  { en: 'TO BE ABSENT (FOR THE WORK)', trans: 'kaat ngaan', thai: 'ขาดงาน', level: 2 , lesson: 5 },

  // -- Транспорт --
  { en: 'ELECTRIC TRAIN', trans: 'rot fai-faa', thai: 'รถไฟฟ้า', level: 2 , lesson: 4 },

  // -- Навигация --
  { en: 'LEFT SIDE', trans: 'taang-saai', thai: 'ทางซ้าย', level: 2 , lesson: 4 },
  { en: 'RIGHT SIDE', trans: 'taang-kwaa', thai: 'ทางขวา', level: 2 , lesson: 4 },
  { en: 'STRAIGHT', trans: 'dtorng bpai', thai: 'ตรงไป', level: 2 , lesson: 4 },
  { en: 'ROUNDABOUT', trans: 'wong-wian', thai: 'วงเวียน', level: 2 , lesson: 4 },
  { en: '4 INTERSECTION', trans: 'sii yaek', thai: 'สี่แยก', level: 2 , lesson: 4 },
  { en: 'TRAFFIC LIGHT', trans: 'sanyaan-fai', thai: 'สัญญาณไฟ', level: 2 , lesson: 4 },
  { en: 'ENTRANCE', trans: 'taang kao', thai: 'ทางเข้า', level: 2 , lesson: 4 },
  { en: 'GO WALKING', trans: 'dern bpai', thai: 'เดินไป', level: 2 , lesson: 4 },
  { en: 'TO TURN LEFT', trans: 'liao saai', thai: 'เลี้ยวซ้าย', level: 2 , lesson: 4 },
  { en: 'TO TURN RIGHT', trans: 'liao kwaa', thai: 'เลี้ยวขวา', level: 2 , lesson: 4 },
  { en: 'TO REVERSE', trans: 'toi lang', thai: 'ถอยหลัง', level: 2 , lesson: 4 },
  { en: 'U TURN', trans: 'glap rot', thai: 'กลับรถ', level: 2 , lesson: 4 },
  { en: 'BUS STOP', trans: 'bpaai rot mee', thai: 'ป้ายรถเมล์', level: 2 , lesson: 4 },

  // -- Покупки --
  { en: 'CASH', trans: 'ngern-sot', thai: 'เงินสด', level: 2 , lesson: 6 },
  { en: 'CHANGE (money)', trans: 'ngern-torn', thai: 'เงินทอน', level: 2 , lesson: 6 },
  { en: 'RECEIPT', trans: 'bai-set', thai: 'ใบเสร็จ', level: 2 , lesson: 6 },

  // -- Одежда --
  { en: 'CLOTHES', trans: 'chut / seua-paa', thai: 'ชุด / เสื้อผ้า', level: 2 , lesson: 6 },
  { en: 'SUNGLASSES', trans: 'waen-gan-daet', thai: 'แว่นกันแดด', level: 2 , lesson: 6 },
  { en: 'SUNCREAM', trans: 'kriim-gan-daet', thai: 'ครีมกันแดด', level: 2 , lesson: 6 },
  { en: 'RAINCOAT', trans: 'seua-gan-fon', thai: 'เสื้อกันฝน', level: 2 , lesson: 6 },
  { en: 'SWEATER', trans: 'seua-gan-naao', thai: 'เสื้อกันหนาว', level: 2 , lesson: 6 },
  { en: 'COAT', trans: 'seua koht', thai: 'เสื้อโค้ต', level: 2 , lesson: 6 },

  // -- Медицина (фразы) --
  { en: 'HEADACHE', trans: 'bpuuat huua', thai: 'ปวดหัว', level: 2 , lesson: 8 },
  { en: 'PHARMACY', trans: 'raan yaa', thai: 'ร้านยา', level: 2 , lesson: 4 },
  { en: 'ICE CREAM SHOP', trans: 'raan ai sa griim', thai: 'ร้านไอศกรีม', level: 2 , lesson: 4 },
  { en: 'AQUARIUM', trans: 'pi-pit-ta-pan sat-naam', thai: 'พิพิธภัณฑ์สัตว์น้ำ', level: 2 , lesson: 4 },
  { en: 'WIFI PASSWORD', trans: 'rahat wai fai', thai: 'รหัสไวไฟ', level: 2 , lesson: 1 },
  { en: 'NEXT TO/BESIDE', trans: 'kaang kaang', thai: 'ข้างข้าง', level: 2 , lesson: 1 },
  { en: 'NO / INCORRECT', trans: 'mai chai', thai: 'ไม่ใช่', level: 2 , lesson: 1 },
  { en: 'TOM YUM', trans: 'dtom-yam', thai: 'ต้มยำ', level: 2 , lesson: 6 },
  { en: 'PAPAYA SALAD', trans: 'som-dtam', thai: 'ส้มตำ', level: 2 , lesson: 6 },
  { en: 'MAYBE', trans: 'aat-ja', thai: 'อาจจะ', level: 2 , lesson: 1 },
  { en: 'SURE / DEFINITELY', trans: 'nae-norn', thai: 'แน่นอน', level: 2 , lesson: 1 },
  { en: 'MY BIRTHDAY', trans: 'wan-gert korng pom', thai: 'วันเกิดของผม', level: 2 , lesson: 2 },
  { en: 'TO COME BACK', trans: 'glap maa', thai: 'กลับมา', level: 2 , lesson: 3 },
  { en: 'EVERYONE', trans: 'tuk kon', thai: 'ทุกคน', level: 2 , lesson: 1 },
  { en: 'FORBIDDEN TO TOUCH', trans: 'haam jap', thai: 'ห้ามจับ', level: 2 , lesson: 1 },
  { en: 'FORBIDDEN TO ENTER', trans: 'haam kao', thai: 'ห้ามเข้า', level: 2 , lesson: 1 },
  { en: 'FORBIDDEN FOR PARKING', trans: 'haam jort', thai: 'ห้ามจอด', level: 2 , lesson: 1 },
  { en: 'FORBIDDEN TO SMOKE', trans: 'haam suup burii', thai: 'ห้ามสูบบุหรี่', level: 2 , lesson: 1 },
  { en: 'HELP EMERGENCY', trans: 'chuai duai', thai: 'ช่วยด้วย', level: 2 , lesson: 1 },
  { en: 'STOP HERE', trans: 'jort tii nii', thai: 'จอดที่นี่', level: 2 , lesson: 1 },
  { en: 'STOP BEFORE...', trans: 'jort gorn', thai: 'จอดก่อน', level: 2 , lesson: 1 },
  { en: 'COCONUT TREE', trans: 'dton ma-praao', thai: 'ต้นมะพร้าว', level: 2 , lesson: 9 },
  { en: 'SHARK', trans: 'bplaa cha-laam', thai: 'ปลาฉลาม', level: 2 , lesson: 9 },

  // ═══ УРОВЕНЬ 3 — ПРЕДЛОЖЕНИЯ ═══
  // (short to long)

  { en: 'I AM LATE', trans: 'pom saai', thai: 'ผมสาย', level: 3 , lesson: 3 },
  { en: 'I AM PLAYING', trans: 'pom gamlang leen', thai: 'ผมกำลังเล่น', level: 3 , lesson: 3 },
  { en: 'SHE SLEEPS', trans: 'ter norn lap', thai: 'เธอนอนหลับ', level: 3 , lesson: 8 },
  { en: 'I HAVE A CAT', trans: 'pom mii maeo', thai: 'ผมมีแมว', level: 3 , lesson: 9 },
  { en: 'I DONT KNOW', trans: 'pom mai ruu', thai: 'ผมไม่รู้', level: 3 , lesson: 1 },
  { en: 'I\'M TIRED', trans: 'pom neuai', thai: 'ผมเหนื่อย', level: 3 , lesson: 5 },
  { en: 'I AM HUNGRY', trans: 'pom hio laeo', thai: 'ผมหิวแล้ว', level: 3 , lesson: 5 },
  { en: 'SHE IS SAD', trans: 'kao sia-jai', thai: 'เขาเสียใจ', level: 3 , lesson: 9 },
  { en: 'IT\'S VERY SPICY', trans: 'pet maak', thai: 'เผ็ดมาก', level: 3 , lesson: 7 },
  { en: 'TODAY IS FRIDAY', trans: 'wan nii wan suk', thai: 'วันนี้วันศุกร์', level: 3 , lesson: 2 },
  { en: 'TOMORROW IS SATURDAY', trans: 'prung nii wan sao', thai: 'พรุ่งนี้วันเสาร์', level: 3 , lesson: 2 },
  { en: 'HE HAS HEADACHE', trans: 'kao bpuuat huua', thai: 'เขาปวดหัว', level: 3 , lesson: 8 },
  { en: 'BECAUSE I DON\'T FEEL WELL', trans: 'pror-waa mai sa-baai', thai: 'เพราะว่าไม่สบาย', level: 3 , lesson: 8 },
  { en: 'EVERYONE HAS A COUGH', trans: 'tuk kon ai', thai: 'ทุกคนไอ', level: 3 , lesson: 8 },
  { en: 'THEY DRINK MILK', trans: 'puuak kao deuum nom', thai: 'พวกเขาดื่มนม', level: 3 , lesson: 5 },
  { en: 'HE/THEY DRINK(S) MILK', trans: 'kao deuum nom', thai: 'เขาดื่มนม', level: 3 , lesson: 5 },
  { en: 'WE LIKE DESSERT', trans: 'rao chorp kanom', thai: 'เราชอบขนม', level: 3 , lesson: 5 },
  { en: 'SHE WASHES HER HAIR', trans: 'ter sa pom', thai: 'เธอสระผม', level: 3 , lesson: 5 },
  { en: 'I\'M FROM THAILAND', trans: 'pom maa jaak bpra-tet Tai', thai: 'ผมมาจากประเทศไทย', level: 3 , lesson: 1 },
  { en: 'THIS IS MY SHIRT', trans: 'nii seua korng pom', thai: 'นี่เสื้อของผม', level: 3 , lesson: 6 },
  { en: 'THIS IS MY MOTHER', trans: 'nii keuu kun mae', thai: 'นี่คือคุณแม่', level: 3 , lesson: 9 },
  { en: 'ARE YOU HAVING FUN?', trans: 'sanuk mai?', thai: 'สนุกไหม?', level: 3 , lesson: 3 },
  { en: 'WHAT IS THIS?', trans: 'nii keuu arai?', thai: 'นี่คืออะไร?', level: 3 , lesson: 1 },
  { en: 'WHAT IS THAT?', trans: 'nan keuu arai?', thai: 'นั่นคืออะไร?', level: 3 , lesson: 1 },
  { en: 'WHO IS THIS?', trans: 'nii keuu krai?', thai: 'นี่คือใคร?', level: 3 , lesson: 1 },
  { en: 'WHO IS THAT?', trans: 'nan keuu krai?', thai: 'นั่นคือใคร?', level: 3 , lesson: 1 },
  { en: 'WHAT ARE YOU DOING?', trans: 'kun tam arai?', thai: 'คุณทำอะไร?', level: 3 , lesson: 1 },
  { en: 'WHERE ARE YOU GOING?', trans: 'kun bpai tii nai?', thai: 'คุณไปที่ไหน?', level: 3 , lesson: 1 },
  { en: 'COME HERE', trans: 'maa nii', thai: 'มานี่', level: 3 , lesson: 1 },
  { en: 'LOOK AT THE CROCODILE', trans: 'duu jo-ra-kee', thai: 'ดูจระเข้', level: 3 , lesson: 9 },
  { en: 'IT IS TOO HOT', trans: 'man rorn gern bpai', thai: 'มันร้อนเกินไป', level: 3 , lesson: 10 },
  { en: 'IT IS TOO COLD', trans: 'man naao gern bpai', thai: 'มันหนาวเกินไป', level: 3 , lesson: 10 },
  { en: 'THERE IS A CAT IN THE HOUSE', trans: 'mii maeo nai baan', thai: 'มีแมวในบ้าน', level: 3 , lesson: 10 },
  { en: 'THERE IS SUNNY', trans: 'mii daet-ork', thai: 'มีแดดออก', level: 3 , lesson: 2 },
  { en: 'THERE IS WINDY', trans: 'mii lom-raeng', thai: 'มีลมแรง', level: 3 , lesson: 2 },
  { en: 'THERE IS RAINBOW', trans: 'mii saai-rung', thai: 'มีสายรุ้ง', level: 3 , lesson: 2 },
  { en: 'THERE IS STORMY', trans: 'mii paa-yu', thai: 'มีพายุ', level: 3 , lesson: 2 },
  { en: 'THERE IS RAINING', trans: 'mii fon-dtok', thai: 'มีฝนตก', level: 3 , lesson: 2 },
  { en: 'THERE IS MONSOON', trans: 'mii mor-ra-sum', thai: 'มีมรสุม', level: 3 , lesson: 2 },
  { en: 'THERE IS SNOWING', trans: 'mii hima-dtok', thai: 'มีหิมะตก', level: 3 , lesson: 2 },
  { en: 'THERE IS VERY CLOUDY', trans: 'mii mek maak', thai: 'มีเมฆมาก', level: 3 , lesson: 2 },
  { en: 'PLEASE HELP WASH THE PLATES', trans: 'chuai laang jaan', thai: 'ช่วยล้างจาน', level: 3 , lesson: 6 },
  { en: 'I SPEAK CHINESE', trans: 'pom puut paa-saa jiin', thai: 'ผมพูดภาษาจีน', level: 3 , lesson: 1 },
  { en: 'I\'M FRENCH', trans: 'pom bpen kon farangset', thai: 'ผมเป็นคนฝรั่งเศส', level: 3 , lesson: 1 },
  { en: 'SPEAK SLOWLY PLEASE', trans: 'puut chaa chaa noi', thai: 'พูดช้าช้าหน่อย', level: 3 , lesson: 1 },
  { en: 'EVERY DAY I DRINK COFFEE', trans: 'tuk wan pom deuum gaa-fae', thai: 'ทุกวันผมดื่มกาแฟ', level: 3 , lesson: 2 },
  { en: 'THERE IS ONE BOOK', trans: 'mii nang-seuu neung leem', thai: 'มีหนังสือหนึ่งเล่ม', level: 3 , lesson: 10 },
  { en: 'PLEASE DON\'T GO THERE', trans: 'yaa bpai tii nan', thai: 'อย่าไปที่นั่น', level: 3 , lesson: 1 },
  { en: 'COME SEE THE GIRAFFE', trans: 'maa duu yii-raap', thai: 'มาดูยีราฟ', level: 3 , lesson: 4 },
  { en: 'WHOOSE IS THIS SHIRT?', trans: 'nii seua korng krai?', thai: 'นี่เสื้อของใคร?', level: 3 , lesson: 6 },
  { en: 'WHAT DAY?', trans: 'wan arai?', thai: 'วันอะไร?', level: 3 , lesson: 2 },
  { en: 'WHICH DAY?', trans: 'wan nai?', thai: 'วันไหน?', level: 3 , lesson: 2 },
  { en: 'I PLAY FOOTBALL EVERY MONDAY', trans: 'pom leen fut-born tuk wan jan', thai: 'ผมเล่นฟุตบอลทุกวันจันทร์', level: 3 , lesson: 2 },
  { en: 'SHE DOES HER HOMEWORK IN THE LIVING ROOM', trans: 'ter tam ngaan baan nai horng nang leen', thai: 'เธอทำงานบ้านในห้องนั่งเล่น', level: 3 , lesson: 5 },
  { en: 'THE GIRAFFE IS TALL', trans: 'yii-raap dtuua suung', thai: 'ยีราฟตัวสูง', level: 3 , lesson: 10 },
  { en: 'THE BUTTERFLY IS SMALL', trans: 'pii-seua dtuua lek', thai: 'ผีเสื้อตัวเล็ก', level: 3 , lesson: 10 },
  { en: 'THE ELEPHANT IS BIG', trans: 'chaang dtuua yai', thai: 'ช้างตัวใหญ่', level: 3 , lesson: 10 },
  { en: 'WHY ARE YOU SAD?', trans: 'kun sia-jai tam-mai?', thai: 'คุณเสียใจทำไม?', level: 3 , lesson: 10 },
  { en: 'WHY DO YOU CRY?', trans: 'kun rorng-hai tam-mai?', thai: 'คุณร้องไห้ทำไม?', level: 3 , lesson: 10 },
  { en: 'HOW IS THE WEATHER?', trans: 'aa-gaat bpen yaang-rai?', thai: 'อากาศเป็นอย่างไร?', level: 3 , lesson: 2 },
  { en: 'CAN YOU HELP ME?', trans: 'chuai pom dai-mai?', thai: 'ช่วยผมได้ไหม?', level: 3 , lesson: 1 },
  { en: 'I KNOW THAT HE IS HERE', trans: 'pom ruu waa kao yuu tii nan', thai: 'ผมรู้ว่าเขาอยู่ที่นั่น', level: 3 , lesson: 3 },
  { en: 'ARE YOU FEELING BETTER YES/OR NOT?', trans: 'kun haai-dii reuu-yang?', thai: 'คุณหายดีหรือยัง?', level: 3 , lesson: 3 },
  { en: 'FROM ONE O\'CLOCK', trans: 'dtang-dtae baai mohng', thai: 'ตั้งแต่บ่ายโมง', level: 3 , lesson: 2 },
  { en: 'FROM MONDAY TO FRIDAY', trans: 'dtang-dtae wan jan teung wan suk', thai: 'ตั้งแต่วันจันทร์ถึงวันศุกร์', level: 3 , lesson: 2 },
  { en: 'I BRUSH MY TEETH IN THE MORNING', trans: 'pom bpraeng fan nai dtorn chao', thai: 'ผมแปรงฟันในตอนเช้า', level: 3 , lesson: 5 },
  { en: 'I EAT SNACK IN THE AFTERNOON', trans: 'pom gin kanom nai dtorn baai', thai: 'ผมกินขนมในตอนบ่าย', level: 3 , lesson: 5 },
  { en: 'I TAKE SHOWER IN THE EVENING', trans: 'pom aap naam nai dtorn yen', thai: 'ผมอาบน้ำในตอนเย็น', level: 3 , lesson: 5 },
  { en: 'I WASH MY HANDS IN THE BATHROOM', trans: 'pom laang meuu nai horng naam', thai: 'ผมล้างมือในห้องน้ำ', level: 3 , lesson: 5 },
  { en: 'THEY SLEEP IN THE BEDROOM', trans: 'puuak kao norn lap nai horng norn', thai: 'พวกเขานอนหลับในห้องนอน', level: 3 , lesson: 4 },
  { en: 'I GO TO THE TEMPLE BY BOAT', trans: 'pom bpai tii wat doi reua', thai: 'ผมไปที่วัดโดยเรือ', level: 3 , lesson: 4 },
  { en: 'WE ARE AT TEMPLE', trans: 'rao yuu tii wat', thai: 'เราอยู่ที่วัด', level: 3 , lesson: 4 },
  { en: 'WE WALK BACK HOME', trans: 'rao dern glap baan', thai: 'เราเดินกลับบ้าน', level: 3 , lesson: 4 },
  { en: 'SHE WEARS PYJAMAS', trans: 'kao sai chut-norn', thai: 'เขาใส่ชุดนอน', level: 3 , lesson: 6 },
  { en: 'ONE COCONUT', trans: 'ma-praao neung luuk', thai: 'มะพร้าวหนึ่งลูก', level: 3 , lesson: 10 },
  { en: 'FOUR COCONUTS', trans: 'ma-praao sii luuk', thai: 'มะพร้าวสี่ลูก', level: 3 , lesson: 10 },
  { en: 'EIGHT COCONUTS', trans: 'ma-praao bpaet luuk', thai: 'มะพร้าวแปดลูก', level: 3 , lesson: 10 },
  { en: 'SEVEN MONKEYS', trans: 'ling jet dtuua', thai: 'ลิงเจ็ดตัว', level: 3 , lesson: 9 },
  { en: 'TEN MONKEYS', trans: 'ling sip dtuua', thai: 'ลิงสิบตัว', level: 3 , lesson: 9 },
  { en: 'A MONKEY ON A COCONUT TREE', trans: 'ling bon dton ma-praao', thai: 'ลิงบนต้นมะพร้าว', level: 3 , lesson: 9 },
  { en: 'BROWN FISH', trans: 'bplaa sii naam-dtaan', thai: 'ปลาสีน้ำตาล', level: 3 , lesson: 10 },
  { en: 'GREEN TURTLE', trans: 'dtao sii kiao', thai: 'เต่าสีเขียว', level: 3 , lesson: 10 },
  { en: 'THE GREEN TURTLE', trans: 'dtao sii kiao', thai: 'เต่าสีเขียว', level: 3 , lesson: 10 },
  { en: 'THE GREY SHARK', trans: 'bplaa cha-laam sii tao', thai: 'ปลาฉลามสีเทา', level: 3 , lesson: 10 },
  { en: 'THE ORANGE AND WHITE FISH', trans: 'bplaa sii som gap sii kaao', thai: 'ปลาสีส้มกับสีขาว', level: 3 , lesson: 10 },
  { en: 'I LIKE TURTLES', trans: 'pom chorp dtao', thai: 'ผมชอบเต่า', level: 3 , lesson: 10 },
  { en: 'I LIKE RED', trans: 'pom chorp sii daeng', thai: 'ผมชอบสีแดง', level: 3 , lesson: 10 },
  { en: 'I LIKE PINK', trans: 'pom chorp sii chompuu', thai: 'ผมชอบสีชมพู', level: 3 , lesson: 10 },
  { en: 'I PREFER RED', trans: 'pom chorp sii daeng maak gwaa', thai: 'ผมชอบสีแดงมากกว่า', level: 3 , lesson: 10 },
  { en: 'I LIKE BLACK AND YELLOW', trans: 'pom chorp sii dam gap sii leuang', thai: 'ผมชอบสีดำกับสีเหลือง', level: 3 , lesson: 10 },
  { en: 'I HAVE TEN FRIENDS', trans: 'pom mii peuan sip kon', thai: 'ผมมีเพื่อนสิบคน', level: 3 , lesson: 10 },
  { en: 'I HAVE ONE BOOK', trans: 'pom mii nang-seuu neung leem', thai: 'ผมมีหนังสือหนึ่งเล่ม', level: 3 , lesson: 10 },
  { en: 'WE HAVE FIVE COCONUTS', trans: 'rao mii ma-praao haa luuk', thai: 'เรามีมะพร้าวห้าลูก', level: 3 , lesson: 10 },
  { en: 'WE HAVE SEVEN COCONUTS', trans: 'rao mii ma-praao jet luuk', thai: 'เรามีมะพร้าวเจ็ดลูก', level: 3 , lesson: 10 },
  { en: 'WE HAVE NINE COCONUTS', trans: 'rao mii ma-praao gao luuk', thai: 'เรามีมะพร้าวเก้าลูก', level: 3 , lesson: 10 },
  { en: 'HE CRIES BECAUSE BROKE ARM', trans: 'kao rorng-hai pror-waa kaen hak', thai: 'เขาร้องไห้เพราะว่าแขนหัก', level: 3 , lesson: 8 },
  { en: 'HE NEEDS A TOWEL AND SOAP', trans: 'kao dtorng gaan paa-chet-dtuua gap sa-buu', thai: 'เขาต้องการผ้าเช็ดตัวกับสบู่', level: 3 , lesson: 8 },
  { en: 'WOULD YOU LIKE SOME ORANGE JUICE?', trans: 'ao naam som mai?', thai: 'เอาน้ำส้มไหม?', level: 3 , lesson: 6 },
  { en: 'HOW MANY FRIENDS DO YOU HAVE?', trans: 'kun mii peuan gii kon?', thai: 'คุณมีเพื่อนกี่คน?', level: 3 , lesson: 10 },
  { en: 'HOW MANY MONKEYS DO YOU HAVE?', trans: 'kun mii ling gii dtuua?', thai: 'คุณมีลิงกี่ตัว?', level: 3 , lesson: 10 },
  { en: 'HOW MANY MONKEYS DO WE HAVE?', trans: 'rao mii ling gii dtuua?', thai: 'เรามีลิงกี่ตัว?', level: 3 , lesson: 10 },
  { en: 'HOW MANY COCONUTS DO WE HAVE?', trans: 'rao mii ma-praao gii luuk?', thai: 'เรามีมะพร้าวกี่ลูก?', level: 3 , lesson: 10 },
  { en: 'HOW MUCH APPLE COST?', trans: 'aep-bpern raa-kaa taorai?', thai: 'แอปเปิ้ลราคาเท่าไร?', level: 3 , lesson: 6 },
  { en: 'WHICH DAY DO YOU PLAY MUSIC?', trans: 'kun leen don-dtrii wan nai?', thai: 'คุณเล่นดนตรีวันไหน?', level: 3 , lesson: 2 },
  { en: 'ARE YOU AVAILABLE ON SATURDAY?', trans: 'kun waang wan sao mai?', thai: 'คุณว่างวันเสาร์ไหม?', level: 3 , lesson: 2 },
  { en: 'CAN YOU GIVE ME YOUR PHONE NUMBER?', trans: 'kor ber dai-mai?', thai: 'ขอเบอร์ได้ไหม?', level: 3 , lesson: 3 },
  { en: 'WHERE ARE WE GOING?', trans: 'rao ja bpai tii nai?', thai: 'เราจะไปที่ไหน?', level: 3 , lesson: 3 },
  { en: 'AT NIGHT, I CAN WATCH TV', trans: 'dtorn kam pom duu tii-wii dai', thai: 'ตอนค่ำผมดูทีวีได้', level: 3 , lesson: 2 },
  { en: 'IN THE AFTERNOON, I READ BOOK', trans: 'dtorn baai pom aan nang-seuu', thai: 'ตอนบ่ายผมอ่านหนังสือ', level: 3 , lesson: 2 },
  { en: 'WE GO TO SCHOOL AT 8AM', trans: 'rao bpai tii rohng-rian bpaet mohng chao', thai: 'เราไปที่โรงเรียนแปดโมงเช้า', level: 3 , lesson: 2 },
  { en: 'CAN YOU BRING ME TO AIRPORT?', trans: 'kun bpai-song pom tii sa-naam-bin dai-mai?', thai: 'คุณไปส่งผมที่สนามบินได้ไหม?', level: 3 , lesson: 4 },
  { en: 'CAN YOU PICKUP ME FROM AIRPORT?', trans: 'kun maa-rap pom tii sa-naam-bin dai-mai?', thai: 'คุณมารับผมที่สนามบินได้ไหม?', level: 3 , lesson: 4 },
  { en: 'YOU COME MEET ME AT HOME, IN THE MORNING', trans: 'kun maa-jer pom tii baan, nai dtorn chao', thai: 'คุณมาเจอผมที่บ้าน ในตอนเช้า', level: 3 , lesson: 4 },
  { en: 'WE WILL GO TO THE AQUARIUM', trans: 'rao ja bpai tii pi-pit-ta-pan sat-naam', thai: 'เราจะไปที่พิพิธภัณฑ์สัตว์น้ำ', level: 3 , lesson: 4 },
  { en: 'I WANT TO GO TO BKK, DO YOU WANT TO GO TOGETHER?', trans: 'pom yaak bpai grung-tep, kun yaak bpai duai gan mai?', thai: 'ผมอยากไปกรุงเทพ คุณอยากไปด้วยกันไหม?', level: 3 , lesson: 4 },


  // ═══════════════════════════════════════════════════════════════
  // THAI FOR BEGINNERS
  // ═══════════════════════════════════════════════════════════════

  // ── Урок 1 ──────────────────────────────────────────────────────

  // -- Местоимения --
  { en: 'I, ME (MALE)', trans: 'pom', thai: 'ผม', level: 1, lesson: 1 },
  { en: 'I, ME (FEMALE, FORMAL)', trans: 'di-chan', thai: 'ดิฉัน', level: 1, lesson: 1 },
  { en: 'I, ME (FEMALE)', trans: 'chan', thai: 'ฉัน', level: 1, lesson: 1 },
  { en: 'YOU', trans: 'kun', thai: 'คุณ', level: 1, lesson: 1 },

  // -- Приветствия и частицы --
  { en: 'HELLO / GOODBYE', trans: 'sa-watdii', thai: 'สวัสดี', level: 1, lesson: 1 },
  { en: 'NAME', trans: 'cheuu', thai: 'ชื่อ', level: 1, lesson: 1 },
  { en: 'TO BE FINE', trans: 'sa-baai-dii', thai: 'สบายดี', level: 1, lesson: 1 },
  { en: 'EXCUSE ME', trans: 'kor-toht', thai: 'ขอโทษ', level: 1, lesson: 1 },
  { en: 'THANK YOU', trans: 'korp-kun', thai: 'ขอบคุณ', level: 1, lesson: 1 },
  { en: 'WHAT ABOUT...?', trans: 'la', thai: 'ล่ะ', level: 1, lesson: 1 },
  { en: 'POLITE PARTICLE (MALE)', trans: 'krap', thai: 'ครับ', level: 1, lesson: 1 },
  { en: 'POLITE PARTICLE (FEMALE, FORMAL)', trans: 'ka', thai: 'ค่ะ', level: 1, lesson: 1 },
  { en: 'POLITE PARTICLE (FEMALE)', trans: 'ka', thai: 'คะ', level: 1, lesson: 1 },

  // -- Предметы --
  { en: 'BOOK', trans: 'nang-seuu', thai: 'หนังสือ', level: 1, lesson: 1 },
  { en: 'NEWSPAPER', trans: 'nang-seuu-pim', thai: 'หนังสือพิมพ์', level: 1, lesson: 1 },
  { en: 'WATCH / CLOCK', trans: 'naa-li-gaa', thai: 'นาฬิกา', level: 1, lesson: 1 },
  { en: 'PEN', trans: 'bpaak-gaa', thai: 'ปากกา', level: 1, lesson: 1 },
  { en: 'PENCIL', trans: 'din-sor', thai: 'ดินสอ', level: 1, lesson: 1 },
  { en: 'BAG', trans: 'gra-bpao', thai: 'กระเป๋า', level: 1, lesson: 1 },
  { en: 'MAP', trans: 'paen-tii', thai: 'แผนที่', level: 1, lesson: 1 },
  { en: 'NOTEBOOK', trans: 'sa-mut', thai: 'สมุด', level: 1, lesson: 1 },

  // -- Указательные / вопросительные --
  { en: 'THIS', trans: 'nii', thai: 'นี่', level: 1, lesson: 1 },
  { en: 'THAT', trans: 'nan', thai: 'นั้น', level: 1, lesson: 1 },
  { en: 'THAT (FURTHER AWAY)', trans: 'nohn', thai: 'โน่น', level: 1, lesson: 1 },
  { en: 'WHAT', trans: 'a-rai', thai: 'อะไร', level: 1, lesson: 1 },
  { en: 'YES / CORRECT', trans: 'chai', thai: 'ใช่', level: 1, lesson: 1 },
  { en: 'NO / NOT', trans: 'mai', thai: 'ไม่', level: 1, lesson: 1 },
  { en: 'QUESTION PARTICLE', trans: 'mai', thai: 'ไหม', level: 1, lesson: 1 },
  { en: 'ALSO', trans: 'go', thai: 'ก็', level: 1, lesson: 1 },
  { en: 'OR', trans: 'reuu', thai: 'หรือ', level: 1, lesson: 1 },
  { en: 'OR (SHORT FORM)', trans: 'reu', thai: 'รึ', level: 1, lesson: 1 },
  { en: 'TO UNDERSTAND', trans: 'kao-jai', thai: 'เข้าใจ', level: 1, lesson: 1 },

  // -- Фразы --
  { en: 'HOW ARE YOU?', trans: 'sa-baai-dii-mai', thai: 'สบายดีไหม', level: 2, lesson: 1 },
  { en: 'HOW ARE YOU? (ALT)', trans: 'sa-baai-dii-reuu', thai: 'สบายดีหรือ', level: 2, lesson: 1 },
  { en: 'SAME HERE', trans: 'cheen-gan', thai: 'เช่นกัน', level: 2, lesson: 1 },
  { en: 'IT DOESN\'T MATTER', trans: 'mai-bpen-rai', thai: 'ไม่เป็นไร', level: 2, lesson: 1 },
  { en: 'RIGHT? / ISN\'T IT?', trans: 'chai-mai', thai: 'ใช่ไหม', level: 2, lesson: 1 },
  { en: 'DO YOU UNDERSTAND?', trans: 'kao-jai-mai', thai: 'เข้าใจไหม', level: 2, lesson: 1 },
  { en: 'DON\'T UNDERSTAND', trans: 'mai-kao-jai', thai: 'ไม่เข้าใจ', level: 2, lesson: 1 },
  { en: 'NICE TO MEET YOU', trans: 'yin-dii-tii-dai-ruu-jak', thai: 'ยินดีที่ได้รู้จัก', level: 3, lesson: 1 },

  // ── Урок 2 ──────────────────────────────────────────────────────

  // -- Предметы --
  { en: 'TELEPHONE', trans: 'toh-ra-sap', thai: 'โทรศัพท์', level: 1, lesson: 2 },
  { en: 'TELEVISION', trans: 'too-ra-tat', thai: 'โทรทัศน์', level: 1, lesson: 2 },
  { en: 'EYE-GLASSES', trans: 'waen-dtaa', thai: 'แว่นตา', level: 1, lesson: 2 },
  { en: 'MONEY', trans: 'ngern', thai: 'เงิน', level: 1, lesson: 2 },
  { en: 'DICTIONARY', trans: 'pot-ja-naa-nu-grom', thai: 'พจนานุกรม', level: 1, lesson: 2 },
  { en: 'PICTURE', trans: 'ruup-paap', thai: 'รูปภาพ', level: 1, lesson: 2 },
  { en: 'PAPER', trans: 'gra-daat', thai: 'กระดาษ', level: 1, lesson: 2 },
  { en: 'TABLE', trans: 'dto', thai: 'โต๊ะ', level: 1, lesson: 2 },
  { en: 'CHAIR', trans: 'gao-ii', thai: 'เก้าอี้', level: 1, lesson: 2 },
  { en: 'ROOM', trans: 'horng', thai: 'ห้อง', level: 1, lesson: 2 },
  { en: 'BEDROOM', trans: 'horng-norn', thai: 'ห้องนอน', level: 1, lesson: 2 },
  { en: 'BATHROOM', trans: 'horng-naam', thai: 'ห้องน้ำ', level: 1, lesson: 2 },
  { en: 'HOUSE', trans: 'baan', thai: 'บ้าน', level: 1, lesson: 2 },

  // -- Глаголы и предлоги --
  { en: 'TO BE SOMEWHERE / LIVE / STAY', trans: 'yuu', thai: 'อยู่', level: 1, lesson: 2 },
  { en: 'TO GET / TAKE / WANT', trans: 'ao', thai: 'เอา', level: 1, lesson: 2 },
  { en: 'CANNOT / DID NOT', trans: 'mai-dai', thai: 'ไม่ได้', level: 1, lesson: 2 },
  { en: 'IN', trans: 'nai', thai: 'ใน', level: 1, lesson: 2 },
  { en: 'ON', trans: 'bon', thai: 'บน', level: 1, lesson: 2 },
  { en: 'UNDER', trans: 'dtai', thai: 'ใต้', level: 1, lesson: 2 },
  { en: 'BETWEEN', trans: 'ra-waang', thai: 'ระหว่าง', level: 1, lesson: 2 },
  { en: 'AND / WITH', trans: 'gap', thai: 'กับ', level: 1, lesson: 2 },

  // -- Существительные --
  { en: 'TOWN / CITY', trans: 'meuang', thai: 'เมือง', level: 1, lesson: 2 },
  { en: 'PERSON', trans: 'kon', thai: 'คน', level: 1, lesson: 2 },
  { en: 'COUNTRY', trans: 'bpra-teet', thai: 'ประเทศ', level: 1, lesson: 2 },
  { en: 'LANGUAGE', trans: 'paa-saa', thai: 'ภาษา', level: 1, lesson: 2 },

  // -- Местоимения --
  { en: 'WE / US', trans: 'rao', thai: 'เรา', level: 1, lesson: 2 },
  { en: 'WE / US (GROUP)', trans: 'puak-rao', thai: 'พวกเรา', level: 1, lesson: 2 },
  { en: 'IT', trans: 'man', thai: 'มัน', level: 1, lesson: 2 },

  // -- Прилагательные --
  { en: 'EXPENSIVE', trans: 'paeng', thai: 'แพง', level: 1, lesson: 2 },
  { en: 'CHEAP / CORRECT', trans: 'tuuk', thai: 'ถูก', level: 1, lesson: 2 },
  { en: 'DIFFICULT', trans: 'yaak', thai: 'ยาก', level: 1, lesson: 2 },
  { en: 'EASY', trans: 'ngaai', thai: 'ง่าย', level: 1, lesson: 2 },
  { en: 'VERY / MANY', trans: 'maak', thai: 'มาก', level: 1, lesson: 2 },

  // -- Деньги --
  { en: 'BAHT', trans: 'baat', thai: 'บาท', level: 1, lesson: 2 },
  { en: 'DOLLAR', trans: 'don-laa', thai: 'ดอลลาร์', level: 1, lesson: 2 },
  { en: 'YEN', trans: 'yeen', thai: 'เยน', level: 1, lesson: 2 },

  // -- Направления --
  { en: 'LEFT', trans: 'saai', thai: 'ซ้าย', level: 1, lesson: 2 },
  { en: 'RIGHT', trans: 'kwaa', thai: 'ขวา', level: 1, lesson: 2 },
  { en: 'WAY / DIRECTION', trans: 'taang', thai: 'ทาง', level: 1, lesson: 2 },

  // -- Указатели и вопросы --
  { en: 'AT / RELATIVE PRONOUN', trans: 'tii', thai: 'ที่', level: 1, lesson: 2 },
  { en: 'HERE', trans: 'tii-nii', thai: 'ที่นี่', level: 1, lesson: 2 },
  { en: 'THERE', trans: 'tii-nan', thai: 'ที่นั่น', level: 1, lesson: 2 },
  { en: 'OVER THERE (FURTHER)', trans: 'tii-nohn', thai: 'ที่โน่น', level: 1, lesson: 2 },
  { en: 'WHERE', trans: 'tii-nai', thai: 'ที่ไหน', level: 1, lesson: 2 },
  { en: 'HOW MUCH', trans: 'tao-rai', thai: 'เท่าไร', level: 1, lesson: 2 },
  { en: 'THIS ONE', trans: 'an-nii', thai: 'อันนี้', level: 1, lesson: 2 },
  { en: 'THAT ONE', trans: 'an-nan', thai: 'อันนั้น', level: 1, lesson: 2 },
  { en: 'THAT ONE (FURTHER)', trans: 'an-nohn', thai: 'อันโน่น', level: 1, lesson: 2 },
  { en: 'WHICH ONE', trans: 'an-nai', thai: 'อันไหน', level: 1, lesson: 2 },

  // -- Национальности --
  { en: 'THAI PERSON', trans: 'kon-tai', thai: 'คนไทย', level: 1, lesson: 2 },
  { en: 'LAOTIAN', trans: 'kon-laao', thai: 'คนลาว', level: 1, lesson: 2 },
  { en: 'CHINESE', trans: 'kon-jiin', thai: 'คนจีน', level: 1, lesson: 2 },
  { en: 'JAPANESE', trans: 'kon-yii-bpun', thai: 'คนญี่ปุ่น', level: 1, lesson: 2 },
  { en: 'AMERICAN', trans: 'kon-a-mee-ri-gan', thai: 'คนอเมริกัน', level: 1, lesson: 2 },
  { en: 'FRENCHMAN', trans: 'kon-fa-rang-seet', thai: 'คนฝรั่งเศส', level: 1, lesson: 2 },
  { en: 'KOREAN', trans: 'kon-gao-lii', thai: 'คนเกาหลี', level: 1, lesson: 2 },
  { en: 'ENGLISHMAN', trans: 'kon-ang-grit', thai: 'คนอังกฤษ', level: 1, lesson: 2 },

  // -- Страны --
  { en: 'THAILAND', trans: 'bpra-teet-tai', thai: 'ประเทศไทย', level: 2, lesson: 2 },
  { en: 'CHINA', trans: 'bpra-teet-jiin', thai: 'ประเทศจีน', level: 2, lesson: 2 },
  { en: 'JAPAN', trans: 'bpra-teet-yii-bpun', thai: 'ประเทศญี่ปุ่น', level: 2, lesson: 2 },
  { en: 'AMERICA', trans: 'bpra-teet-a-mee-ri-gaa', thai: 'ประเทศอเมริกา', level: 2, lesson: 2 },
  { en: 'ENGLAND', trans: 'bpra-teet-ang-grit', thai: 'ประเทศอังกฤษ', level: 2, lesson: 2 },

  // -- Языки --
  { en: 'THAI LANGUAGE', trans: 'paa-saa-tai', thai: 'ภาษาไทย', level: 2, lesson: 2 },
  { en: 'ENGLISH LANGUAGE', trans: 'paa-saa-ang-grit', thai: 'ภาษาอังกฤษ', level: 2, lesson: 2 },

  // -- Фразы --
  { en: 'WHERE IS THE PHONE?', trans: 'toh-ra-sap yuu tii-nai?', thai: 'โทรศัพท์อยู่ที่ไหน', level: 2, lesson: 2 },
  { en: 'THE PHONE IS ON THE TABLE', trans: 'toh-ra-sap yuu bon dto', thai: 'โทรศัพท์อยู่บนโต๊ะ', level: 2, lesson: 2 },
  { en: 'WHERE ARE YOU?', trans: 'kun yuu tii-nai?', thai: 'คุณอยู่ที่ไหน', level: 2, lesson: 2 },
  { en: "I'M AT HOME", trans: 'pom yuu tii-baan', thai: 'ผมอยู่ที่บ้าน', level: 2, lesson: 2 },
  { en: 'WHERE IS HE?', trans: 'kao yuu tii-nai?', thai: 'เขาอยู่ที่ไหน', level: 2, lesson: 2 },
  { en: 'HE IS HERE', trans: 'kao yuu tii-nii', thai: 'เขาอยู่ที่นี่', level: 2, lesson: 2 },
  { en: 'WHERE IS THE BATHROOM?', trans: 'horng-naam yuu tii-nai?', thai: 'ห้องน้ำอยู่ที่ไหน', level: 2, lesson: 2 },
  { en: 'BATHROOM IS ON THE LEFT', trans: 'horng-naam yuu taang saai', thai: 'ห้องน้ำอยู่ทางซ้าย', level: 2, lesson: 2 },
  { en: 'WHAT NATIONALITY ARE YOU?', trans: 'kun bpen kon a-rai?', thai: 'คุณเป็นคนอะไร', level: 2, lesson: 2 },
  { en: 'I AM AMERICAN (F)', trans: 'di-chan bpen kon a-mee-ri-gan', thai: 'ดิฉันเป็นคนอเมริกัน', level: 2, lesson: 2 },
  { en: 'I AM THAI', trans: 'pom bpen kon tai', thai: 'ผมเป็นคนไทย', level: 2, lesson: 2 },
  { en: 'HOW MUCH IS THIS ONE?', trans: 'an-nii tao-rai?', thai: 'อันนี้เท่าไร', level: 2, lesson: 2 },
  { en: 'HOW MUCH IS THAT ONE?', trans: 'an-nohn tao-rai?', thai: 'อันโน่นเท่าไร', level: 2, lesson: 2 },
  { en: 'THEY ARE KOREAN', trans: 'puak-kao bpen kon gao-lii', thai: 'พวกเขาเป็นคนเกาหลี', level: 2, lesson: 2 },
  { en: 'IS THAI DIFFICULT?', trans: 'paa-saa-tai yaak mai?', thai: 'ภาษาไทยยากไหม', level: 2, lesson: 2 },
  { en: 'THAI IS NOT DIFFICULT', trans: 'paa-saa-tai mai yaak', thai: 'ภาษาไทยไม่ยาก', level: 2, lesson: 2 },
  { en: 'ENGLISH IS DIFFICULT', trans: 'paa-saa-ang-grit yaak', thai: 'ภาษาอังกฤษยาก', level: 2, lesson: 2 },
  { en: 'THIS ONE IS EXPENSIVE', trans: 'an-nii paeng', thai: 'อันนี้แพง', level: 2, lesson: 2 },
  { en: 'THIS ONE IS NOT EXPENSIVE', trans: 'an-nii mai paeng', thai: 'อันนี้ไม่แพง', level: 2, lesson: 2 },

  // -- Предложения --
  { en: 'ARE THEY JAPANESE OR KOREAN?', trans: 'puak-kao bpen kon yii-bpun reu kon gao-lii?', thai: 'พวกเขาเป็นคนญี่ปุ่นหรือคนเกาหลี', level: 3, lesson: 2 },
  { en: 'IS THE PHONE ON THE TABLE?', trans: 'toh-ra-sap yuu bon dto chai-mai?', thai: 'โทรศัพท์อยู่บนโต๊ะใช่ไหม', level: 3, lesson: 2 },
  { en: 'BOOK IS BETWEEN TABLE AND CHAIR', trans: 'nang-seuu yuu ra-waang dto gap gao-ii', thai: 'หนังสืออยู่ระหว่างโต๊ะกับเก้าอี้', level: 3, lesson: 2 },

  // ── Урок 3 ──────────────────────────────────────────────────────

  // -- Грамматические слова --
  { en: 'WILL', trans: 'ja', thai: 'จะ', level: 1, lesson: 3 },
  { en: 'CAN', trans: 'dai', thai: 'ได้', level: 1, lesson: 3 },
  { en: 'BUT', trans: 'dtae', thai: 'แต่', level: 1, lesson: 3 },
  { en: 'A LITTLE', trans: 'nit-noi', thai: 'นิดหน่อย', level: 1, lesson: 3 },
  { en: 'GOOD AT', trans: 'geeng', thai: 'เก่ง', level: 1, lesson: 3 },
  { en: 'ONE MORE TIME', trans: 'iik-tii', thai: 'อีกที', level: 1, lesson: 3 },

  // -- Скорость --
  { en: 'SLOW', trans: 'chaa', thai: 'ช้า', level: 1, lesson: 3 },
  { en: 'SLOWLY', trans: 'chaa-chaa', thai: 'ช้าๆ', level: 1, lesson: 3 },
  { en: 'FAST', trans: 'reo', thai: 'เร็ว', level: 1, lesson: 3 },
  { en: 'QUICKLY', trans: 'reo-reo', thai: 'เร็วๆ', level: 1, lesson: 3 },

  // -- Глаголы --
  { en: 'TO DO / TO MAKE', trans: 'tam', thai: 'ทำ', level: 1, lesson: 3 },
  { en: 'TO LIKE', trans: 'chorp', thai: 'ชอบ', level: 1, lesson: 3 },
  { en: 'TO EAT', trans: 'gin', thai: 'กิน', level: 1, lesson: 3 },
  { en: 'TO DRINK', trans: 'deuum', thai: 'ดื่ม', level: 1, lesson: 3 },
  { en: 'TO WATCH', trans: 'duu', thai: 'ดู', level: 1, lesson: 3 },
  { en: 'TO SPEAK', trans: 'puut', thai: 'พูด', level: 1, lesson: 3 },
  { en: 'TO READ', trans: 'aan', thai: 'อ่าน', level: 1, lesson: 3 },
  { en: 'TO WRITE', trans: 'kian', thai: 'เขียน', level: 1, lesson: 3 },
  { en: 'TO STUDY', trans: 'rian', thai: 'เรียน', level: 1, lesson: 3 },
  { en: 'TO TEACH', trans: 'sorn', thai: 'สอน', level: 1, lesson: 3 },
  { en: 'TO WORK', trans: 'tam-ngaan', thai: 'ทำงาน', level: 1, lesson: 3 },
  { en: 'TO SLEEP', trans: 'norn', thai: 'นอน', level: 1, lesson: 3 },
  { en: 'TO WAKE UP', trans: 'dteuun', thai: 'ตื่น', level: 1, lesson: 3 },
  { en: 'TO GO', trans: 'bpai', thai: 'ไป', level: 1, lesson: 3 },
  { en: 'TO COME', trans: 'maa', thai: 'มา', level: 1, lesson: 3 },

  // -- Места --
  { en: 'TEMPLE', trans: 'wat', thai: 'วัด', level: 1, lesson: 3 },
  { en: 'CHURCH', trans: 'boht', thai: 'โบสถ์', level: 1, lesson: 3 },
  { en: 'MARKET', trans: 'dta-laat', thai: 'ตลาด', level: 1, lesson: 3 },
  { en: 'FACTORY', trans: 'rohng-ngaan', thai: 'โรงงาน', level: 1, lesson: 3 },
  { en: 'SCHOOL', trans: 'rohng-rian', thai: 'โรงเรียน', level: 1, lesson: 3 },
  { en: 'HOSPITAL', trans: 'rohng-pa-yaa-baan', thai: 'โรงพยาบาล', level: 1, lesson: 3 },
  { en: 'BANK', trans: 'ta-naa-kaan', thai: 'ธนาคาร', level: 1, lesson: 3 },
  { en: 'POST OFFICE', trans: 'bprai-sa-nii', thai: 'ไปรษณีย์', level: 1, lesson: 3 },
  { en: 'UNIVERSITY', trans: 'ma-haa-wit-ta-yaa-lai', thai: 'มหาวิทยาลัย', level: 1, lesson: 3 },
  { en: 'AIRPORT', trans: 'sa-naam-bin', thai: 'สนามบิน', level: 1, lesson: 3 },
  { en: 'RESTAURANT', trans: 'raan aa-haan', thai: 'ร้านอาหาร', level: 1, lesson: 3 },
  { en: 'HOTEL', trans: 'rohng-raem', thai: 'โรงแรม', level: 2, lesson: 3 },
  { en: 'MOVIE THEATER', trans: 'rohng-nang', thai: 'โรงหนัง', level: 2, lesson: 3 },
  { en: 'CAR', trans: 'rot-yon', thai: 'รถยนต์', level: 1, lesson: 3 },

  // -- Еда и напитки --
  { en: 'FOOD', trans: 'aa-haan', thai: 'อาหาร', level: 1, lesson: 3 },
  { en: 'RICE', trans: 'kaao', thai: 'ข้าว', level: 1, lesson: 3 },
  { en: 'NOODLES', trans: 'guai-dtiao', thai: 'ก๋วยเตี๋ยว', level: 1, lesson: 3 },
  { en: 'EGG NOODLE', trans: 'ba-mii', thai: 'บะหมี่', level: 1, lesson: 3 },
  { en: 'SNACK', trans: 'ka-nom', thai: 'ขนม', level: 1, lesson: 3 },
  { en: 'DESSERT', trans: 'korng-waan', thai: 'ของหวาน', level: 1, lesson: 3 },
  { en: 'WATER', trans: 'naam', thai: 'น้ำ', level: 1, lesson: 3 },
  { en: 'ICE', trans: 'naam-keng', thai: 'น้ำแข็ง', level: 1, lesson: 3 },
  { en: 'ORANGE JUICE', trans: 'naam-som', thai: 'น้ำส้ม', level: 1, lesson: 3 },
  { en: 'COFFEE', trans: 'gaa-fae', thai: 'กาแฟ', level: 1, lesson: 3 },
  { en: 'TEA', trans: 'chaa', thai: 'ชา', level: 1, lesson: 3 },
  { en: 'BEER', trans: 'bia', thai: 'เบียร์', level: 1, lesson: 3 },
  { en: 'THAI FOOD', trans: 'aa-haan tai', thai: 'อาหารไทย', level: 2, lesson: 3 },
  { en: 'WESTERN FOOD', trans: 'aa-haan fa-rang', thai: 'อาหารฝรั่ง', level: 2, lesson: 3 },
  { en: 'CHINESE FOOD', trans: 'aa-haan jiin', thai: 'อาหารจีน', level: 2, lesson: 3 },
  { en: 'JAPANESE FOOD', trans: 'aa-haan yii-bpun', thai: 'อาหารญี่ปุ่น', level: 2, lesson: 3 },
  { en: 'TO HAVE A MEAL', trans: 'gin-kaao', thai: 'กินข้าว', level: 2, lesson: 3 },
  { en: 'BREAKFAST', trans: 'aa-haan-chao', thai: 'อาหารเช้า', level: 2, lesson: 3 },
  { en: 'LUNCH', trans: 'aa-haan-tiang', thai: 'อาหารเที่ยง', level: 2, lesson: 3 },
  { en: 'DINNER', trans: 'kaao-yen', thai: 'ข้าวเย็น', level: 2, lesson: 3 },

  // -- Цвета --
  { en: 'COLOR', trans: 'sii', thai: 'สี', level: 1, lesson: 3 },
  { en: 'BLACK', trans: 'sii dam', thai: 'สีดำ', level: 2, lesson: 3 },
  { en: 'WHITE', trans: 'sii kaao', thai: 'สีขาว', level: 2, lesson: 3 },
  { en: 'RED', trans: 'sii daeng', thai: 'สีแดง', level: 2, lesson: 3 },
  { en: 'GREEN', trans: 'sii kiao', thai: 'สีเขียว', level: 2, lesson: 3 },
  { en: 'LIGHT BLUE', trans: 'sii faa', thai: 'สีฟ้า', level: 2, lesson: 3 },
  { en: 'DARK BLUE', trans: 'sii naam-ngern', thai: 'สีน้ำเงิน', level: 2, lesson: 3 },
  { en: 'BROWN', trans: 'sii naam-dtaan', thai: 'สีน้ำตาล', level: 2, lesson: 3 },
  { en: 'YELLOW', trans: 'sii leuang', thai: 'สีเหลือง', level: 2, lesson: 3 },
  { en: 'PINK', trans: 'sii chompuu', thai: 'สีชมพู', level: 2, lesson: 3 },
  { en: 'PURPLE', trans: 'sii muuang', thai: 'สีม่วง', level: 2, lesson: 3 },
  { en: 'ORANGE', trans: 'sii som', thai: 'สีส้ม', level: 2, lesson: 3 },
  { en: 'GREY', trans: 'sii tao', thai: 'สีเทา', level: 2, lesson: 3 },

  // ── Урок 4 ──────────────────────────────────────────────────────

  // -- Время --
  { en: 'TIME', trans: 'wee-laa', thai: 'เวลา', level: 1, lesson: 4 },
  { en: 'HOUR', trans: 'chuua-mohng', thai: 'ชั่วโมง', level: 1, lesson: 4 },
  { en: 'MINUTE', trans: 'naa-tii', thai: 'นาที', level: 1, lesson: 4 },
  { en: 'SECOND', trans: 'wi-naa-tii', thai: 'วินาที', level: 1, lesson: 4 },
  { en: 'EXACTLY', trans: 'dtrong', thai: 'ตรง', level: 1, lesson: 4 },
  { en: 'HALF', trans: 'kreung', thai: 'ครึ่ง', level: 1, lesson: 4 },
  { en: 'ALMOST', trans: 'guuap', thai: 'เกือบ', level: 1, lesson: 4 },
  { en: 'PAST (more than)', trans: 'gwaa', thai: 'กว่า', level: 1, lesson: 4 },
  { en: 'ABOUT / APPROXIMATELY', trans: 'bpra-maan', thai: 'ประมาณ', level: 1, lesson: 4 },
  { en: 'MORE / AGAIN', trans: 'iik', thai: 'อีก', level: 1, lesson: 4 },
  { en: 'LATE', trans: 'saai', thai: 'สาย', level: 1, lesson: 4 },
  { en: 'BEFORE', trans: 'gorn', thai: 'ก่อน', level: 1, lesson: 4 },
  { en: 'AFTER / BEHIND', trans: 'lang', thai: 'หลัง', level: 1, lesson: 4 },
  { en: 'FROM', trans: 'jaak', thai: 'จาก', level: 1, lesson: 4 },
  { en: 'FROM (TIME)', trans: 'dtang-dtae', thai: 'ตั้งแต่', level: 1, lesson: 4 },
  { en: 'TO / UNTIL', trans: 'teung', thai: 'ถึง', level: 1, lesson: 4 },
  { en: 'WHEN?', trans: 'meua-rai', thai: 'เมื่อไหร่', level: 1, lesson: 4 },
  { en: 'JUST NOW', trans: 'meua-gii', thai: 'เมื่อกี้', level: 1, lesson: 4 },
  { en: 'NOON', trans: 'tiang', thai: 'เที่ยง', level: 1, lesson: 4 },
  { en: 'NIGHT', trans: 'kam', thai: 'ค่ำ', level: 1, lesson: 4 },
  { en: 'AT (TIME PERIOD)', trans: 'dtorn', thai: 'ตอน', level: 1, lesson: 4 },
  { en: 'NOW', trans: 'dtorn-nii', thai: 'ตอนนี้', level: 1, lesson: 4 },

  // -- Время суток --
  { en: 'IN THE MORNING', trans: 'dtorn-chao', thai: 'ตอนเช้า', level: 2, lesson: 4 },
  { en: 'AT NOON', trans: 'dtorn-tiang', thai: 'ตอนเที่ยง', level: 2, lesson: 4 },
  { en: 'IN THE AFTERNOON', trans: 'dtorn-baai', thai: 'ตอนบ่าย', level: 2, lesson: 4 },
  { en: 'IN THE EVENING', trans: 'dtorn-yen', thai: 'ตอนเย็น', level: 2, lesson: 4 },
  { en: 'AT NIGHT', trans: 'dtorn-kam', thai: 'ตอนค่ำ', level: 2, lesson: 4 },
  { en: 'FIVE MORE MINUTES', trans: 'iik-haa-naa-tii', thai: 'อีกห้านาที', level: 2, lesson: 4 },
  { en: 'JUST NOW (LONG FORM)', trans: 'meua-gii-nii', thai: 'เมื่อกี้นี้', level: 2, lesson: 4 },

  // -- Часы --
  { en: '1:00 AM', trans: 'dtii-neung', thai: 'ตีหนึ่ง', level: 2, lesson: 4 },
  { en: '2:00 AM', trans: 'dtii-sorng', thai: 'ตีสอง', level: 2, lesson: 4 },
  { en: '3:00 AM', trans: 'dtii-saam', thai: 'ตีสาม', level: 2, lesson: 4 },
  { en: '4:00 AM', trans: 'dtii-sii', thai: 'ตีสี่', level: 2, lesson: 4 },
  { en: '5:00 AM', trans: 'dtii-haa', thai: 'ตีห้า', level: 2, lesson: 4 },
  { en: '6:00 AM', trans: 'hok-mohng-chao', thai: 'หกโมงเช้า', level: 2, lesson: 4 },
  { en: '7:00 AM', trans: 'jet-mohng-chao', thai: 'เจ็ดโมงเช้า', level: 2, lesson: 4 },
  { en: '8:00 AM', trans: 'bpaet-mohng-chao', thai: 'แปดโมงเช้า', level: 2, lesson: 4 },
  { en: '9:00 AM', trans: 'gao-mohng-chao', thai: 'เก้าโมงเช้า', level: 2, lesson: 4 },
  { en: '10:00 AM', trans: 'sip-mohng-chao', thai: 'สิบโมงเช้า', level: 2, lesson: 4 },
  { en: '11:00 AM', trans: 'sip-et-mohng-chao', thai: 'สิบเอ็ดโมงเช้า', level: 2, lesson: 4 },
  { en: '12:00 PM (NOON)', trans: 'tiang-wan', thai: 'เที่ยงวัน', level: 2, lesson: 4 },
  { en: '1:00 PM', trans: 'baai-neung', thai: 'บ่ายหนึ่ง', level: 2, lesson: 4 },
  { en: '2:00 PM', trans: 'baai-sorng', thai: 'บ่ายสอง', level: 2, lesson: 4 },
  { en: '3:00 PM', trans: 'baai-saam', thai: 'บ่ายสาม', level: 2, lesson: 4 },
  { en: '4:00 PM', trans: 'baai-sii', thai: 'บ่ายสี่', level: 2, lesson: 4 },
  { en: '5:00 PM', trans: 'haa-mohng-yen', thai: 'ห้าโมงเย็น', level: 2, lesson: 4 },
  { en: '6:00 PM', trans: 'hok-mohng-yen', thai: 'หกโมงเย็น', level: 2, lesson: 4 },
  { en: '7:00 PM', trans: 'neung-tum', thai: 'หนึ่งทุ่ม', level: 2, lesson: 4 },
  { en: '8:00 PM', trans: 'sorng-tum', thai: 'สองทุ่ม', level: 2, lesson: 4 },
  { en: '9:00 PM', trans: 'saam-tum', thai: 'สามทุ่ม', level: 2, lesson: 4 },
  { en: '10:00 PM', trans: 'sii-tum', thai: 'สี่ทุ่ม', level: 2, lesson: 4 },
  { en: '11:00 PM', trans: 'haa-tum', thai: 'ห้าทุ่ม', level: 2, lesson: 4 },
  { en: '15:00 (24H)', trans: 'sip-haa-naa-li-gaa', thai: 'สิบห้านาฬิกา', level: 2, lesson: 4 },

  // ── Урок 5 ──────────────────────────────────────────────────────

  // -- Дни недели --
  { en: 'DAY', trans: 'wan', thai: 'วัน', level: 1, lesson: 5 },
  { en: 'SUNDAY', trans: 'wan-aa-tit', thai: 'วันอาทิตย์', level: 1, lesson: 5 },
  { en: 'MONDAY', trans: 'wan-jan', thai: 'วันจันทร์', level: 1, lesson: 5 },
  { en: 'TUESDAY', trans: 'wan-ang-kaan', thai: 'วันอังคาร', level: 1, lesson: 5 },
  { en: 'WEDNESDAY', trans: 'wan-put', thai: 'วันพุธ', level: 1, lesson: 5 },
  { en: 'THURSDAY', trans: 'wan-pa-reu-hat', thai: 'วันพฤหัส', level: 1, lesson: 5 },
  { en: 'FRIDAY', trans: 'wan-suk', thai: 'วันศุกร์', level: 1, lesson: 5 },
  { en: 'SATURDAY', trans: 'wan-sao', thai: 'วันเสาร์', level: 1, lesson: 5 },
  { en: 'HOLIDAY', trans: 'wan-yut', thai: 'วันหยุด', level: 1, lesson: 5 },
  { en: 'WEEKEND', trans: 'sao-aa-tit', thai: 'เสาร์อาทิตย์', level: 1, lesson: 5 },
  { en: 'WEEK', trans: 'aa-tit', thai: 'อาทิตย์', level: 1, lesson: 5 },
  { en: 'MONTH', trans: 'deuan', thai: 'เดือน', level: 1, lesson: 5 },
  { en: 'YEAR', trans: 'bpii', thai: 'ปี', level: 1, lesson: 5 },

  // -- Месяцы (краткая форма) --
  { en: 'JANUARY (SHORT)', trans: 'ma-ga-raa', thai: 'มกรา', level: 1, lesson: 5 },
  { en: 'FEBRUARY (SHORT)', trans: 'gum-paa', thai: 'กุมภา', level: 1, lesson: 5 },
  { en: 'MARCH (SHORT)', trans: 'mii-naa', thai: 'มีนา', level: 1, lesson: 5 },
  { en: 'APRIL (SHORT)', trans: 'mee-saa', thai: 'เมษา', level: 1, lesson: 5 },
  { en: 'MAY (SHORT)', trans: 'preut-sa-paa', thai: 'พฤษภา', level: 1, lesson: 5 },
  { en: 'JUNE (SHORT)', trans: 'mi-tu-naa', thai: 'มิถุนา', level: 1, lesson: 5 },
  { en: 'JULY (SHORT)', trans: 'ga-ra-ga-daa', thai: 'กรกฎา', level: 1, lesson: 5 },
  { en: 'AUGUST (SHORT)', trans: 'sing-haa', thai: 'สิงหา', level: 1, lesson: 5 },
  { en: 'SEPTEMBER (SHORT)', trans: 'gan-yaa', thai: 'กันยา', level: 1, lesson: 5 },
  { en: 'OCTOBER (SHORT)', trans: 'dtu-laa', thai: 'ตุลา', level: 1, lesson: 5 },
  { en: 'NOVEMBER (SHORT)', trans: 'preut-sa-ji-gaa', thai: 'พฤศจิกา', level: 1, lesson: 5 },
  { en: 'DECEMBER (SHORT)', trans: 'tan-waa', thai: 'ธันวา', level: 1, lesson: 5 },

  // -- Относительное время --
  { en: 'TODAY', trans: 'wan-nii', thai: 'วันนี้', level: 1, lesson: 5 },
  { en: 'YESTERDAY', trans: 'meua-waan-nii', thai: 'เมื่อวานนี้', level: 1, lesson: 5 },
  { en: 'TOMORROW', trans: 'prung-nii', thai: 'พรุ่งนี้', level: 1, lesson: 5 },
  { en: 'EVERY', trans: 'tuk', thai: 'ทุก', level: 1, lesson: 5 },
  { en: 'THIS WEEK', trans: 'aa-tit-nii', thai: 'อาทิตย์นี้', level: 2, lesson: 5 },
  { en: 'LAST WEEK', trans: 'aa-tit-tii-laeo', thai: 'อาทิตย์ที่แล้ว', level: 2, lesson: 5 },
  { en: 'NEXT WEEK', trans: 'aa-tit-naa', thai: 'อาทิตย์หน้า', level: 2, lesson: 5 },
  { en: 'LAST MONTH', trans: 'deuan-tii-laeo', thai: 'เดือนที่แล้ว', level: 2, lesson: 5 },
  { en: 'THIS MONTH', trans: 'deuan-nii', thai: 'เดือนนี้', level: 2, lesson: 5 },
  { en: 'NEXT MONTH', trans: 'deuan-naa', thai: 'เดือนหน้า', level: 2, lesson: 5 },
  { en: 'THIS YEAR', trans: 'bpii-nii', thai: 'ปีนี้', level: 2, lesson: 5 },
  { en: 'LAST YEAR', trans: 'bpii-tii-laeo', thai: 'ปีที่แล้ว', level: 2, lesson: 5 },
  { en: 'NEXT YEAR', trans: 'bpii-naa', thai: 'ปีหน้า', level: 2, lesson: 5 },
  { en: 'EVERY DAY', trans: 'tuk-wan', thai: 'ทุกวัน', level: 2, lesson: 5 },
  { en: 'EVERY WEEK', trans: 'tuk-aa-tit', thai: 'ทุกอาทิตย์', level: 2, lesson: 5 },
  { en: 'EVERY MONTH', trans: 'tuk-deuan', thai: 'ทุกเดือน', level: 2, lesson: 5 },
  { en: 'EVERY YEAR', trans: 'tuk-bpii', thai: 'ทุกปี', level: 2, lesson: 5 },

  // -- Время суток --
  { en: 'MORNING', trans: 'chao', thai: 'เช้า', level: 1, lesson: 5 },
  { en: 'COLD / EVENING', trans: 'yen', thai: 'เย็น', level: 1, lesson: 5 },
  { en: 'NIGHT', trans: 'keuun', thai: 'คืน', level: 1, lesson: 5 },

  // -- Люди и социальное --
  { en: 'LOVED ONE', trans: 'faen', thai: 'แฟน', level: 1, lesson: 5 },
  { en: 'FRIEND', trans: 'peuan', thai: 'เพื่อน', level: 1, lesson: 5 },
  { en: 'FREE / AVAILABLE', trans: 'waang', thai: 'ว่าง', level: 1, lesson: 5 },
  { en: 'BUSY', trans: 'yung', thai: 'ยุ่ง', level: 1, lesson: 5 },
  { en: 'MUST / HAVE TO', trans: 'dtorng', thai: 'ต้อง', level: 1, lesson: 5 },
  { en: 'TO HAVE / THERE IS', trans: 'mii', thai: 'มี', level: 1, lesson: 5 },
  { en: 'TO RETURN / GO BACK', trans: 'glap', thai: 'กลับ', level: 1, lesson: 5 },
  { en: 'TO WAKE SOMEONE UP', trans: 'bpluk', thai: 'ปลุก', level: 1, lesson: 5 },
  { en: 'TO TAKE A TRIP', trans: 'bpai-tiao', thai: 'ไปเที่ยว', level: 1, lesson: 5 },
  { en: 'BY ONESELF', trans: 'kon-diao', thai: 'คนเดียว', level: 2, lesson: 5 },
  { en: 'TO GO TOGETHER', trans: 'bpai-duai-gan', thai: 'ไปด้วยกัน', level: 2, lesson: 5 },
  { en: 'TO COME TO PICK UP', trans: 'maa-rap', thai: 'มารับ', level: 2, lesson: 5 },
  { en: 'TO GO TO PICK UP', trans: 'bpai-rap', thai: 'ไปรับ', level: 2, lesson: 5 },
  { en: 'HAVE A DATE / APPOINTMENT', trans: 'mii-nat', thai: 'มีนัด', level: 2, lesson: 5 },
  { en: 'SEE YOU', trans: 'joo-gan', thai: 'เจอกัน', level: 2, lesson: 5 },

  // ── Урок 7 ──────────────────────────────────────────────────────

  // -- Грамматические слова --
  { en: 'WHO', trans: 'krai', thai: 'ใคร', level: 1, lesson: 7 },
  { en: 'OF / POSSESSIVE', trans: 'korng', thai: 'ของ', level: 1, lesson: 7 },
  { en: 'WHOSE', trans: 'korng-krai', thai: 'ของใคร', level: 2, lesson: 7 },
  { en: 'CAN / TO BE', trans: 'bpen', thai: 'เป็น', level: 1, lesson: 7 },
  { en: 'OUT', trans: 'ook', thai: 'ออก', level: 1, lesson: 7 },
  { en: 'ON TIME / KEEP UP', trans: 'tan', thai: 'ทัน', level: 1, lesson: 7 },
  { en: 'TRUE / REALLY', trans: 'jing', thai: 'จริง', level: 1, lesson: 7 },
  { en: 'REALLY (EMPHATIC)', trans: 'jing-jing', thai: 'จริงๆ', level: 1, lesson: 7 },
  { en: 'INCORRECT', trans: 'pit', thai: 'ผิด', level: 1, lesson: 7 },

  // -- Глаголы восприятия и мышления --
  { en: 'TO KNOW', trans: 'ruu', thai: 'รู้', level: 1, lesson: 7 },
  { en: 'TO KNOW (PERSON)', trans: 'ruu-jak', thai: 'รู้จัก', level: 1, lesson: 7 },
  { en: 'TO THINK', trans: 'kit', thai: 'คิด', level: 1, lesson: 7 },
  { en: 'TO MISS / THINK ABOUT', trans: 'kit-teung', thai: 'คิดถึง', level: 2, lesson: 7 },
  { en: 'TO THINK THAT', trans: 'kit-waa', thai: 'คิดว่า', level: 2, lesson: 7 },
  { en: 'TO LOOK', trans: 'morng', thai: 'มอง', level: 1, lesson: 7 },
  { en: 'TO SEE / CAN SEE', trans: 'morng-hen', thai: 'มองเห็น', level: 2, lesson: 7 },
  { en: 'CAN\'T SEE', trans: 'morng-mai-hen', thai: 'มองไม่เห็น', level: 2, lesson: 7 },
  { en: 'TO HEAR / CAN HEAR', trans: 'dai-yin', thai: 'ได้ยิน', level: 1, lesson: 7 },
  { en: 'CAN\'T HEAR', trans: 'mai-dai-yin', thai: 'ไม่ได้ยิน', level: 2, lesson: 7 },
  { en: 'TO MEMORIZE', trans: 'jam', thai: 'จำ', level: 1, lesson: 7 },
  { en: 'TO REMEMBER', trans: 'jam-dai', thai: 'จำได้', level: 2, lesson: 7 },
  { en: 'CAN\'T REMEMBER', trans: 'jam-mai-dai', thai: 'จำไม่ได้', level: 2, lesson: 7 },
  { en: 'TO FINISH', trans: 'set', thai: 'เสร็จ', level: 1, lesson: 7 },
  { en: 'TO SWIM', trans: 'waai-naam', thai: 'ว่ายน้ำ', level: 1, lesson: 7 },
  { en: 'TO FALL ASLEEP', trans: 'norn-lap', thai: 'นอนหลับ', level: 2, lesson: 7 },

  // -- Состояния --
  { en: 'TIRED', trans: 'neuai', thai: 'เหนื่อย', level: 1, lesson: 7 },
  { en: 'SLEEPY', trans: 'nguang', thai: 'ง่วง', level: 1, lesson: 7 },
  { en: 'LOUD', trans: 'dang', thai: 'ดัง', level: 1, lesson: 7 },


  // -- Вкус --
  { en: 'DELICIOUS', trans: 'a-roi', thai: 'อร่อย', level: 1, lesson: 7 },
  { en: 'SWEET', trans: 'waan', thai: 'หวาน', level: 1, lesson: 7 },
  { en: 'SALTY', trans: 'kem', thai: 'เค็ม', level: 1, lesson: 7 },
  { en: 'TASTELESS', trans: 'jeuut', thai: 'จืด', level: 1, lesson: 7 },
  { en: 'SOUR', trans: 'bpriao', thai: 'เปรี้ยว', level: 1, lesson: 7 },
  { en: 'SPICY', trans: 'pet', thai: 'เผ็ด', level: 1, lesson: 7 },

  // ── Урок 10 ─────────────────────────────────────────────────────

  // -- Сравнение --
  { en: 'MOST', trans: 'tii-sut', thai: 'ที่สุด', level: 1, lesson: 10 },

  // -- Размер и форма --
  { en: 'BIG', trans: 'yai', thai: 'ใหญ่', level: 1, lesson: 10 },
  { en: 'BIG / GROWN-UP', trans: 'dtoh', thai: 'โต', level: 1, lesson: 10 },
  { en: 'SMALL', trans: 'lek', thai: 'เล็ก', level: 1, lesson: 10 },
  { en: 'FAT', trans: 'uan', thai: 'อ้วน', level: 1, lesson: 10 },
  { en: 'THIN (LEAN)', trans: 'porm', thai: 'ผอม', level: 1, lesson: 10 },
  { en: 'THICK', trans: 'naa', thai: 'หนา', level: 1, lesson: 10 },
  { en: 'THIN (FLAT)', trans: 'baang', thai: 'บาง', level: 1, lesson: 10 },
  { en: 'TALL / HIGH', trans: 'suung', thai: 'สูง', level: 1, lesson: 10 },
  { en: 'SHORT (HEIGHT)', trans: 'dtia', thai: 'เตี้ย', level: 1, lesson: 10 },
  { en: 'LOW', trans: 'dtam', thai: 'ต่ำ', level: 1, lesson: 10 },
  { en: 'LONG', trans: 'yaao', thai: 'ยาว', level: 1, lesson: 10 },
  { en: 'SHORT (LENGTH)', trans: 'san', thai: 'สั้น', level: 1, lesson: 10 },
  { en: 'HEAVY', trans: 'nak', thai: 'หนัก', level: 1, lesson: 10 },
  { en: 'LIGHT (WEIGHT)', trans: 'bao', thai: 'เบา', level: 1, lesson: 10 },
  { en: 'WIDE', trans: 'gwaang', thai: 'กว้าง', level: 1, lesson: 10 },
  { en: 'NARROW', trans: 'kaep', thai: 'แคบ', level: 1, lesson: 10 },

  // -- Температура и расстояние --
  { en: 'HOT', trans: 'rorn', thai: 'ร้อน', level: 1, lesson: 10 },
  { en: 'COLD (WEATHER)', trans: 'naao', thai: 'หนาว', level: 1, lesson: 10 },
  { en: 'FAR', trans: 'glai', thai: 'ไกล', level: 1, lesson: 10 },
  { en: 'NEAR', trans: 'glai', thai: 'ใกล้', level: 1, lesson: 10 },

  // -- Количество и возраст --
  { en: 'LITTLE / FEW', trans: 'noi', thai: 'น้อย', level: 1, lesson: 10 },
  { en: 'OLD (PEOPLE)', trans: 'gae', thai: 'แก่', level: 1, lesson: 10 },
  { en: 'YOUNG', trans: 'aa-yu-noi', thai: 'อายุน้อย', level: 2, lesson: 10 },
  { en: 'NEW', trans: 'mai', thai: 'ใหม่', level: 1, lesson: 10 },
  { en: 'OLD (THINGS)', trans: 'gao', thai: 'เก่า', level: 1, lesson: 10 },

  // -- Прилагательные --
  { en: 'STRONG', trans: 'kaeng-raeng', thai: 'แข็งแรง', level: 1, lesson: 10 },
  { en: 'WEAK', trans: 'orn-ae', thai: 'อ่อนแอ', level: 1, lesson: 10 },
  { en: 'INTELLIGENT', trans: 'cha-laat', thai: 'ฉลาด', level: 1, lesson: 10 },
  { en: 'STUPID', trans: 'ngoh', thai: 'โง่', level: 1, lesson: 10 },
  { en: 'BRIGHT / LIGHT', trans: 'sa-waang', thai: 'สว่าง', level: 1, lesson: 10 },
  { en: 'DARK', trans: 'meuut', thai: 'มืด', level: 1, lesson: 10 },
  { en: 'DANGEROUS', trans: 'an-dta-raai', thai: 'อันตราย', level: 1, lesson: 10 },
  { en: 'SAFE', trans: 'bplort-pai', thai: 'ปลอดภัย', level: 1, lesson: 10 },
  { en: 'AWFUL / TERRIFYING', trans: 'naa-gluua', thai: 'น่ากลัว', level: 1, lesson: 10 },
  { en: 'INTERESTING', trans: 'naa-son-jai', thai: 'น่าสนใจ', level: 1, lesson: 10 },
  { en: 'BORING', trans: 'naa-beua', thai: 'น่าเบื่อ', level: 1, lesson: 10 },
  { en: 'CONVENIENT', trans: 'sa-duak', thai: 'สะดวก', level: 1, lesson: 10 },
  { en: 'COMFORTABLE', trans: 'sa-baai', thai: 'สบาย', level: 1, lesson: 10 },
  { en: 'CLEAN', trans: 'sa-aat', thai: 'สะอาด', level: 1, lesson: 10 },
  { en: 'DIRTY', trans: 'sok-ga-bprok', thai: 'สกปรก', level: 1, lesson: 10 },
  { en: 'DILIGENT', trans: 'ka-yan', thai: 'ขยัน', level: 1, lesson: 10 },
  { en: 'LAZY', trans: 'kii-giat', thai: 'ขี้เกียจ', level: 1, lesson: 10 },
  { en: 'RICH', trans: 'ruai', thai: 'รวย', level: 1, lesson: 10 },
  { en: 'POOR', trans: 'jon', thai: 'จน', level: 1, lesson: 10 },
  { en: 'BEAUTIFUL / PRETTY', trans: 'suai', thai: 'สวย', level: 1, lesson: 10 },
  { en: 'CUTE', trans: 'naa-rak', thai: 'น่ารัก', level: 1, lesson: 10 },
  { en: 'HANDSOME', trans: 'ruup-lor', thai: 'รูปหล่อ', level: 1, lesson: 10 },
  { en: 'FAMOUS', trans: 'mii-cheuu-siang', thai: 'มีชื่อเสียง', level: 1, lesson: 10 },
  { en: 'IMPORTANT', trans: 'sam-kan', thai: 'สำคัญ', level: 1, lesson: 10 },
  { en: 'SPECIAL', trans: 'pi-seet', thai: 'พิเศษ', level: 1, lesson: 10 },

  // -- Характер --
  { en: 'STINGY / THRIFTY', trans: 'kii-niao', thai: 'ขี้เหนียว', level: 2, lesson: 10 },
  { en: 'GLAD', trans: 'dii-jai', thai: 'ดีใจ', level: 1, lesson: 10 },
  { en: 'KIND', trans: 'jai-dii', thai: 'ใจดี', level: 1, lesson: 10 },
  { en: 'GENEROUS', trans: 'jai-gwaang', thai: 'ใจกว้าง', level: 2, lesson: 10 },
  { en: 'CALM', trans: 'jai-yen', thai: 'ใจเย็น', level: 2, lesson: 10 },
  { en: 'IMPATIENT', trans: 'jai-rorn', thai: 'ใจร้อน', level: 2, lesson: 10 },
  { en: 'BAD (MORALLY)', trans: 'leo', thai: 'เลว', level: 1, lesson: 10 },
  { en: 'QUIET', trans: 'ngiap', thai: 'เงียบ', level: 1, lesson: 10 },
  { en: 'TO ASK FOR STH', trans: 'kor', thai: 'ขอ', level: 1, lesson: 10 },
  { en: 'TO SMOKE', trans: 'suup', thai: 'สูบ', level: 1, lesson: 10 },
  { en: 'TO HATE', trans: 'gliat', thai: 'เกลียด', level: 1, lesson: 10 },
  { en: 'TO LIE', trans: 'goh-hok', thai: 'โกหก', level: 1, lesson: 10 },

  // -- Слова-сравнения --
  { en: 'EARTH / WORLD', trans: 'lohk', thai: 'โลก', level: 1, lesson: 10 },
  { en: 'PRICE', trans: 'raa-kaa', thai: 'ราคา', level: 1, lesson: 10 },
  { en: 'EACH OTHER', trans: 'gan', thai: 'กัน', level: 1, lesson: 10 },
  { en: 'SAME / TO LOOK ALIKE', trans: 'meuan-gan', thai: 'เหมือนกัน', level: 1, lesson: 10 },
  { en: 'TO LOOK ALIKE', trans: 'klaai-gan', thai: 'คล้ายกัน', level: 2, lesson: 10 },
  { en: 'EQUAL', trans: 'tao-gan', thai: 'เท่ากัน', level: 1, lesson: 10 },

  // -- Фрукты --
  { en: 'FRUIT', trans: 'pon-la-mai', thai: 'ผลไม้', level: 1, lesson: 10 },
  { en: 'BANANA', trans: 'gluai', thai: 'กล้วย', level: 1, lesson: 10 },
  { en: 'MANGO', trans: 'ma-muang', thai: 'มะม่วง', level: 1, lesson: 10 },
  { en: 'DURIAN', trans: 'tu-rian', thai: 'ทุเรียน', level: 1, lesson: 10 },
  { en: 'MANGOSTEEN', trans: 'mang-kut', thai: 'มังคุด', level: 1, lesson: 10 },
  { en: 'RAMBUTAN', trans: 'ngor', thai: 'เงาะ', level: 1, lesson: 10 },
  { en: 'LONGAN', trans: 'lam-yai', thai: 'ลำไย', level: 1, lesson: 10 },
  { en: 'PAPAYA', trans: 'ma-la-gor', thai: 'มะละกอ', level: 1, lesson: 10 },
  { en: 'APPLE', trans: 'aep-bpern', thai: 'แอปเปิ้ล', level: 1, lesson: 10 },
  { en: 'ROSE APPLE', trans: 'chom-puu', thai: 'ชมพู่', level: 1, lesson: 10 },
  { en: 'SUGAR APPLE', trans: 'noi-naa', thai: 'น้อยหน่า', level: 2, lesson: 10 },
  { en: 'ORANGE', trans: 'som', thai: 'ส้ม', level: 1, lesson: 10 },
  { en: 'PINEAPPLE', trans: 'sap-bpa-rot', thai: 'สับปะรด', level: 1, lesson: 10 },
  { en: 'WATERMELON', trans: 'dtaeng-moh', thai: 'แตงโม', level: 1, lesson: 10 },
  { en: 'COCONUT', trans: 'ma-praao', thai: 'มะพร้าว', level: 1, lesson: 10 },
  { en: 'JACKFRUIT', trans: 'ka-nun', thai: 'ขนุน', level: 1, lesson: 10 },
  { en: 'POMELO', trans: 'som-oh', thai: 'ส้มโอ', level: 2, lesson: 10 },

  // -- Цветы --
  { en: 'FLOWER', trans: 'dok-mai', thai: 'ดอกไม้', level: 1, lesson: 10 },
  { en: 'ROSE', trans: 'gu-laap', thai: 'กุหลาบ', level: 1, lesson: 10 },
  { en: 'ORCHID', trans: 'gluai-mai', thai: 'กล้วยไม้', level: 1, lesson: 10 },

  // -- Посуда и вещи --
  { en: 'GLASS / CUP', trans: 'gaeo', thai: 'แก้ว', level: 1, lesson: 10 },
  { en: 'CUP / BOWL', trans: 'tuuai', thai: 'ถ้วย', level: 1, lesson: 10 },
  { en: 'PLATE', trans: 'jaan', thai: 'จาน', level: 1, lesson: 10 },
  { en: 'BOX', trans: 'glorng', thai: 'กล่อง', level: 1, lesson: 10 },
  { en: 'BOTTLE', trans: 'kuuat', thai: 'ขวด', level: 1, lesson: 10 },
  { en: 'BALL', trans: 'luuk-bon', thai: 'ลูกบอล', level: 1, lesson: 10 },
  { en: 'BOARD', trans: 'gra-daan', thai: 'กระดาน', level: 1, lesson: 10 },
  { en: 'LETTER / MAIL', trans: 'jot-maai', thai: 'จดหมาย', level: 1, lesson: 10 },

  // -- Еда --
  { en: 'EGG', trans: 'kai', thai: 'ไข่', level: 1, lesson: 10 },
  { en: 'MEAT', trans: 'neua', thai: 'เนื้อ', level: 1, lesson: 10 },
  { en: 'BREAD', trans: 'ka-nom-bpang', thai: 'ขนมปัง', level: 1, lesson: 10 },
  { en: 'COOKIE', trans: 'kuk-gii', thai: 'คุกกี้', level: 1, lesson: 10 },
  { en: 'SUGAR', trans: 'naam-dtaan', thai: 'น้ำตาล', level: 1, lesson: 10 },
  { en: 'SALT', trans: 'gleua', thai: 'เกลือ', level: 1, lesson: 10 },
  { en: 'FRIED RICE', trans: 'kaao-pat', thai: 'ข้าวผัด', level: 1, lesson: 10 },

  // -- Дом и техника --
  { en: 'SPOON', trans: 'chon', thai: 'ช้อน', level: 1, lesson: 10 },
  { en: 'FORK', trans: 'som', thai: 'ส้อม', level: 1, lesson: 10 },
  { en: 'KNIFE', trans: 'miit', thai: 'มีด', level: 1, lesson: 10 },
  { en: 'UMBRELLA', trans: 'rom', thai: 'ร่ม', level: 1, lesson: 10 },
  { en: 'REFRIGERATOR', trans: 'dtuu-yen', thai: 'ตู้เย็น', level: 1, lesson: 10 },
  { en: 'COMPUTER', trans: 'kom-piu-dter', thai: 'คอมพิวเตอร์', level: 1, lesson: 10 },
  { en: 'DOCUMENT', trans: 'ek-ga-saan', thai: 'เอกสาร', level: 1, lesson: 10 },
  { en: 'MAGAZINE', trans: 'nit-dta-ya-saan', thai: 'นิตยสาร', level: 2, lesson: 10 },
  { en: 'STAMP', trans: 'sa-dtem', thai: 'แสตมป์', level: 1, lesson: 10 },
  { en: 'VIDEO', trans: 'wi-dii-oh', thai: 'วิดีโอ', level: 1, lesson: 10 },
  { en: 'CASSETTE TAPE', trans: 'muan-tep', thai: 'มวนเทป', level: 2, lesson: 10 },
  { en: 'FILM', trans: 'fim', thai: 'ฟิล์ม', level: 2, lesson: 10 },
  { en: 'BUILDING', trans: 'dteuk', thai: 'ตึก', level: 1, lesson: 10 },
  { en: 'FLOOR / GRADE', trans: 'chan', thai: 'ชั้น', level: 1, lesson: 10 },
  { en: 'DOLL', trans: 'dtuk-ga-dtaa', thai: 'ตุ๊กตา', level: 1, lesson: 10 },
  { en: 'CANDLE', trans: 'tian', thai: 'เทียน', level: 1, lesson: 10 },
  { en: 'NEEDLE', trans: 'kem', thai: 'เข็ม', level: 1, lesson: 10 },
  { en: 'CANDY / LOZENGE', trans: 'luuk-om', thai: 'ลูกอม', level: 1, lesson: 10 },
  { en: 'CIGARETTE', trans: 'bu-rii', thai: 'บุหรี่', level: 1, lesson: 10 },
  { en: 'ASHTRAY', trans: 'tii-kia-bu-rii', thai: 'ที่เขี่ยบุหรี่', level: 2, lesson: 10 },
  { en: 'LETTER OF ALPHABET', trans: 'dtuua-nang-seuu', thai: 'ตัวหนังสือ', level: 2, lesson: 10 },
  { en: 'PRESENT / GIFT', trans: 'korng-kwan', thai: 'ของขวัญ', level: 1, lesson: 10 },

  // -- Природа --
  { en: 'STAR', trans: 'daao', thai: 'ดาว', level: 1, lesson: 10 },
  { en: 'SUN', trans: 'duang-aa-tit', thai: 'ดวงอาทิตย์', level: 1, lesson: 10 },
  { en: 'MOON', trans: 'duang-jan', thai: 'ดวงจันทร์', level: 1, lesson: 10 },

  // -- Места --
  { en: 'ROAD / STREET', trans: 'ta-non', thai: 'ถนน', level: 1, lesson: 10 },
  { en: 'RAILWAY', trans: 'taang-rot-fai', thai: 'ทางรถไฟ', level: 1, lesson: 10 },
  { en: 'CANAL', trans: 'klorng', thai: 'คลอง', level: 1, lesson: 10 },

  // -- Медиа --
  { en: 'MOVIE (COLLOQUIAL)', trans: 'nang', thai: 'หนัง', level: 1, lesson: 10 },
  { en: 'MOVIE / FILM', trans: 'paap-pa-yon', thai: 'ภาพยนตร์', level: 2, lesson: 10 },
  { en: 'STORY', trans: 'reuang', thai: 'เรื่อง', level: 1, lesson: 10 },

  // ── Урок 9 ──────────────────────────────────────────────────────

  // -- Общее --
  { en: 'GARDEN', trans: 'suuan', thai: 'สวน', level: 1, lesson: 9 },
  { en: 'ZOO', trans: 'suuan-sat', thai: 'สวนสัตว์', level: 1, lesson: 9 },
  { en: 'AGE', trans: 'aa-yu', thai: 'อายุ', level: 1, lesson: 9 },
  { en: 'COMPANY', trans: 'bor-ri-sat', thai: 'บริษัท', level: 1, lesson: 9 },
  { en: 'WHY', trans: 'tam-mai', thai: 'ทำไม', level: 1, lesson: 9 },
  { en: 'BECAUSE (SHORT)', trans: 'pror', thai: 'เพราะ', level: 1, lesson: 9 },
  { en: 'BECAUSE', trans: 'pror-waa', thai: 'เพราะว่า', level: 1, lesson: 9 },
  { en: 'IF', trans: 'taa', thai: 'ถ้า', level: 1, lesson: 9 },
  { en: 'TO GET MARRIED', trans: 'dtaeng-ngaan', thai: 'แต่งงาน', level: 1, lesson: 9 },
  { en: 'TO MARRY (SHORT)', trans: 'dtaeng', thai: 'แต่ง', level: 2, lesson: 9 },
  { en: 'SINGLE', trans: 'soht', thai: 'โสด', level: 1, lesson: 9 },
  { en: 'TO LOVE', trans: 'rak', thai: 'รัก', level: 1, lesson: 9 },
  { en: 'BOTH', trans: 'tang-sorng', thai: 'ทั้งสอง', level: 1, lesson: 9 },

  // -- Семья --
  { en: 'FAMILY', trans: 'krorp-kruua', thai: 'ครอบครัว', level: 1, lesson: 9 },
  { en: 'MAN / MALE', trans: 'puu-chaai', thai: 'ผู้ชาย', level: 1, lesson: 9 },
  { en: 'WOMAN / FEMALE', trans: 'puu-ying', thai: 'ผู้หญิง', level: 1, lesson: 9 },
  { en: 'ADULT', trans: 'puu-yai', thai: 'ผู้ใหญ่', level: 1, lesson: 9 },
  { en: 'CHILD', trans: 'dek', thai: 'เด็ก', level: 1, lesson: 9 },
  { en: 'SON OR DAUGHTER', trans: 'luuk', thai: 'ลูก', level: 1, lesson: 9 },
  { en: 'SON', trans: 'luuk-chaai', thai: 'ลูกชาย', level: 1, lesson: 9 },
  { en: 'DAUGHTER', trans: 'luuk-saao', thai: 'ลูกสาว', level: 1, lesson: 9 },
  { en: 'HUSBAND (FORMAL)', trans: 'saa-mii', thai: 'สามี', level: 1, lesson: 9 },
  { en: 'WIFE (FORMAL)', trans: 'pan-ra-yaa', thai: 'ภรรยา', level: 1, lesson: 9 },
  { en: 'HUSBAND (COLLOQ.)', trans: 'puua', thai: 'ผัว', level: 2, lesson: 9 },
  { en: 'WIFE (COLLOQ.)', trans: 'mia', thai: 'เมีย', level: 2, lesson: 9 },
  { en: 'FATHER', trans: 'por', thai: 'พ่อ', level: 1, lesson: 9 },
  { en: 'MOTHER', trans: 'mae', thai: 'แม่', level: 1, lesson: 9 },
  { en: 'OLDER SIBLING', trans: 'pii', thai: 'พี่', level: 1, lesson: 9 },
  { en: 'YOUNGER SIBLING', trans: 'norng', thai: 'น้อง', level: 1, lesson: 9 },
  { en: 'OLDER BROTHER', trans: 'pii-chaai', thai: 'พี่ชาย', level: 1, lesson: 9 },
  { en: 'OLDER SISTER', trans: 'pii-saao', thai: 'พี่สาว', level: 1, lesson: 9 },
  { en: 'YOUNGER BROTHER', trans: 'norng-chaai', thai: 'น้องชาย', level: 1, lesson: 9 },
  { en: 'YOUNGER SISTER', trans: 'norng-saao', thai: 'น้องสาว', level: 1, lesson: 9 },
  { en: 'PATERNAL GRANDFATHER', trans: 'bpuu', thai: 'ปู่', level: 1, lesson: 9 },
  { en: 'PATERNAL GRANDMOTHER', trans: 'yaa', thai: 'ย่า', level: 1, lesson: 9 },
  { en: 'MATERNAL GRANDMOTHER', trans: 'yaai', thai: 'ยาย', level: 1, lesson: 9 },
  { en: 'UNCLE (PARENT\'S OLDER BRO.)', trans: 'lung', thai: 'ลุง', level: 1, lesson: 9 },
  { en: 'AUNT (PARENT\'S OLDER SIS.)', trans: 'bpaa', thai: 'ป้า', level: 1, lesson: 9 },
  { en: 'MOTHER\'S YOUNGER SIBLING', trans: 'naa', thai: 'น้า', level: 2, lesson: 9 },
  { en: 'FATHER\'S YOUNGER SIBLING', trans: 'aa', thai: 'อา', level: 2, lesson: 9 },

  // -- Профессии --
  { en: 'TEACHER', trans: 'kruu', thai: 'ครู', level: 1, lesson: 9 },
  { en: 'PROFESSOR', trans: 'aa-jaan', thai: 'อาจารย์', level: 1, lesson: 9 },
  { en: 'DOCTOR', trans: 'mor', thai: 'หมอ', level: 1, lesson: 9 },
  { en: 'DENTIST', trans: 'mor-fan', thai: 'หมอฟัน', level: 1, lesson: 9 },
  { en: 'NURSE', trans: 'pa-yaa-baan', thai: 'พยาบาล', level: 1, lesson: 9 },
  { en: 'STUDENT', trans: 'nak-rian', thai: 'นักเรียน', level: 1, lesson: 9 },
  { en: 'COLLEGE STUDENT', trans: 'nak-seuk-saa', thai: 'นักศึกษา', level: 1, lesson: 9 },
  { en: 'BUSINESSMAN', trans: 'nak-tu-ra-git', thai: 'นักธุรกิจ', level: 1, lesson: 9 },
  { en: 'WRITER', trans: 'nak-kian', thai: 'นักเขียน', level: 1, lesson: 9 },
  { en: 'PILOT', trans: 'nak-bin', thai: 'นักบิน', level: 1, lesson: 9 },
  { en: 'SINGER', trans: 'nak-rohng', thai: 'นักร้อง', level: 1, lesson: 9 },
  { en: 'POLICEMAN', trans: 'dtam-ruat', thai: 'ตำรวจ', level: 1, lesson: 9 },
  { en: 'SOLDIER', trans: 'ta-haan', thai: 'ทหาร', level: 1, lesson: 9 },
  { en: 'ENGINEER', trans: 'wit-sa-wa-gon', thai: 'วิศวกร', level: 1, lesson: 9 },
  { en: 'FARMER', trans: 'chaao-naa', thai: 'ชาวนา', level: 1, lesson: 9 },
  { en: 'MONK', trans: 'pra', thai: 'พระ', level: 1, lesson: 9 },
  { en: 'MOVIE STAR', trans: 'daa-raa', thai: 'ดารา', level: 1, lesson: 9 },
  { en: 'ROBBER', trans: 'john', thai: 'โจร', level: 1, lesson: 9 },
  { en: 'THIEF', trans: 'ka-moi', thai: 'ขโมย', level: 1, lesson: 9 },
  { en: 'SPY', trans: 'nak-seuup', thai: 'นักสืบ', level: 2, lesson: 9 },
  { en: 'DESIGNER', trans: 'nak-ork-baep', thai: 'นักออกแบบ', level: 2, lesson: 9 },
  { en: 'GOVERNMENT OFFICIAL', trans: 'kaa-raat-cha-gaan', thai: 'ข้าราชการ', level: 2, lesson: 9 },
  { en: 'DRIVER', trans: 'kon-kap-rot', thai: 'คนขับรถ', level: 2, lesson: 9 },
  { en: 'MECHANIC', trans: 'chaang', thai: 'ช่าง', level: 2, lesson: 9 },
  { en: 'BARBER', trans: 'chaang-dtat-pom', thai: 'ช่างตัดผม', level: 2, lesson: 9 },
  { en: 'SECRETARY', trans: 'lee-kaa', thai: 'เลขา', level: 2, lesson: 9 },
  { en: 'HOUSEWIFE', trans: 'mae-baan', thai: 'แม่บ้าน', level: 2, lesson: 9 },
  { en: 'MERCHANT (MALE)', trans: 'por-kaa', thai: 'พ่อค้า', level: 2, lesson: 9 },
  { en: 'MERCHANT (FEMALE)', trans: 'mae-kaa', thai: 'แม่ค้า', level: 2, lesson: 9 },
  { en: 'OWNER', trans: 'jao-korng', thai: 'เจ้าของ', level: 2, lesson: 9 },
  { en: 'SHOP OWNER', trans: 'jao-korng-raan', thai: 'เจ้าของร้าน', level: 2, lesson: 9 },
  { en: 'BUSINESS OWNER', trans: 'jao-korng-tu-ra-git', thai: 'เจ้าของธุรกิจ', level: 2, lesson: 9 },
  { en: 'SELF-EMPLOYED', trans: 'tam-ngaan-suuan-dtuua', thai: 'ทำงานส่วนตัว', level: 2, lesson: 9 },
  { en: 'COMPANY EMPLOYEE', trans: 'tam-ngaan-bor-ri-sat', thai: 'ทำงานบริษัท', level: 2, lesson: 9 },

  // -- Животные --
  { en: 'ANIMAL', trans: 'sat', thai: 'สัตว์', level: 1, lesson: 9 },
  { en: 'PET', trans: 'sat-liang', thai: 'สัตว์เลี้ยง', level: 1, lesson: 9 },
  { en: 'MALE ANIMAL', trans: 'dtuua-puu', thai: 'ตัวผู้', level: 2, lesson: 9 },
  { en: 'FEMALE ANIMAL', trans: 'dtuua-mia', thai: 'ตัวเมีย', level: 2, lesson: 9 },
  { en: 'DOG', trans: 'maa', thai: 'หมา', level: 1, lesson: 9 },
  { en: 'CAT', trans: 'maeo', thai: 'แมว', level: 1, lesson: 9 },
  { en: 'PIG / PORK', trans: 'muu', thai: 'หมู', level: 1, lesson: 9 },
  { en: 'DUCK', trans: 'bpet', thai: 'เป็ด', level: 1, lesson: 9 },
  { en: 'CHICKEN / HEN', trans: 'gai', thai: 'ไก่', level: 1, lesson: 9 },
  { en: 'ELEPHANT', trans: 'chaang', thai: 'ช้าง', level: 1, lesson: 9 },
  { en: 'HORSE', trans: 'maa', thai: 'ม้า', level: 1, lesson: 9 },
  { en: 'COW / OX', trans: 'wuua', thai: 'วัว', level: 1, lesson: 9 },
  { en: 'BUFFALO', trans: 'kwaai', thai: 'ควาย', level: 1, lesson: 9 },
  { en: 'SHELLFISH / OYSTER', trans: 'hoi', thai: 'หอย', level: 1, lesson: 9 },
  { en: 'CRAB', trans: 'bpuu', thai: 'ปู', level: 1, lesson: 9 },
  { en: 'SHRIMP', trans: 'gung', thai: 'กุ้ง', level: 1, lesson: 9 },
  { en: 'BEAR', trans: 'mii', thai: 'หมี', level: 1, lesson: 9 },
  { en: 'BIRD', trans: 'nok', thai: 'นก', level: 1, lesson: 9 },
  { en: 'MONKEY', trans: 'ling', thai: 'ลิง', level: 1, lesson: 9 },
  { en: 'RAT / MOUSE', trans: 'nuu', thai: 'หนู', level: 1, lesson: 9 },
  { en: 'SNAKE', trans: 'nguu', thai: 'งู', level: 1, lesson: 9 },
  { en: 'TIGER', trans: 'seua', thai: 'เสือ', level: 1, lesson: 9 },
  { en: 'LION', trans: 'sing-dtoh', thai: 'สิงโต', level: 1, lesson: 9 },
  { en: 'CROCODILE', trans: 'jo-ra-kee', thai: 'จระเข้', level: 1, lesson: 9 },
  { en: 'TURTLE', trans: 'dtao', thai: 'เต่า', level: 1, lesson: 9 },
  { en: 'BUTTERFLY', trans: 'pii-seua', thai: 'ผีเสื้อ', level: 1, lesson: 9 },
  { en: 'MOSQUITO', trans: 'yung', thai: 'ยุง', level: 1, lesson: 9 },
  { en: 'KANGAROO', trans: 'jing-joh', thai: 'จิงโจ้', level: 2, lesson: 9 },
  { en: 'GOAT', trans: 'pae', thai: 'แพะ', level: 2, lesson: 9 },
  { en: 'SHEEP', trans: 'gae', thai: 'แกะ', level: 2, lesson: 9 },
  { en: 'CAMEL', trans: 'uut', thai: 'อูฐ', level: 2, lesson: 9 },
  { en: 'BAT', trans: 'kaang-kaao', thai: 'ค้างคาว', level: 2, lesson: 9 },
  { en: 'ZEBRA', trans: 'maa-laai', thai: 'ม้าลาย', level: 2, lesson: 9 },
  { en: 'WOLF', trans: 'maa-bpaa', thai: 'หมาป่า', level: 2, lesson: 9 },
  { en: 'FOX', trans: 'maa-jing-jok', thai: 'หมาจิ้งจอก', level: 2, lesson: 9 },
  { en: 'ANT', trans: 'mot', thai: 'มด', level: 2, lesson: 9 },
  { en: 'FLY', trans: 'ma-laeng-wan', thai: 'แมลงวัน', level: 2, lesson: 9 },

  // ── Урок 8 ──────────────────────────────────────────────────────

  // -- Голова и лицо --
  { en: 'HEAD', trans: 'huua', thai: 'หัว', level: 1, lesson: 8 },
  { en: 'FACE', trans: 'naa', thai: 'หน้า', level: 1, lesson: 8 },
  { en: 'FOREHEAD', trans: 'naa-paak', thai: 'หน้าผาก', level: 1, lesson: 8 },
  { en: 'EYE / GRANDFATHER', trans: 'dtaa', thai: 'ตา', level: 1, lesson: 8 },
  { en: 'EYEBROW', trans: 'kiu', thai: 'คิ้ว', level: 1, lesson: 8 },

  { en: 'EAR', trans: 'huu', thai: 'หู', level: 1, lesson: 8 },
  { en: 'NOSE', trans: 'ja-muuk', thai: 'จมูก', level: 1, lesson: 8 },
  { en: 'MOUTH', trans: 'bpaak', thai: 'ปาก', level: 1, lesson: 8 },
  { en: 'TOOTH', trans: 'fan', thai: 'ฟัน', level: 1, lesson: 8 },
  { en: 'TONGUE', trans: 'lin', thai: 'ลิ้น', level: 1, lesson: 8 },

  { en: 'BEARD', trans: 'krao', thai: 'เครา', level: 1, lesson: 8 },


  // -- Тело --
  { en: 'NECK', trans: 'kor', thai: 'คอ', level: 1, lesson: 8 },

  { en: 'STOMACH', trans: 'torng', thai: 'ท้อง', level: 1, lesson: 8 },

  { en: 'HEART', trans: 'huua-jai', thai: 'หัวใจ', level: 1, lesson: 8 },
  { en: 'MILK / BREAST', trans: 'nom', thai: 'นม', level: 1, lesson: 8 },
  { en: 'CHEST', trans: 'ok', thai: 'อก', level: 1, lesson: 8 },
  { en: 'HAND', trans: 'meuu', thai: 'มือ', level: 1, lesson: 8 },
  { en: 'FINGER', trans: 'nio', thai: 'นิ้ว', level: 1, lesson: 8 },
  { en: 'NAIL', trans: 'lep', thai: 'เล็บ', level: 1, lesson: 8 },
  { en: 'ARM', trans: 'kaen', thai: 'แขน', level: 1, lesson: 8 },
  { en: 'LEG', trans: 'kaa', thai: 'ขา', level: 1, lesson: 8 },
  { en: 'KNEE', trans: 'kao', thai: 'เข่า', level: 1, lesson: 8 },
  { en: 'FOOT', trans: 'tao', thai: 'เท้า', level: 1, lesson: 8 },
  { en: 'TOE', trans: 'nio-tao', thai: 'นิ้วเท้า', level: 2, lesson: 8 },
  { en: 'BODY', trans: 'dtuua', thai: 'ตัว', level: 1, lesson: 8 },







  { en: 'PIMPLE', trans: 'sio', thai: 'สิว', level: 2, lesson: 8 },
  { en: 'TEAR', trans: 'naam-dtaa', thai: 'น้ำตา', level: 2, lesson: 8 },

  // -- Одежда --
  { en: 'HAT', trans: 'muuak', thai: 'หมวก', level: 1, lesson: 8 },
  { en: 'SHIRT / BLOUSE', trans: 'seua', thai: 'เสื้อ', level: 1, lesson: 8 },
  { en: 'T-SHIRT', trans: 'sua-yuut', thai: 'เสื้อยืด', level: 1, lesson: 8 },
  { en: 'BUSINESS SUIT', trans: 'sua-nork', thai: 'เสื้อนอก', level: 2, lesson: 8 },
  { en: 'LONG-SLEEVED SHIRT', trans: 'sua-keen-yaao', thai: 'เสื้อแขนยาว', level: 2, lesson: 8 },
  { en: 'SHORT-SLEEVED SHIRT', trans: 'sua-keen-san', thai: 'เสื้อแขนสั้น', level: 2, lesson: 8 },
  { en: 'SKIRT', trans: 'gra-bprohng', thai: 'กระโปรง', level: 1, lesson: 8 },
  { en: 'TROUSERS', trans: 'gaang-geeng', thai: 'กางเกง', level: 1, lesson: 8 },
  { en: 'SHOES', trans: 'rorng-tao', thai: 'รองเท้า', level: 1, lesson: 8 },
  { en: 'SOCK', trans: 'tung-tao', thai: 'ถุงเท้า', level: 1, lesson: 8 },
  { en: 'GLOVE', trans: 'tung-meuu', thai: 'ถุงมือ', level: 2, lesson: 8 },
  { en: 'PANTYHOSE', trans: 'tung-norng', thai: 'ถุงน่อง', level: 2, lesson: 8 },

  { en: 'BELT', trans: 'kem-kat', thai: 'เข็มขัด', level: 2, lesson: 8 },



  { en: 'RING', trans: 'waen', thai: 'แหวน', level: 1, lesson: 8 },
  { en: 'BRACELET', trans: 'gam-lai', thai: 'กำไล', level: 2, lesson: 8 },
  { en: 'RIBBON', trans: 'boo', thai: 'โบว์', level: 2, lesson: 8 },

  // -- Гигиена --
  { en: 'SOAP', trans: 'sabuu', thai: 'สบู่', level: 1, lesson: 8 },
  { en: 'TOOTHBRUSH', trans: 'bpreeng-sii-fan', thai: 'แปรงสีฟัน', level: 1, lesson: 8 },
  { en: 'TOOTHPASTE', trans: 'yaa-sii-fan', thai: 'ยาสีฟัน', level: 1, lesson: 8 },


  // -- Глаголы и действия --
  { en: 'TO WEAR / PUT ON', trans: 'sai', thai: 'ใส่', level: 1, lesson: 8 },
  { en: 'TO TAKE OFF', trans: 'toot', thai: 'ถอด', level: 1, lesson: 8 },
  { en: 'TO GET DRESSED', trans: 'dtaeng-dtuua', thai: 'แต่งตัว', level: 2, lesson: 8 },
  { en: 'TO WASH', trans: 'laang', thai: 'ล้าง', level: 1, lesson: 8 },
  { en: 'TO WASH HAIR', trans: 'sa-pom', thai: 'สระผม', level: 2, lesson: 8 },
  { en: 'TO TAKE A BATH', trans: 'aap-naam', thai: 'อาบน้ำ', level: 2, lesson: 8 },
  { en: 'TO BRUSH TEETH', trans: 'bpraeng-fan', thai: 'แปรงฟัน', level: 2, lesson: 8 },
  { en: 'TO DO LAUNDRY', trans: 'sak-paa', thai: 'ซักผ้า', level: 2, lesson: 8 },
  { en: 'TO ACHE', trans: 'bpuat', thai: 'ปวด', level: 1, lesson: 8 },
  { en: 'TO HURT / INJURE', trans: 'jep', thai: 'เจ็บ', level: 1, lesson: 8 },

  { en: 'TO CUT', trans: 'dtat', thai: 'ตัด', level: 1, lesson: 8 },
  { en: 'TO SHAVE', trans: 'gohn', thai: 'โกน', level: 1, lesson: 8 },
  { en: 'TO SHOP', trans: 'seuu-korng', thai: 'ซื้อของ', level: 2, lesson: 8 },
  { en: 'TO GO SHOPPING', trans: 'bpai-chop-bping', thai: 'ไปชอปปิ้ง', level: 2, lesson: 8 },

  // -- Прочее --
  { en: 'PER', trans: 'la', thai: 'ละ', level: 1, lesson: 8 },


  // ── Урок 6 ──────────────────────────────────────────────────────

  // -- Грамматические частицы и наречия --
  { en: 'TO BE ...ING', trans: 'gamlang', thai: 'กำลัง', level: 1, lesson: 6 },
  { en: 'TO BE GOING TO', trans: 'gamlang-ja', thai: 'กำลังจะ', level: 2, lesson: 6 },
  { en: 'NOT VERY', trans: 'mai-koi', thai: 'ไม่ค่อย', level: 2, lesson: 6 },
  { en: 'NOT AT ALL (particle)', trans: 'loei', thai: 'เลย', level: 1, lesson: 6 },
  { en: 'HOW', trans: 'yaang-rai', thai: 'อย่างไร', level: 1, lesson: 6 },
  { en: 'EVER / USED TO', trans: 'koei', thai: 'เคย', level: 1, lesson: 6 },
  { en: 'NORMALLY', trans: 'bpa-ga-dti', thai: 'ปกติ', level: 1, lesson: 6 },
  { en: 'USUALLY', trans: 'bpra-jam', thai: 'ประจำ', level: 1, lesson: 6 },
  { en: 'OFTEN', trans: 'boi', thai: 'บ่อย', level: 1, lesson: 6 },
  { en: 'YET / STILL', trans: 'yang', thai: 'ยัง', level: 1, lesson: 6 },
  { en: 'ALREADY', trans: 'laeo', thai: 'แล้ว', level: 1, lesson: 6 },
  { en: 'GOOD', trans: 'dii', thai: 'ดี', level: 1, lesson: 6 },
  { en: 'TO WANT TO DO', trans: 'yaak', thai: 'อยาก', level: 1, lesson: 6 },

  // -- Глаголы --
  { en: 'TO LISTEN', trans: 'fang', thai: 'ฟัง', level: 1, lesson: 6 },
  { en: 'TO CHAT', trans: 'kui', thai: 'คุย', level: 1, lesson: 6 },
  { en: 'TO MEET / FIND', trans: 'jer', thai: 'เจอ', level: 1, lesson: 6 },
  { en: 'TO SIT', trans: 'nang', thai: 'นั่ง', level: 1, lesson: 6 },
  { en: 'TO STAND', trans: 'yeuun', thai: 'ยืน', level: 1, lesson: 6 },
  { en: 'TO WALK', trans: 'dern', thai: 'เดิน', level: 1, lesson: 6 },
  { en: 'TO RUN', trans: 'wing', thai: 'วิ่ง', level: 1, lesson: 6 },
  { en: 'TO BUY', trans: 'seuu', thai: 'ซื้อ', level: 1, lesson: 6 },
  { en: 'TO SELL', trans: 'kaai', thai: 'ขาย', level: 1, lesson: 6 },
  { en: 'TO SING / CRY OUT', trans: 'rorng', thai: 'ร้อง', level: 1, lesson: 6 },
  { en: 'TO DANCE (MODERN)', trans: 'dteen', thai: 'เต้น', level: 1, lesson: 6 },
  { en: 'TO DANCE TRADITIONAL', trans: 'ram', thai: 'รำ', level: 1, lesson: 6 },
  { en: 'TO PLAY', trans: 'leen', thai: 'เล่น', level: 1, lesson: 6 },
  { en: 'TO GO SEE SOMEONE', trans: 'bpai-haa', thai: 'ไปหา', level: 2, lesson: 6 },
  { en: 'TO COME SEE SOMEONE', trans: 'maa-haa', thai: 'มาหา', level: 2, lesson: 6 },
  { en: 'TO DRIVE', trans: 'kap', thai: 'ขับ', level: 1, lesson: 6 },
  { en: 'TO RIDE', trans: 'kii', thai: 'ขี่', level: 1, lesson: 6 },
  { en: 'TO FALL', trans: 'dtok', thai: 'ตก', level: 1, lesson: 6 },

  // -- Существительные --
  { en: 'WORK / EVENT', trans: 'ngaan', thai: 'งาน', level: 1, lesson: 6 },
  { en: 'SONG', trans: 'pleeng', thai: 'เพลง', level: 1, lesson: 6 },
  { en: 'BY / VIA', trans: 'doi', thai: 'โดย', level: 1, lesson: 6 },

  // -- Транспорт --
  { en: 'CAR / VEHICLE', trans: 'rot', thai: 'รถ', level: 1, lesson: 6 },
  { en: 'TRAIN', trans: 'rot-fai', thai: 'รถไฟ', level: 2, lesson: 6 },
  { en: 'SUBWAY', trans: 'rot-fai-dtai-din', thai: 'รถไฟใต้ดิน', level: 2, lesson: 6 },
  { en: 'BUS', trans: 'rot-mee', thai: 'รถเมล์', level: 2, lesson: 6 },
  { en: 'SONGTAEW', trans: 'sorng-taeo', thai: 'สองแถว', level: 2, lesson: 6 },
  { en: 'TRICYCLE TAXI', trans: 'saam-lor', thai: 'สามล้อ', level: 2, lesson: 6 },
  { en: 'TUK-TUK', trans: 'dtuk-dtuk', thai: 'ตุ๊กตุ๊ก', level: 1, lesson: 6 },
  { en: 'MOTORCYCLE', trans: 'mor-dter-sai', thai: 'มอเตอร์ไซ', level: 1, lesson: 6 },
  { en: 'BICYCLE', trans: 'jak-gra-yaan', thai: 'จักรยาน', level: 2, lesson: 6 },
  { en: 'AIRPLANE', trans: 'kreuang-bin', thai: 'เครื่องบิน', level: 2, lesson: 6 },
  { en: 'BOAT', trans: 'reua', thai: 'เรือ', level: 2, lesson: 6 },

  // -- Природа --
  { en: 'RAIN', trans: 'fon', thai: 'ฝน', level: 1, lesson: 6 },
  { en: 'SNOW', trans: 'hi-ma', thai: 'หิมะ', level: 1, lesson: 6 },
  { en: 'TREE', trans: 'dton-mai', thai: 'ต้นไม้', level: 1, lesson: 6 },
  { en: 'MOUNTAIN', trans: 'puu-kao', thai: 'ภูเขา', level: 1, lesson: 6 },
  { en: 'SEA', trans: 'ta-lee', thai: 'ทะเล', level: 1, lesson: 6 },
  { en: 'RIVER', trans: 'mae-naam', thai: 'แม่น้ำ', level: 1, lesson: 6 },
  { en: 'SOIL / EARTH', trans: 'din', thai: 'ดิน', level: 1, lesson: 6 },
  { en: 'WIND', trans: 'lom', thai: 'ลม', level: 1, lesson: 6 },
  { en: 'FIRE', trans: 'fai', thai: 'ไฟ', level: 1, lesson: 6 },

  // -- Прочее --
  { en: 'MAY I SPEAK WITH', trans: 'kor-saai-gap', thai: 'ขอสายกับ', level: 2, lesson: 6 },
];
